linuxdeepin/deepin-unioncode

src/tools/debugadapter/dapsession.cpp, src/tools/debugadapter/debugmanager.cpp, src/tools/debugadapter/debugmanager.h
terminate request not processed, end gdb
process to abort debug.
Log: fix abort debug not work
Change-Id: I174d2f308421c8190755fe1ea16b2714d84a5df1
=> fix: abort debug not work

src/tools/eventrecorder/preload/vdsopreload.c
remove gettimeofday function to avoid build
failed on some platform
Log: bug fix
Change-Id: I70175e646fd95005cb2c8fdd26b8e0731c8690c3
=> fix: remove unused function

debian/control
fix build error due to lack of dependencies of llvm-dev and doxygen
=> fix: build error due to lack of dependencies

debian/control
dh-systemd is a temporary depend, remove it now.
Log: control changed
Change-Id: Ie2c6f636b110cb6cfec24f19afe39d8b8f12f1e0
=> feat: remove unused depend

assets/translations/en_US.ts, assets/translations/zh_CN.ts, src/plugins/codegeex/codegeex.qrc, src/plugins/codegeex/codegeexmanager.cpp, src/plugins/codegeex/codegeexmanager.h, src/plugins/codegeex/widgets/codeeditcomponent.cpp, src/plugins/codegeex/widgets/codegeexwidget.cpp, src/plugins/codegeex/widgets/codegeexwidget.h, src/plugins/codegeex/widgets/intropage.cpp, src/plugins/codegeex/widgets/messagecomponent.cpp
=> feat: add create session proccess

src/plugins/codegeex/data/messagedata.cpp, src/plugins/codegeex/data/messagedata.h, src/plugins/codegeex/widgets/messagecomponent.cpp, src/plugins/codegeex/widgets/messagecomponent.h
fix code edit component display issue
=> fix: codegeex message display issue

src/plugins/codeeditor/mainframe/naveditmainwindow.cpp, src/plugins/core/mainframe/windowkeeper.cpp, src/plugins/debugger/interface/menumanager.cpp, src/plugins/recent/mainframe/displayitemdelegate.cpp, src/plugins/recent/mainframe/displayitemdelegate.h, src/plugins/recent/mainframe/displayrecentview.cpp, src/plugins/recent/mainframe/displayrecentview.h, src/plugins/recent/mainframe/recentdisplay.cpp
DTK Changed-Project and doc list in recent plugin
=> feat: DTK Changed-Project and doc list in recent plugin

src/plugins/codegeex/widgets/historylistwidget.cpp, src/plugins/codegeex/widgets/sessionrecorditem.cpp, src/plugins/codegeex/widgets/sessionrecorditem.h
historylistwidget dosen`t close after clicked historyItem
=> fix: historylistwidget dosen`t close after clicked historyItem

src/plugins/cxx/cmake/project/mainframe/cmakeasynparse.cpp
The expand icon of project treeview don't show.
=> fix: The expand icon of project treeview don't show

src/plugins/project/projectcore.cpp
Secondary popups of openProject are not displayed
=> fix: Secondary popups of openProject are not displayed

src/plugins/core/mainframe/windowkeeper.cpp, src/plugins/recent/mainframe/recentdisplay.cpp, src/services/window/windowelement.h
1.Set the default state to full screen
2.Adjusting the layout of the recentWindow
3.Adjust the minimum height of the mainWindowAdjust the minimum height of the window
=> feat: reset window Minimumsize

src/plugins/builder/mainframe/buildmanager.cpp
The "build cancel" button in the menu bar has a redundant icon
=> fix: The "build cancel" button in the menu bar has a redundant icon

src/plugins/core/mainframe/plugindialog.cpp
Incomplete display of the plug-in window
=> fix: Incomplete display of the plug-in window

src/plugins/codeeditor/textedittabwidget/textedittabbar.cpp, src/plugins/codeeditor/textedittabwidget/textedittabwidget.cpp
Replace ui with DTk when closing a window with unsaved changes
=> fix: Replace ui with DTk when closing a window with unsaved changes

src/plugins/cxx/cmake/project/mainframe/properties/buildpropertywidget.cpp, src/plugins/cxx/cmake/project/mainframe/properties/configureprojpane.cpp, src/plugins/cxx/cmake/project/mainframe/properties/runconfigpane.cpp, src/plugins/cxx/cmake/project/mainframe/properties/stepspane.cpp, src/plugins/java/gradle/project/properties/gradleconfigpropertywidget.cpp, src/plugins/java/maven/project/properties/mavenconfigpropertywidget.cpp, src/plugins/reversedebug/loadcoredialog.cpp
=> fix: Button text modification

src/plugins/cxx/cmake/project/cmakeprojectgenerator.cpp, src/plugins/cxx/cmake/project/properties/runCfgWidget/runpropertypage.cpp, src/plugins/cxx/cmake/project/properties/runCfgWidget/runpropertypage.h, src/plugins/template/templatemanager.cpp
Log:
Change-Id: Id66b6ec9968475259b1f5b9c81098a854dc342ef
=> refactor: [cxxplugin]file renamed

src/plugins/core/uicontroller/controller.cpp, src/plugins/debugger/debuggerplugin.cpp, src/plugins/debugger/debugmanager.cpp, src/plugins/debugger/debugmanager.h
watchData widget can`t show when switching navigation
=> fix: [debugger] watchData widget can`t show when switching navigation

src/plugins/debugger/dap/dapdebugger.cpp, src/plugins/debugger/dap/debugsession.cpp, src/tools/debugadapter/dapproxy.h, src/tools/debugadapter/dapsession.cpp, src/tools/debugadapter/dapsession.h, src/tools/debugadapter/debugger/debugger.h, src/tools/debugadapter/debugger/gdbmi/gdbdebugger.cpp, src/tools/debugadapter/debugger/gdbmi/gdbdebugger.h, src/tools/debugadapter/debugger/javascript/jsdebugger.cpp, src/tools/debugadapter/debugger/javascript/jsdebugger.h, src/tools/debugadapter/debugmanager.cpp, src/tools/debugadapter/debugmanager.h
1.While GDB is running, the input command is invalid and needs to be paused before executing the command.” 2.Optimize operations related to breakpoints
=> fix: [debugger] can`t operating when project is running

src/plugins/cxx/cmake/project/cmakeasynparse.cpp
When adding files in projectTreeView, the files are added to the wrong directory
=> fix: [project] The file was added to the wrong directory

src/plugins/core/gui/navigationbar.cpp, src/plugins/core/uicontroller/mainwindow.cpp
do not show context menu when right-clicked the navigationbar
=> fix: [mainWindow] empty context menu when right-clicked the navigationbar

src/scripts/prettyprinters/qt.py
=> fix: [debugger] gdb crash when parse QVariant

src/plugins/project/mainframe/projecttree.cpp
remove "delete File" option when right-clicked a dir
Bug: https://pms.uniontech.com/bug-view-246243.html
=> fix: [projectTree] remove "delete File" option when right-clicked a dir

src/plugins/builder/mainframe/buildmanager.cpp
Lines 54 to 57 were removed because of a problem with repeated destructions
=> fix: [builder] Resolve the crash issue

src/common/util/eventdefinitions.h, src/plugins/core/gui/dockheader.cpp, src/plugins/core/gui/dockheader.h, src/plugins/core/gui/workspacewidget.cpp, src/plugins/core/gui/workspacewidget.h, src/plugins/core/uicontroller/controller.cpp, src/plugins/core/uicontroller/mainwindow.cpp, src/plugins/core/uicontroller/mainwindow.h, src/plugins/project/mainframe/projecttree.cpp, src/plugins/project/transceiver/projectcorereceiver.cpp, src/services/window/windowservice.h
=> feat: [core] add header to dock Widget

src/plugins/binarytools/mainframe/binarytoolsconfigview.cpp, src/plugins/binarytools/mainframe/binarytoolsconfigview.h, src/plugins/binarytools/mainframe/binarytoolsdialog.cpp, src/plugins/binarytools/mainframe/binarytoolsdialog.h
Fixed an issue in binary dialog where renaming occurred after clicking Cancel
Bug: https://pms.uniontech.com/bug-view-246913.html
=> fix: [binarytools] rename issue in binarytools dialog

src/plugins/option/optioncore/CMakeLists.txt, src/plugins/option/optioncore/mainframe/shortcutedit.cpp, src/plugins/option/optioncore/mainframe/shortcutedit.h, src/plugins/option/optioncore/mainframe/shortcutsettingwidget.cpp
Log: Fixed that shortcut keys could not be cancelled, added right-click menu to cancel shortcut keys
Bug: https://pms.uniontech.com/bug-view-246835.html
=> fix: [optioncore] Fixed that shortcut keys could not be cancelled

src/plugins/cxx/cmake/project/properties/bulidCfgWidget/stepspane.cpp, src/plugins/cxx/cmake/project/properties/configWidget/configureprojpane.cpp, src/plugins/cxx/cmake/project/properties/configutil.h
Use QStringList for build arguments, same as in steps pane
Log: bug fix
Change-Id: I8831a8be8d9103511dd54d3085146b3a17f7db5a
=> fix: [builder] build failed when build parameters used

assets/templates/projects/cmake/console/CMakeLists.txt
Log: add "-g" compile option while the cmake version less than 3.16
Bug: https://pms.uniontech.com/bug-view-255883.html
=> fix: [template] can't debug default template

src/plugins/debugger/dap/dapdebugger.cpp
=> fix: [dapdebugger] crash when close ide

src/plugins/core/uicontroller/controller.cpp
Fixed an issue where the contextwidget would not expand when the contextwidget tab was clicked when the dockwidget was hidden Log: fix an issue
=> fix: [core] can't expand when tapping the context widget tab

src/plugins/console/consolemanager.cpp, src/plugins/console/consolemanager.h
fixed removeButton should be disabled while activating only one console
=> fix: [console] removeButton should be disabled

src/plugins/find/constants.h, src/plugins/find/gui/advancedsearchwidget.cpp, src/plugins/find/gui/searchresultitemdelegate.cpp, src/plugins/find/gui/searchresultmodel.cpp, src/plugins/find/maincontroller/worker/searchreplaceworker.cpp, src/plugins/find/maincontroller/worker/searchreplaceworker_p.h
=> fix: [search] Fixed an issue where advanced search could not find results

src/plugins/cxx/cmake/cmakegenerator.cpp, src/plugins/cxx/cmake/project/cmakeprojectgenerator.cpp, src/plugins/cxx/cmake/project/properties/configutil.cpp, src/tools/debugadapter/dapsession.cpp
=> fix: [run] incorret arguments when run/debug application

src/plugins/codeeditor/gui/completion/codecompletionmodel.cpp, src/plugins/codeeditor/gui/completion/codecompletionwidget.cpp, src/plugins/codeeditor/gui/completion/codecompletionwidget.h, src/plugins/cxx/lexer/scilexercpp.cpp
=> fix: Fixed an issue where the completion was abnormal in some scenarios

src/plugins/codegeex/codegeexmanager.h, src/plugins/codegeex/copilot.cpp, src/plugins/codegeex/copilot.h, src/plugins/codegeex/option/detailwidget.cpp, src/plugins/codegeex/option/detailwidget.h
=> feat: [codegeex] add options of locale

src/common/project/projectinfo.h, src/plugins/cxx/cmake/cmakedebug.cpp, src/plugins/cxx/cmake/model/kitlistmodel.cpp, src/plugins/cxx/cmake/option/kit.cpp, src/plugins/cxx/cmake/option/kit.h, src/plugins/cxx/cmake/option/kitmanager.cpp, src/plugins/cxx/cmake/project/cmakeprojectgenerator.cpp, src/plugins/cxx/cmake/project/properties/bulidCfgWidget/buildpropertypage.cpp, src/plugins/cxx/cmake/project/properties/configutil.cpp, src/plugins/cxx/cmake/project/properties/kitpage/kitpage.cpp, src/plugins/cxx/cmake/project/properties/kitpage/kitpage.h, src/plugins/cxx/cmake/settings/kitoptionwidget.cpp, src/plugins/debugger/dap/dapdebugger.cpp
=> feat: [cmake] Added feature for switching cmake kit

assets/translations/en_US.ts, assets/translations/zh_CN.ts, src/common/lsp/client/client.cpp, src/plugins/codeeditor/codeeditor.cpp, src/plugins/codeeditor/codeeditor.h, src/plugins/codeeditor/gui/tabwidget.cpp, src/plugins/codeeditor/gui/workspacewidget.cpp, src/plugins/codeeditor/symbol/symbolbar.cpp, src/plugins/codeeditor/symbol/symbolbar.h, src/plugins/codeeditor/symbol/symbolmanager.cpp, src/plugins/codeeditor/symbol/symbolmanager.h, src/plugins/codeeditor/symbol/symbolview.cpp, src/plugins/codeeditor/symbol/symbolview.h, src/plugins/codeeditor/symbol/symbolwidget.cpp, src/plugins/codeeditor/symbol/symbolwidget.h, src/plugins/option/optioncore/mainframe/optionsdialog.cpp, src/plugins/project/projectcore.cpp
=> feat: [symbol] Add Outline for current document

src/app/main.cpp, src/common/util/commandparser.cpp, src/common/util/commandparser.h, src/common/util/eventdefinitions.h, src/plugins/project/projectcore.cpp, src/plugins/project/transceiver/projectcorereceiver.cpp, src/plugins/project/transceiver/projectcorereceiver.h
=> feat: support open projcet by terminal

src/plugins/codeeditor/gui/tabwidget.cpp, src/plugins/codeeditor/lsp/lspclientmanager.cpp, src/plugins/codeeditor/lsp/lspclientmanager.h, src/plugins/codeeditor/symbol/symbolbar.cpp, src/plugins/codeeditor/symbol/symbolbar.h
=> fix: [symbolbar] Fix issue of UI

src/plugins/cxx/cmake/project/cmakeprojectgenerator.cpp, src/plugins/cxx/cmake/project/properties/bulidCfgWidget/buildpropertypage.cpp, src/plugins/cxx/cmake/project/properties/configutil.cpp, src/plugins/cxx/cmake/project/properties/configutil.h, src/plugins/cxx/cmake/project/properties/runCfgWidget/runpropertypage.cpp, src/plugins/debugger/runner/runner.cpp, src/plugins/project/mainframe/projecttree.cpp, src/plugins/project/mainframe/projecttree.h, src/plugins/project/projectcore.cpp, src/plugins/project/transceiver/projectcorereceiver.cpp, src/services/project/projectservice.h
Log: Support automatic switching of the application after toggling between debug/release compilation modes, and fix related bugs.
=> fix: [project] debug/release switch issue

assets/configures/editorstyle_cpp.support, src/common/lsp/client/client.cpp, src/common/lsp/client/client.h, src/common/lsp/protocol/new/extendedproject.cpp, src/common/lsp/protocol/new/extendedproject.h, src/plugins/codeeditor/lsp/languageclienthandler.cpp, src/plugins/codeeditor/lsp/languageworker.cpp, src/plugins/codeeditor/lsp/lspclientmanager.cpp, src/plugins/codeeditor/lsp/private/languageclienthandler_p.h, src/plugins/cxx/lexer/scilexercpp.cpp, src/tools/languageadapter/main.cpp
Fixed a coloring issue where `QT_DEBUG` macro could not be recognized
Log: fix issue
=> fix: Fixed code coloring issues

src/plugins/python/python/pythongenerator.cpp
Log: as title
bug: https://pms.uniontech.com/bug-view-267551.html
=> fix: [python] output can not display immediately

src/plugins/filebrowser/mainframe/filetreeview.cpp, src/plugins/filebrowser/mainframe/filetreeview.h
as title
Bug: https://pms.uniontech.com/bug-view-245901.html
Log: fix bug
=> fix: Fixed an issue where files could not be created in file browsing view

src/plugins/codeeditor/lsp/languageworker.cpp
The length of the obtained text exceeds the maximum text length
Log: fix issue
=> fix: Fix app crash issue

src/plugins/debugger/interface/breakpointview.h
=> fix: [translations] translations issue of breakpoint`s view

src/plugins/cxx/cmake/builder/generator/cmakebuildergenerator.cpp
=> fix: [cmake] can not show cmake error at issue list

src/plugins/codeeditor/gui/private/tabwidget_p.h, src/plugins/codeeditor/gui/private/workspacewidget_p.h, src/plugins/codeeditor/gui/tabbar.cpp, src/plugins/codeeditor/gui/tabbar.h, src/plugins/codeeditor/gui/tabwidget.cpp, src/plugins/codeeditor/gui/tabwidget.h, src/plugins/codeeditor/gui/texteditor.cpp, src/plugins/codeeditor/gui/texteditor.h, src/plugins/codeeditor/gui/workspacewidget.cpp
=> fix: [editor] Fixed an issue where documents could not be synchronized

src/plugins/collaborators/collaborators.cpp, src/plugins/core/modules/pluginmanagermodule.cpp, src/plugins/core/uicontroller/controller.cpp, src/plugins/core/uicontroller/controller.h, src/plugins/find/findplugin.cpp, src/plugins/linglong/linglongplugin.cpp, src/services/window/windowservice.h
Delayed creation improves efficiency
Log:
Change-Id: Ia87a3799846ee2f08ecee17d9b6cd4aa867aac86
=> chore: refactor regitster function

src/plugins/debugger/dap/dapdebugger.cpp, src/tools/debugadapter/debugger/gdbmi/gdbdebugger.cpp, src/tools/debugadapter/debugger/gdbmi/gdbmi.h
1.No prompt information when interrupting a Python project. 2.No response when debugging an application crash.
Log: as title
=> fix: [debugger] issues when debugging project

src/plugins/debugger/dap/debugsession.cpp
memory release issue
Log: as title
=> fix: [debugger] crash when close ide

src/plugins/option/optioncore/mainframe/optionsdialog.cpp
=> fix: [pluginmanager] crash when open optionsdialog in plugins

src/tools/debugadapter/debugger/gdbmi/gdbmi.cpp
=> fix: [debugger] crash when fetch threads

src/common/actionmanager/command.cpp, src/common/actionmanager/command.h, src/plugins/builder/mainframe/buildmanager.cpp, src/plugins/codeeditor/gui/tabwidget.cpp, src/plugins/core/locator/actionlocator.cpp, src/plugins/option/optioncore/mainframe/shortcutsettingwidget.cpp
as title
Bug: https://pms.uniontech.com/bug-view-255293.html
Log: fix bug
=> fix: The shortcuts are not synchronized with the locator content

src/plugins/codeeditor/gui/private/texteditor_p.cpp
as title
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-270153.html
=> fix: Fix cursor anomaly issue

src/plugins/codeeditor/gui/workspacewidget.cpp
If newly opened files are already open in other tabwidgets, their content changes are not synchronized
Log: fix issue
=> fix: Fixed an issue with editor document synchronization

src/plugins/codeeditor/gui/workspacewidget.cpp
=> fix: Fixed an issue where `Ctrl + Tab` could not be used to toggle open files

src/plugins/codegeex/widgets/referencepopup.cpp
=> fix: [codegeex] build can't import QPainterPath class

src/plugins/codegeex/codegeex/copilotapi.cpp, src/plugins/codegeex/codegeex/copilotapi.h, src/plugins/codegeex/copilot.cpp, src/plugins/codegeex/copilot.h
=> fix: [autoComplete] optimized complete logic

src/plugins/option/optioncore/mainframe/shortcutsettingwidget.cpp, src/plugins/option/optioncore/mainframe/shortcutsettingwidget.h
as title
Bug: https://pms.uniontech.com/bug-view-277235.html
Bug: https://pms.uniontech.com/bug-view-277115.html
Log: fix bug
=> fix: Reset the shortcut key search status when close the Settings dialog

src/plugins/codegeex/codegeex/askapi.cpp, src/plugins/codegeex/codegeexmanager.h, src/plugins/codegeex/widgets/inlinechatwidget.cpp
as title
Log: Change the Lite model name
=> fix: Change the Lite model name

src/plugins/codeeditor/gui/texteditor.cpp
When the focus is in the editor, cannot exit the dialog through Esc
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-277671.html
=> fix: [InlineChat] Fixed an issue where the inline chat dialog could not exit

src/plugins/option/optioncore/mainframe/shortcutsettingwidget.cpp
When the imported shortcut key has a format problem, the shortcut key is displayed incorrectly
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-277815.html
=> fix: [shortcut] Fix shortcut key import issue

src/plugins/codeeditor/gui/tabwidget.cpp
=> fix: [editor] Fix the `replaceRange` interface issue

src/plugins/cxx/cmake/project/cmakeprojectgenerator.cpp, src/plugins/cxx/cmake/project/cmakeprojectgenerator.h, src/scripts/CMakeLists.txt, src/scripts/compiledb/update_compile_commands.py
The `compile_commands.json` file is missing some header files
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-282343.html
=> fix: Cland cannot correctly identify syntax errors

src/plugins/codegeex/widgets/inlinechatwidget.cpp
The chat view display is abnormal due to the pre-input status
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-282523.html
=> fix: [inline chat] The chat view display is abnormal

src/plugins/codegeex/codegeex/copilotapi.cpp, src/plugins/codegeex/copilot.cpp, src/plugins/codegeex/widgets/codegeexwidget.cpp, src/plugins/codegeex/widgets/intropage.cpp
Log: as title
bug: https://pms.uniontech.com/bug-view-285053.html
=> fix: [codegeex] incorecct ui and display logic

src/plugins/codegeex/codegeex.cpp, src/plugins/codegeex/codegeexmanager.cpp, src/plugins/codegeex/codegeexmanager.h, src/plugins/codegeex/widgets/inputeditwidget.cpp, src/services/ai/aiservice.h
=> feat: [AI] add interface of askquestion

src/app/main.cpp, src/common/settings/settings.cpp, src/plugins/codegeex/codegeexmanager.cpp, src/plugins/codegeex/option/codegeexoptionwidget.cpp, src/plugins/codegeex/option/detailwidget.cpp, src/plugins/option/optioncore/mainframe/profilesettingwidget.cpp
Refactored configuration storage mechanism across multiple components to use
the unified settings system:
- Migrated language settings from file-based to settings-based storage
- Updated CodeGeeX configuration to use OptionManager
- Refactored profile settings to use centralized storage
- Added compatibility code for smooth transition from old storage format
- Cleaned up deprecated file-based storage methods
The changes improve configuration management consistency and maintainability
by centralizing all settings into a single system.
Log: refactored configuration storage to use unified settings system
=> refactor: [settings] migrate config storage to unified settings system

src/plugins/core/session/sessiondialog.cpp, src/plugins/core/session/sessionlistview.cpp, src/plugins/core/session/sessionlistview.h, src/plugins/core/session/sessionmanager.cpp, src/plugins/project/mainframe/projecttree.cpp, src/plugins/project/mainframe/projecttree.h, src/plugins/project/transceiver/projectcorereceiver.cpp, src/plugins/recent/mainframe/sessionitemwidget.cpp
- Fix session clone operation by using correct cloneSession instead of rename
- Improve session deletion handling with keyboard support
- Optimize session list widget removal logic
- Add session created signal and connection
- Change project tree clear method name to closeAllProjects for clarity
- Add UI switch to edit mode when loading session
- Only save session when not in default virgin state
Log: fix session management issues and enhance user interaction
=> fix: [session] improve session management and UI interaction

src/plugins/builder/tasks/taskmanager.cpp, src/plugins/codegeex/codegeex/copilotapi.cpp
1. inlinchat can`t work when file language is unknown 
2. [Double-clicking the error item did not open the file where the error occurs.
=> fix: 2 commit of bugs

src/plugins/codeeditor/statusbar/encodecombobox.cpp
as title
Log: Fix compilation errors
=> fix: The compilation failed

src/plugins/codeeditor/statusbar/encodecombobox.cpp
Log:
Change-Id: I7ea9433a154763891c309be4eb75f9fcf8493c64
=> fix: build failed missing header

src/plugins/cxx/cmake/project/cmakeasynparse.cpp, src/plugins/cxx/cmake/project/cmakeasynparse.h, src/plugins/cxx/cmake/project/cmakeprojectgenerator.cpp, src/plugins/cxx/cmake/project/cmakeprojectgenerator.h, src/plugins/java/gradle/project/gradleasynparse.cpp, src/plugins/java/gradle/project/gradleprojectgenerator.cpp, src/plugins/java/maven/project/mavenasynparse.cpp, src/plugins/java/maven/project/mavenprojectgenerator.cpp, src/plugins/project/mainframe/projectdelegate.cpp, src/plugins/project/mainframe/projectmodel.cpp, src/plugins/project/mainframe/projectmodel.h, src/plugins/project/mainframe/projecttree.cpp, src/services/project/directoryasynparse.cpp, src/services/project/directorygenerator.cpp, src/services/project/projectservice.h
Refactored project tree icon loading mechanism and parsing process to improve
performance and maintainability:
- Moved icon loading from individual items to ProjectModel data() method
- Added ProjectItemRole enum for icon name and file path roles
- Replaced direct icon setting with role-based data storage
- Implemented stop mechanism for cmake async parsing
- Moved cmake parser to separate thread for better responsiveness
- Unified parsing state role usage across project types
- Removed redundant icon loading code from various parsers
- Added sorting capability to project tree
Log: Optimize project tree icon loading and parsing mechanism
=> refactor: [project] Optimize project tree icon loading and parsing

src/plugins/debugger/interface/stackframemodel.cpp, src/tools/debugadapter/debugmanager.cpp
=> fix: [debugger] crash when debugging

src/plugins/codeeditor/statusbar/encodecombobox.cpp, src/plugins/find/gui/searchresultitemdelegate.cpp, src/plugins/find/gui/searchresultitemdelegate.h, src/plugins/find/gui/searchresultmodel.cpp, src/plugins/find/maincontroller/worker/searchreplaceworker.cpp
Enhance search result handling and display in multiple aspects:
- Add content truncation for large search results to prevent parsing issues
- Optimize search result text display with proper trimming and formatting
- Improve regex pattern for parsing search results with non-greedy matching
- Add content side length limit for better readability
- Refactor result model to handle data updates more efficiently
The changes focus on improving stability and user experience when handling large search results, while maintaining performance.
Log: fix search result display and parsing issues
=> fix: [find] improve search result display and parsing

src/plugins/codeeditor/gui/tabwidget.cpp, src/plugins/core/session/sessionmodel.cpp, src/plugins/cxx/cmake/project/cmakeasynparse.cpp, src/plugins/cxx/cmake/project/cmakeprojectgenerator.cpp, src/plugins/java/gradle/project/gradleasynparse.cpp, src/plugins/java/gradle/project/gradleprojectgenerator.cpp, src/plugins/java/maven/project/mavenasynparse.cpp, src/plugins/java/maven/project/mavenprojectgenerator.cpp, src/plugins/project/mainframe/projectdelegate.cpp, src/plugins/project/mainframe/projectmodel.cpp, src/plugins/project/mainframe/projecttree.cpp, src/plugins/project/mainframe/projecttree.h, src/plugins/project/projectcore.cpp, src/plugins/recent/mainframe/recentdisplaywidget.cpp, src/services/project/directoryasynparse.cpp, src/services/project/directoryasynparse.h, src/services/project/directorygenerator.cpp, src/services/project/directorygenerator.h, src/services/project/projectservice.h
Refactored directory parsing implementation to improve performance and
maintainability. Major changes include:
- Replaced manual directory traversal with QDirIterator for better performance
- Added proper sorting of items (directories first, then case-insensitive)
- Implemented expand state persistence for project tree nodes
- Improved file monitoring and dynamic updates
- Cleaned up role definitions and moved them to Project namespace
- Streamlined signal/slot connections for item updates
Log: Refactored directory parsing and project tree management
=> refactor: [project] Improve directory parsing and expand state management

src/plugins/python/python/project/properties/configpropertywidget.cpp
Some python interpreters are not visible in the `Project Properties Dialog`
Log: fix issue
=> fix: [python] Python interpreter

src/plugins/python/installer/pipinstaller.cpp, src/plugins/python/python/option/interpreterwidget.cpp, src/plugins/python/utils/utils.cpp, src/plugins/python/utils/utils.h
=> feat: [python] Added pip source configuration

src/plugins/core/session/sessiondialog.cpp, src/plugins/core/session/sessionlistview.cpp, src/plugins/core/session/sessionlistview.h
Enhance session management UX by automatically closing the session dialog
when user switches to a different session. This improvement streamlines
the workflow by:
- Adding new sessionSwitched signal in SessionListView
- Connecting dialog close action to session switch event
- Maintaining clean state transitions during session changes
Log: Add auto-close behavior to session dialog after session switch
Bug: https://pms.uniontech.com/bug-view-298077.html
=> fix: [session] Add auto-close dialog after session switch

src/plugins/core/gui/plugindetailsview.cpp, src/plugins/core/gui/plugindetailsview.h
as title
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-272421.html
=> fix: [UI] Change the background color to active color

src/plugins/core/notify/constants.h, src/plugins/core/notify/gui/itemdelegate.cpp, src/plugins/core/notify/gui/itemdelegate.h, src/plugins/core/notify/gui/notificationcenterwidget.cpp, src/plugins/core/notify/gui/notificationlistview.cpp, src/plugins/core/notify/gui/notificationmodel.cpp, src/plugins/core/notify/gui/notificationmodel.h
Refactored notification item delegate to use direct painting instead of widget-based
approach for better performance and visual consistency. Key changes include:
- Removed widget-based item delegate implementation
- Added custom paint methods for background, icon, text and buttons
- Implemented mouse event handling for close button and action buttons
- Added text layout handling with proper wrapping and elision
- Introduced constants for layout metrics and spacing
- Added new roles and data structure for action button info
The new implementation provides smoother scrolling and consistent styling while
reducing memory usage by eliminating widget creation for each item.
Log: Refactor notification item delegate to use paint-based rendering
Bug: https://pms.uniontech.com/bug-view-272445.html
=> fix: [notify] Rewrite notification item delegate with paint method

src/services/project/directoryasynparse.cpp, src/services/project/directoryasynparse.h, src/services/project/directorygenerator.cpp, src/services/project/directorygenerator.h, src/services/project/projectgenerator.cpp
QStandItem is not thread-safe, and operating on the QStandItem object in the thread causes the program to crash
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-298511.html
=> fix: [DirectoryAsynParse] Program crash

src/scripts/prettyprinters/qt.py, src/tools/debugadapter/debugger/gdbmi/gdbdebugger.cpp, src/tools/debugadapter/debugger/gdbmi/gdbdebugger.h, src/tools/debugadapter/debugger/gdbmi/gdbmi.cpp
When the variable is dynamic, it cannot be determined whether it has child members through attributes. Directly obtain it to observe whether it has child members’ is ‘When the variable is dynamic, it cannot be determined whether it has child members through properties. Directly access it to observe whether it has child members
Log: as title
=> fix: [debugger]  Error in displaying QList member variables

src/base/ai/abstractllm.h, src/common/util/eventdefinitions.h, src/plugins/aimanager/aimanager.cpp, src/plugins/aimanager/openai/openaicompatibleconversation.cpp, src/plugins/aimanager/openai/openaicompatiblellm.cpp, src/plugins/aimanager/openai/openaicompatiblellm.h
1.event when LLM changed
2.modelname
3.LLM`s idle state to description LLM can send request or not
Log: as title
=> feat: [aiManager] add interface

src/app/main.cpp, src/plugins/option/optioncore/mainframe/profilesettingwidget.cpp
as title
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-298047.html
=> fix: Incorrect language modification prompt

src/services/project/directorygenerator.cpp
as title
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-298495.html
=> fix: [project] Project information could not be obtained correctly

src/plugins/codegeex/codegeex/copilotapi.cpp, src/plugins/codegeex/copilot.cpp
Log: as title
Bug: https://pms.uniontech.com/bug-view-298313.html
=> fix: [Ai] `add comment` function will delete selecetd code

src/plugins/core/uicontroller/controller.cpp
as title
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-298035.html
=> fix: [mainwidow] The software page is not fully displayed

src/plugins/codegeex/codegeex/copilotapi.cpp, src/plugins/codegeex/codegeex/copilotapi.h, src/plugins/codegeex/copilot.cpp
leads to long-term unresponsiveness
Log: as title
Bug: https://pms.uniontech.com/bug-view-298309.html
=> fix: [AI] Code review functionality not working

src/plugins/find/gui/advancedsearchwidget.cpp, src/plugins/find/maincontroller/worker/searchreplaceworker.cpp, src/plugins/find/maincontroller/worker/searchreplaceworker_p.h
This commit addresses a bug where the search functionality would not
work when the editor content was empty. The following changes were made:
- Changed the `channelData` type to `std::optional<QString>` to
handle cases where there may not be any data to send.
These changes ensure that the search operation can gracefully handle
empty input, improving the overall robustness of the search feature.
Log: Fix search issue when editor content is empty
Bug: https://pms.uniontech.com/bug-view-298499.html
=> fix: [search functionality] Resolve issue with empty editor content

src/plugins/codegeex/widgets/inputeditwidget.cpp
1.reference dialog can not hide normally
2.Optimize the display and hiding of the `@` symbol
Log: fix bugs
Bug: https://pms.uniontech.com/bug-view-298457.html
https://pms.uniontech.com/bug-view-298349.html
=> fix: [Ai] issues of input-edit-widget

src/plugins/codeeditor/gui/tabbar.cpp, src/plugins/find/maincontroller/worker/searchreplaceworker_p.h
Log:
Change-Id: I42f7a848456c40b0952b98ecc93fa21310c4ff96
=> fix: build faild

src/plugins/core/session/sessiondialog.cpp, src/plugins/core/session/sessiondialog.h, src/plugins/core/session/sessionlistview.cpp, src/plugins/recent/mainframe/sessionitemwidget.cpp, src/plugins/recent/mainframe/sessionitemwidget.h
as title
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-299557.html
Bug: https://pms.uniontech.com/bug-view-299555.html
Bug: https://pms.uniontech.com/bug-view-299391.html
=> fix: [session] Issues of session name

src/plugins/cxx/cmake/builder/parser/cmakeparser.cpp, src/plugins/cxx/cmake/builder/parser/cmakeparser.h
=> fix: [cmake] incomplete path of cmake error

src/plugins/template/wizard/detailwidget.cpp, src/plugins/template/wizard/detailwidget.h, src/plugins/template/wizard/maindialog.cpp
Log: as title
Bug: https://pms.uniontech.com/bug-view-285081.html
=> fix: [template] optimized ui of "create new project/file" dialog

src/plugins/binarytools/mainframe/binarytoolsconfigview.cpp, src/plugins/binarytools/mainframe/binarytoolsdialog.cpp, src/plugins/binarytools/models/toolitemdelegate.cpp, src/plugins/binarytools/models/toolitemdelegate.h, src/plugins/binarytools/widgets/iconcombobox.cpp, src/plugins/binarytools/widgets/iconcombobox.h, src/plugins/builder/mainframe/settingdialog.cpp, src/plugins/smartut/common/projectitemdelegate.cpp, src/plugins/smartut/gui/widget/promptsettingwidget.cpp, src/plugins/smartut/gui/widget/resourcesettingwidget.cpp
as title
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-272447.html
=> fix: [binarytool] Optimize the display

src/plugins/aimanager/option/detailwidget.cpp, src/plugins/aimanager/option/modelconfigdialog.cpp, src/plugins/aimanager/option/modelconfigdialog.h
Log:
Change-Id: I24bb03cb56340e128d9e6ef5b415434807533229
=> feat: add model change feature

.gitignore, src/plugins/python/installer/pipinstaller.cpp, src/plugins/python/installer/pipinstaller.h
- Implemented a method to check if pip is installed before attempting to install packages. If pip is not found, the installer will now install python3-pip first and then proceed with the package installation.
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-316965.html
=> fix: add pip existence check before installation

src/common/lsp/client/client.cpp, src/common/lsp/client/client.h, src/common/lsp/client/private/client_p.h, src/plugins/codeeditor/lsp/languageclienthandler.cpp, src/plugins/codeeditor/lsp/lspclientmanager.cpp
- Updated the LSP client to include a validity check for the client before performing actions.
- Added a new method `isValid()` to the `Client` class to return the validity status.
- Modified the `selectLspServer` method to check if the client is valid before proceeding.
- Updated the context menu actions in `LanguageClientHandler` to enable or disable based on the client's validity.
- Introduced a new member variable `isClientValid` in `ClientPrivate` to track the client's state.
Log: This change improves the robustness of the LSP client interactions by ensuring actions are only available when the client is in a valid state.
Bug: https://pms.uniontech.com/bug-view-319109.html
=> fix: enhance LSP client validation and menu actions
