linuxdeepin/deepin-unioncode

- README.md
- README.zh_CN.md
correct build step
Log: correct README.md
> doc: complete README file

- .reuse/dep5
- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
- src/common/dialog/contextdialog.cpp
- src/common/dialog/contextdialog.h
- src/framework/lifecycle/pluginview.cpp
- src/plugins/binarytools/mainframe/binarytoolsdialog.cpp
- src/plugins/binarytools/mainframe/environmentview.cpp
- src/plugins/core/mainframe/plugindialog.cpp
- src/plugins/core/mainframe/plugindialog.h
- src/plugins/cxx/cmake/project/mainframe/properties/buildpropertywidget.cpp
- src/plugins/cxx/cmake/project/mainframe/properties/environmentwidget.cpp
- src/plugins/java/gradle/option/gradlewidget.cpp
- src/plugins/option/optioncore/mainframe/environmentwidget.cpp
- src/plugins/option/optioncore/mainframe/optiongeneralgenerator.h
- src/plugins/reversedebug/eventfilterdialog.cpp
- src/plugins/reversedebug/loadcoredialog.cpp
1. complete translations
2. fixed dialog box
log: bug fix
> fix: UI bugs

- src/tools/debugadapter/dapsession.cpp
- src/tools/debugadapter/debugger/gdbmi/gdbdebugger.cpp
- src/tools/debugadapter/debugger/gdbmi/gdbdebugger.h
- src/tools/debugadapter/debugmanager.cpp
1.supplement missing debugging printing information 2.delete excess debugging information
log: bug fix
> fix: debug mode printing information

- README.en.md
- README.md
Log: readme changed
Change-Id: I2b0a9c6c975f3b8bde25ea642efec0e687e6427a
> doc: add description in readme

- .reuse/dep5
- src/plugins/cxx/cmake/option/kitsmanagerwidget.cpp
1.move CMake kits option configuration window position
log: toolchain interface changed
> feat: refactoring toolchain interface

- README.en.md
- README.md
Log: readme changed
Change-Id: Ie4f075bfaef7561bb7534ad71a093f20118618fa
> doc: add developed app in readme

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
- src/framework/lifecycle/pluginview.cpp
- src/framework/lifecycle/pluginview.h
- src/plugins/core/mainframe/plugindialog.cpp
- src/plugins/core/mainframe/plugindialog.h
- src/plugins/core/mainframe/windowkeeper.cpp
1. merge the plugin management interface and plugin details interface
log: plugin manager view changed
> feat: modify the plugin manager view

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
- src/plugins/binarytools/mainframe/binarytoolsconfigview.cpp
- src/plugins/option/optioncore/mainframe/profilesettingwidget.cpp
1. translate the binary tools dialog box buttons
2. translate the translation dialog box buttons
log: compelete translation
> fix: translation of dialog box buttons

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
- debian/changelog
- src/common/dialog/contextdialog.cpp
- src/common/dialog/contextdialog.h
- src/plugins/binarytools/mainframe/binarytoolsconfigview.cpp
- src/plugins/template/wizard/detailwidget.cpp
1. add question dialog
log: complete common library
> feat: complete dialog box common library

- debian/changelog
- src/plugins/cxx/cmake/project/mainframe/properties/configutil.cpp
Log: bug fix
Change-Id: I6895d460e3555f5403142f8355c4664ce1f461b1
> fix: repeat project when view project info

- README.en.md
- README.md
1. modify spelling errors
2. add gitee link
log:
> doc: modify readme doc

- src/plugins/core/mainframe/plugindialog.cpp
- src/plugins/core/mainframe/plugindialog.h
description: Changed the original label name to a more descriptive name to improve code readability.
> feat: added more descriptive label naming

- 3rdparty/cppdap/include/dap/any.h
- 3rdparty/cppdap/src/io.cpp
- 3rdparty/unioncode-jsonrpccpp/libjson-rpc-cpp/src/jsonrpccpp/common/jsonparser.h
- src/tools/eventrecorder/CMakeLists.txt
- src/tools/eventrecorder/include/elf/data.hh
- src/tools/eventrecorder/preload/vdsopreload.c
- https://github.com/google/cppdap/pull/109/files
- https://github.com/google/cppdap/commit/5f49573daf3922658be9ab8f571e117a7405bbf1
> fix: build failed due to header missing & config error

- debian/control
remove libcurl-dev in control
Log: control changed
Change-Id: I508050d80ad5a7e466ed921d9f78f02c3e1e5269
> fix: remove unused depend

- debian/rules
remove unused parameters in rules file
Log: rules changed
Change-Id: Ibcf082326d7fb943072c519661c0725dc21f3163
> fix: package deb error

- debian/rules
rewrite rules to avoid failed
Log: rules changed
Change-Id: I8d2939ff4f70e5d8e17c761275487690871ad45d
> fix: package failed

- README.en.md
- README.md
Log: readme changed
Change-Id: I06148b65a49af706486e8a7380a39c0d4fc510bb
> doc: update depends in readme

- src/scripts/CMakeLists.txt
Log:
Change-Id: Ibe7c83d5d3496036db1562ebcb6564fc6f74ceb8
> fix: remove unused install path

- src/common/inotify/private/inotify_linux.h
Log: bug fix
Change-Id: Ic562bced6ae27d7eb728dcbb7eca21deaeeabb9e
> fix: faild create fd caused crash

- 3rdparty/unioncode-jsonrpccpp/libjson-rpc-cpp/src/jsonrpccpp/common/jsonparser.h
- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
- debian/changelog
- src/plugins/core/mainframe/aboutdialog.cpp
- src/plugins/core/mainframe/aboutdialog.h
Log:
Change-Id: I152ef9c78846f87a13f887a2dfa2ed0b28ca2a6a
> feat: add description in about dialog

- src/plugins/core/mainframe/aboutdialog.cpp
Log:
Change-Id: Ic5a214e58c20b82a990d24ed4ece7dc200755648
> feat: change about dialog link

- src/plugins/core/mainframe/aboutdialog.cpp
- src/plugins/core/mainframe/aboutdialog.h
Log:
Change-Id: I35b28c42579733d69ad948a16bd661e5cad94713
> feat: show expand pane in about dialog

- debian/deepin/OWNERS
use /lgtm /approve give +1 and +2 like gerrit,but only approver  can use /approve +2, other people use /approve is +1.
log:
> feat: Add OWNERS file for approve and review

- src/plugins/actionanalyse/actionanalyseplugin.json
- src/plugins/binarytools/binarytools.json
- src/plugins/builder/buildercore.json
- src/plugins/codeeditor/codeeditor.json
- src/plugins/codeporting/codeporting.json
- src/plugins/collaborators/collaborators.json
- src/plugins/commandproxy/commandproxy.json
- src/plugins/console/console.json
- src/plugins/container/container.json
- src/plugins/core/core.json
- src/plugins/cxx/cxxplugin.json
- src/plugins/debugger/debugger.json
- src/plugins/filebrowser/filebrowser.json
- src/plugins/find/findplugin.json
- src/plugins/java/javaplugin.json
- src/plugins/javascript/javascriptplugin.json
- src/plugins/option/optioncore/optioncore.json
- src/plugins/option/optionlsp/optionlsp.json
- src/plugins/performance/performance.json
- src/plugins/project/projectcore.json
- src/plugins/python/pythonplugin.json
- src/plugins/recent/recent.json
- src/plugins/reversedebug/reversedebug.json
- src/plugins/symbol/symbol.json
- src/plugins/template/templateplugin.json
- src/plugins/valgrind/valgrind.json
Log:
Change-Id: I225b9a8ca530ae8f577c6dd79effccba9ad2cf38
> refactor: simplify plugin properties

- src/framework/event/event.h
Log:
Bug: https://github.com/linuxdeepin/developer-center/issues/5826 Change-Id: Ia78f60daa59ba9cb5554f9eb1304a4c64a8e0e2c
> fix: crashed when launch in arch linux

- src/plugins/cxx/cmake/project/mainframe/cmakeasynparse.cpp
Log:
Change-Id: I5c720c66aa84dee338e3c5cfd91435a1c02d1761
> fix: remove no need log

- debian/changelog
Log:
Change-Id: Iec66a469bfad9c8c4baa443ceb97026e593b5479
> feat: update changelog to 1.1.20

- 3rdparty/unioncode-scintilla515/scintilla/qt/ScintillaEditBase/PlatQt.cpp
- src/common/util/eventdefinitions.h
- src/plugins/codeeditor/codeeditor.cpp
- src/plugins/codeeditor/mainframe/naveditmainwindow.cpp
- src/plugins/codeeditor/mainframe/texteditkeeper.cpp
- src/plugins/codeeditor/mainframe/texteditkeeper.h
- src/plugins/codeeditor/textedittabwidget/scintillaeditextern.cpp
- src/plugins/codeeditor/textedittabwidget/scintillaeditextern.h
- src/plugins/codeeditor/textedittabwidget/style/stylelsp.cpp
- src/plugins/codeeditor/textedittabwidget/textedit.cpp
- src/plugins/codeeditor/textedittabwidget/texteditsplitter.cpp
- src/plugins/codeeditor/textedittabwidget/texteditsplitter.h
- src/plugins/codeeditor/textedittabwidget/textedittabbar.cpp
- src/plugins/codeeditor/textedittabwidget/textedittabwidget.h
- src/plugins/codegeex/CMakeLists.txt
- src/plugins/codegeex/askpage/askpage.cpp
- src/plugins/codegeex/codegeex.cpp
- src/plugins/codegeex/codegeex/askapi.cpp
- src/plugins/codegeex/codegeex/copilotapi.cpp
- src/plugins/codegeex/codegeex/copilotapi.h
- src/plugins/codegeex/copilot.cpp
- src/plugins/codegeex/copilot.h
- src/plugins/codegeex/eventreceiver.cpp
- src/services/CMakeLists.txt
- src/services/editor/editorservice.h
with comment&generate feature
Log:
Change-Id: I2024bc8eaa6764f025b3a4dee1f20621b2aca349
> feat: add code copilot

- src/plugins/codegeex/askpage/askpage.cpp
- src/plugins/codegeex/codegeex/askapi.cpp
- src/plugins/codegeex/codegeex/askapi.h
could add session、delete session、query history
Log: new session features
Change-Id: Ib63786b70ad4935fa0c3a35de2ff215a0b1009b3
> feat: add session features

- src/plugins/codegeex/CMakeLists.txt
- src/plugins/codegeex/askpage/askpage.cpp
- src/plugins/codegeex/codegeex.cpp
- src/plugins/codegeex/codegeex/askapi.cpp
- src/plugins/codegeex/codegeex/askapi.h
- src/plugins/codegeex/codegeexmanager.cpp
- src/plugins/codegeex/codegeexmanager.h
- src/plugins/codegeex/data/messagedata.cpp
- src/plugins/codegeex/data/messagedata.h
- src/plugins/codegeex/widgets/askpagewidget.cpp
- src/plugins/codegeex/widgets/askpagewidget.h
- src/plugins/codegeex/widgets/codeeditcomponent.cpp
- src/plugins/codegeex/widgets/codeeditcomponent.h
- src/plugins/codegeex/widgets/codegeexwidget.cpp
- src/plugins/codegeex/widgets/codegeexwidget.h
- src/plugins/codegeex/widgets/intropage.cpp
- src/plugins/codegeex/widgets/intropage.h
- src/plugins/codegeex/widgets/messagecomponent.cpp
- src/plugins/codegeex/widgets/messagecomponent.h
- src/plugins/codegeex/widgets/translationpagewidget.cpp
- src/plugins/codegeex/widgets/translationpagewidget.h
add widgets of CodeGeeX plugin
Log: Add CodeGeeX UI
> feat: [CodeGeeX]Widgets of CodeGeeX

- src/plugins/core/mainframe/windowkeeper.cpp
- src/plugins/core/mainframe/windowkeeper.h
- src/plugins/template/CMakeLists.txt
- src/plugins/template/templatemanager.cpp
- src/plugins/template/wizard/detailwidget.cpp
- src/plugins/template/wizard/detailwidget.h
- src/plugins/template/wizard/maindialog.cpp
- src/plugins/template/wizard/maindialog.h
DTK Change-Mainwindow and menu
> feat: DTK Change-Mainwindow and menu

- src/common/CMakeLists.txt
- src/common/lsp/client/client.cpp
- src/common/unilog.h
- src/plugins/codegeex/codegeexmanager.cpp
- src/plugins/codegeex/copilot.cpp
- src/plugins/codegeex/widgets/codegeexwidget.cpp
- src/plugins/codegeex/widgets/codegeexwidget.h
- src/plugins/cxx/cxxplugin.cpp
Log: login ui changed
Change-Id: I29b60f367aaa68f66f9fc4f4c4ed6c70546e4c36
> chore: login ui optimization

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
- src/plugins/codegeex/widgets/askpagewidget.cpp
- src/plugins/codegeex/widgets/askpagewidget.h
Log:
Change-Id: Iee8b9bc8dd67ac58f3a597667d371dfb27d4f172
> chore: remove send button

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
- src/plugins/codeeditor/mainframe/naveditmainwindow.cpp
- src/plugins/codegeex/codegeexmanager.cpp
- src/plugins/codegeex/codegeexmanager.h
- src/plugins/codegeex/widgets/askpagewidget.cpp
- src/plugins/codegeex/widgets/askpagewidget.h
- src/plugins/codegeex/widgets/intropage.cpp
- src/plugins/codegeex/widgets/intropage.h
Log:
Change-Id: I4e7185538a56ae6664c28e2d3b74b25928f97130
> chore: add answering state tips

- src/common/widget/pagewidget.cpp
- src/common/widget/pagewidget.h
- src/plugins/codeeditor/CMakeLists.txt
- src/plugins/codeeditor/mainframe/naveditmainwindow.cpp
- src/plugins/codegeex/CMakeLists.txt
- src/plugins/codegeex/askpage/askpage.cpp
- src/plugins/codegeex/askpage/askpage.h
- src/plugins/codegeex/option/codegeexoptionwidget.cpp
- src/plugins/codegeex/option/detailwidget.cpp
- src/plugins/codegeex/option/optioncodegeexgenerator.cpp
- src/plugins/codegeex/widgets/askpagewidget.cpp
- src/plugins/codegeex/widgets/askpagewidget.h
- src/plugins/codegeex/widgets/codeeditcomponent.cpp
- src/plugins/codegeex/widgets/codeeditcomponent.h
- src/plugins/codegeex/widgets/codegeexwidget.cpp
- src/plugins/codegeex/widgets/codegeexwidget.h
- src/plugins/codegeex/widgets/intropage.cpp
- src/plugins/codegeex/widgets/intropage.h
- src/plugins/codegeex/widgets/messagecomponent.cpp
- src/plugins/codegeex/widgets/messagecomponent.h
- src/plugins/codegeex/widgets/translationpagewidget.cpp
- src/plugins/codegeex/widgets/translationpagewidget.h
DRK-Changed-CodeGeex plugin window
> feat: DTK-Changed-CodeGeex plugin window

- src/plugins/codegeex/codegeexmanager.cpp
- src/plugins/codegeex/codegeexmanager.h
- src/plugins/codegeex/widgets/codegeexwidget.cpp
- src/plugins/codegeex/widgets/codegeexwidget.h
- src/plugins/codegeex/widgets/translationpagewidget.cpp
- src/plugins/codegeex/widgets/translationpagewidget.h
> feat: add translate

- src/plugins/codeeditor/textedittabwidget/textedit.cpp
- src/plugins/codeeditor/transceiver/codeeditorreceiver.cpp
- src/plugins/codegeex/copilot.cpp
- src/plugins/codegeex/copilot.h
- src/plugins/codegeex/widgets/askpagewidget.cpp
- src/services/editor/editorservice.h
use key event to trigger request and reduce delay time
Log:
Change-Id: I1a4133cb6fb2d205e51c6aa42f45cff0e7065644
> chore: optimize code generation

- src/plugins/codegeex/widgets/askpagewidget.cpp
Log: bug fix
Change-Id: I3b9532074a47b736df7be7e79ed5626b8dff364d
> fix: ask page can't scroll to bottom

- src/plugins/codegeex/codegeexmanager.cpp
- src/plugins/codegeex/codegeexmanager.h
- src/plugins/codegeex/data/messagedata.cpp
- src/plugins/codegeex/widgets/codegeexwidget.cpp
- src/plugins/codegeex/widgets/codegeexwidget.h
> fix: set delete button disable while ai anwsering.

- src/plugins/codeeditor/mainframe/naveditmainwindow.cpp
- src/plugins/option/optioncore/optioncore.cpp
Remove the option button of top toolbar and thie titlebar of edit mainwindow.
> feat: Remove the option button of top toolbar

- src/base/abstractconsole.cpp
- src/base/abstractdebugger.h
- src/base/abstractmainwindow.cpp
- src/base/abstractmenu.cpp
- src/base/abstractmenubar.cpp
- src/base/abstractnav.cpp
- src/base/abstractoutputpane.h
- src/base/abstractwidget.cpp
> feat: DTK Changed-base

- src/plugins/codeeditor/codeeditor.cpp
- src/plugins/codeeditor/mainframe/naveditmainwindow.cpp
- src/plugins/codeeditor/mainframe/naveditmainwindow.h
- src/plugins/codeeditor/transceiver/codeeditorreceiver.cpp
- src/plugins/collaborators/collaborators.cpp
- src/plugins/core/core.qrc
- src/plugins/core/mainframe/aboutdialog.cpp
- src/plugins/core/mainframe/plugindialog.cpp
- src/plugins/core/mainframe/windowkeeper.cpp
- src/plugins/core/mainframe/windowkeeper.h
- src/plugins/template/wizard/maindialog.cpp
- src/services/window/windowelement.h
- src/services/window/windowservice.h
DTK Changed-ToolBar and fix some bugs.
> feat: DTK Changed-ToolBar and fix some bugs

- src/plugins/filebrowser/filebrowser.cpp
- src/plugins/filebrowser/mainframe/treeview.cpp
- src/plugins/filebrowser/mainframe/treeview.h
DTK-changed filebrowser plugin
> feat: DTK-changed filebrowser plugin

- src/plugins/java/gradle/option/gradleoptionwidget.cpp
- src/plugins/java/gradle/option/gradlewidget.cpp
- src/plugins/java/java/option/javaoptionwidget.cpp
- src/plugins/java/java/option/jdkwidget.cpp
- src/plugins/java/maven/option/mavenoptionwidget.cpp
- src/plugins/java/maven/option/mavenwidget.cpp
include maven/gradle/java optionWidget
> feat: DTK-Changed javaPlugin

- src/plugins/java/gradle/project/properties/gradleconfigpropertywidget.cpp
- src/plugins/java/gradle/project/properties/gradleconfigpropertywidget.h
- src/plugins/java/maven/project/properties/mavenconfigpropertywidget.cpp
- src/plugins/java/maven/project/properties/mavenconfigpropertywidget.h
DTK-Changed java-propertyWidget
> feat: DTK-Changed java-propertyWidget

- src/plugins/console/consolewidget.cpp
- src/plugins/console/consolewidget.h
Dtk-changed and consoleWidget backgroundColor changes with system theme
> feat: DTK-changed consolewidget

- src/plugins/actionanalyse/actionanalyseplugin.cpp
- src/plugins/actionanalyse/mainframe/analysekeeper.cpp
> feat:Remove useless header files-actionanalyse plugin

- src/common/dialog/contextdialog.cpp
- src/common/dialog/contextdialog.h
- src/common/dialog/pip3dialog.cpp
- src/common/dialog/pip3dialog.h
- src/common/dialog/processdialog.cpp
- src/common/dialog/processdialog.h
- src/common/dialog/propertiesdialog.cpp
- src/common/dialog/propertiesdialog.h
- src/common/dialog/wgetdialog.cpp
- src/common/dialog/wgetdialog.h
- src/common/widget/collapsewidget.cpp
- src/common/widget/collapsewidget.h
- src/common/widget/configurewidget.cpp
- src/common/widget/configurewidget.h
- src/common/widget/hotkeylineedit.cpp
- src/common/widget/hotkeylineedit.h
- src/common/widget/outputpane.cpp
- src/common/widget/outputpane.h
- src/common/widget/singlechoicebox.cpp
- src/common/widget/singlechoicebox.h
- src/common/widget/statuswidget.cpp
- src/common/widget/statuswidget.h
- src/plugins/codeporting/configwidget.cpp
- src/plugins/codeporting/configwidget.h
- src/plugins/codeporting/reportpane.cpp
- src/plugins/codeporting/reportpane.h
DTK Changed-Common and codeporting plugin
> feat: DTK Changed-Common and codeporting plugin

- src/plugins/reversedebug/eventfilterdialog.cpp
- src/plugins/reversedebug/eventfilterdialog.h
- src/plugins/reversedebug/loadcoredialog.cpp
- src/plugins/reversedebug/loadcoredialog.h
- src/plugins/reversedebug/reversedebugplugin.cpp
- src/plugins/reversedebug/taskwindow.cpp
- src/plugins/reversedebug/timelinewidget.cpp
- src/plugins/reversedebug/timelinewidget.h
DTK-Changed reversedebugplugin
> feat: DTK-Changed reversedebugplugin

- src/plugins/codeeditor/textedittabwidget/textedittabwidget.cpp
Edit widget show black line when it get focus.
> fix: Rmove the black line of edit widget

- src/plugins/javascript/project/properties/configpropertywidget.cpp
- src/plugins/javascript/project/properties/configpropertywidget.h
> feat: DTK-Changed javascript-plugin

- src/plugins/binarytools/mainframe/binarytoolsconfigview.cpp
- src/plugins/binarytools/mainframe/binarytoolsdialog.cpp
- src/plugins/binarytools/mainframe/environmentview.cpp
DTK-Changed binarytools-plugin
> feat: DTK-Changed binarytools-plugin

- debian/deepin/OWNERS
github team需要添加linuxdeepin/才能找到
log:
> chore: Update OWNERS by approve

- src/app/main.cpp
- src/framework/lifecycle/private/pluginmanager_p.cpp
- src/plugins/option/optioncore/optioncore.cpp
delete app quit setting in main.cpp
Log: bug fix
Change-Id: I53053fc5eef052f45e582b9da03aa4792822c954
> fix: app quit failed

- src/plugins/codegeex/codegeex.cpp
Log:
Change-Id: Icbb563320017e34e979ad0aea9b431f132661a5b
> chore: remove codegeex option widget

- src/plugins/python/python/option/interperterwidget.cpp
- src/plugins/python/python/option/pythonoptionwidget.cpp
> feat: python-plugin UI modification

- src/plugins/codeeditor/codeeditor.cpp
- src/plugins/codeeditor/mainframe/naveditmainwindow.cpp
- src/plugins/codeeditor/mainframe/naveditmainwindow.h
- src/plugins/codeporting/codeportingmanager.cpp
- src/plugins/codeporting/codeportingplugin.cpp
- src/services/window/windowservice.h
Log:
Change-Id: I2393e9805597c5fec52b26e391f846ff44c53241
> refactor: hide codeporting ui when no used

- src/plugins/core/mainframe/windowkeeper.cpp
Log:
Change-Id: I129cd1f8249d29290f4ca42d2247e8f6d4a9a64a
> feat: add status bar

- src/plugins/option/optioncore/CMakeLists.txt
- src/plugins/option/optioncore/mainframe/environmentwidget.cpp
- src/plugins/option/optioncore/mainframe/navigationdelegate.cpp
- src/plugins/option/optioncore/mainframe/navigationdelegate.h
- src/plugins/option/optioncore/mainframe/optionsdialog.cpp
- src/plugins/option/optioncore/mainframe/optionsdialog.h
- src/plugins/option/optioncore/mainframe/shortcutsettingwidget.cpp
- src/plugins/option/optioncore/optioncore.cpp
> feat: DTK-changed options plugin

- src/plugins/builder/mainframe/problemoutputpane.cpp
- src/plugins/builder/mainframe/problemoutputpane.h
- src/plugins/builder/tasks/taskdelegate.cpp
- src/plugins/builder/tasks/taskdelegate.h
- src/plugins/builder/tasks/taskmanager.cpp
- src/plugins/builder/tasks/taskmanager.h
- src/plugins/builder/tasks/taskview.cpp
- src/plugins/builder/tasks/taskview.h
> feat: DTK Changed-Builder plugin

- src/common/widget/configurewidget.cpp
- src/plugins/cxx/cmake/project/mainframe/properties/buildpropertywidget.cpp
- src/plugins/cxx/cmake/project/mainframe/properties/configpropertywidget.cpp
- src/plugins/cxx/cmake/project/mainframe/properties/environmentwidget.cpp
- src/plugins/cxx/cmake/project/mainframe/properties/runconfigpane.cpp
- src/plugins/cxx/cmake/project/mainframe/properties/runpropertywidget.cpp
- src/plugins/cxx/cmake/project/mainframe/properties/stepspane.cpp
1.modify parent class - configurewidget which used by cxx-plugin 
2.modify cxx-plugin
3.modify config-dialog Ui when open Cmake project
> feat: modify Project-Properties Ui of cxx-plugin and config-dialog when open cmake project

- src/plugins/builder/mainframe/buildmanager.cpp
- src/plugins/codeeditor/codeeditor.cpp
- src/plugins/codeeditor/mainframe/naveditmainwindow.cpp
- src/plugins/codeeditor/mainframe/naveditmainwindow.h
- src/plugins/core/mainframe/windowkeeper.cpp
- src/plugins/core/mainframe/windowkeeper.h
- src/plugins/debugger/interface/menumanager.cpp
- src/plugins/debugger/runner/runner.cpp
- src/plugins/find/findplugin.cpp
- src/plugins/find/findplugin.json
- src/services/window/windowservice.h
The interface of add Top toolbar move to core plugin)[refactor: The interface of add Top toolbar move to core plugin, and add find toolbar.
> refactor: The interface of add Top toolbar move to core plugin

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
- src/plugins/codegeex/widgets/askpagewidget.cpp
- src/plugins/codegeex/widgets/askpagewidget.h
- src/plugins/codegeex/widgets/codegeexwidget.cpp
- src/plugins/codegeex/widgets/codegeexwidget.h
- src/plugins/codegeex/widgets/historylistwidget.cpp
- src/plugins/codegeex/widgets/sessionrecorditem.cpp
- src/plugins/codegeex/widgets/sessionrecorditem.h
- src/plugins/codegeex/widgets/translationpagewidget.cpp
> chore: [codegeex]ui update

- src/framework/lifecycle/pluginview.cpp
- src/plugins/option/optioncore/CMakeLists.txt
- src/plugins/option/optioncore/icons/options_alert_16px.svg
- src/plugins/option/optioncore/mainframe/environmentwidget.cpp
- src/plugins/option/optioncore/mainframe/pluginwidget.cpp
- src/plugins/option/optioncore/mainframe/pluginwidget.h
- src/plugins/option/optioncore/optioncore.cpp
- src/plugins/option/optioncore/optioncore.qrc
add "installed plugins" to options-plugin
> feat: add "installed plugins" to options-plugin

- src/configures/editorstyle_cpp.support
- src/plugins/codeeditor/textedittabwidget/language/cpp/stylelspcpp.cpp
- src/plugins/codeeditor/textedittabwidget/language/cpp/stylescicpp.cpp
- src/plugins/codeeditor/textedittabwidget/language/cpp/stylescicpp.h
- src/plugins/codeeditor/textedittabwidget/language/cpp/texteditcpp.cpp
- src/plugins/codeeditor/textedittabwidget/scintillaeditextern.cpp
- src/plugins/codeeditor/textedittabwidget/scintillaeditextern.h
- src/plugins/codeeditor/textedittabwidget/style/stylejsonfile.h
- src/plugins/codeeditor/textedittabwidget/style/stylesci.cpp
- src/plugins/codeeditor/textedittabwidget/style/stylesci.h
- src/plugins/codegeex/codegeexmanager.cpp
Log:
Change-Id: I9a445d97e0a9e9d77751ce82171a0c4b73f8d2bc
> feat: make editor have two theme

- src/plugins/performance/mainframe/jsondisplaymodel.cpp
- src/plugins/performance/mainframe/jsondisplayview.cpp
- src/plugins/performance/mainframe/jsontabwidget.cpp
- src/plugins/performance/mainframe/mainwindow.cpp
- src/plugins/performance/mainframe/perfrecorddisplay.cpp
- src/plugins/performance/performance.cpp
- src/plugins/valgrind/mainframe/valgrindbar.cpp
- src/plugins/valgrind/mainframe/xmlstreamreader.cpp
DTK control replacement for performance and valgrind plugins
> feat: DTK control replacement for performance and valgrind plugins

- src/plugins/codeeditor/textedittabwidget/style/stylelsp.cpp
- src/plugins/core/mainframe/windowkeeper.cpp
Log:
Change-Id: I84d39dd9d16e70295d3f06c9b17db3f3307e5ace
> fix: remove unused icons

- src/plugins/option/optioncore/mainframe/shortcutsettingwidget.cpp
- src/plugins/option/optioncore/mainframe/shortcutsettingwidget.h
modify shortcutsettingwidget ui
> feat: modify shortcutsettingwidget ui

- src/plugins/cxx/cmake/project/mainframe/properties/buildpropertywidget.cpp
- src/plugins/cxx/cmake/project/mainframe/properties/environmentwidget.cpp
- src/plugins/option/optioncore/mainframe/profilesettingwidget.cpp
- src/plugins/python/python/option/interperterwidget.cpp
> feat: modify ui of Options-plugin

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
> feat: update translations

- src/plugins/codeeditor/mainframe/naveditmainwindow.cpp
- src/plugins/codeeditor/mainframe/naveditmainwindow.h
- src/plugins/codeporting/codeportingwidget.cpp
- src/services/window/windowservice.h
Fix object type transform error.
> fix: [codeeditor] Object type tranform error

- debian/changelog
Log:
Change-Id: I914e227910b9c2e0ff4084b622a777d6a6dbffdc
> tag: update tag to 1.2.0

- src/plugins/option/optioncore/mainframe/optionsdialog.cpp
- src/plugins/template/wizard/detailwidget.cpp
> feat: template-plugins ui update

- src/common/widget/outputpane.cpp
- src/common/widget/outputpane.h
- src/plugins/codeeditor/mainframe/naveditmainwindow.cpp
- src/plugins/codeeditor/mainframe/naveditmainwindow.h
- src/plugins/codeporting/codeportingmanager.cpp
- src/plugins/codeporting/codeportingmanager.h
- src/plugins/codeporting/codeportingwidget.cpp
- src/plugins/codeporting/codeportingwidget.h
- src/plugins/codeporting/reportpane.cpp
- src/plugins/codeporting/reportpane.h
- src/plugins/debugger/interface/stackframeview.cpp
- src/plugins/filebrowser/filebrowser.cpp
- src/plugins/filebrowser/mainframe/treeview.cpp
- src/plugins/project/mainframe/projecttree.cpp
- src/plugins/symbol/mainframe/symboltreeview.cpp
> feat: DTK Changed-Code porting

- src/plugins/codegeex/widgets/codeeditcomponent.cpp
- src/plugins/codegeex/widgets/messagecomponent.cpp
- src/plugins/codegeex/widgets/messagecomponent.h
update backGround code of ask/anwser Widget
> feat: update backGround code of ask/anwser Widget

- 3rdparty/unioncode-scintilla515/scintilla/qt/ScintillaEditBase/ScintillaEditBase.h
- src/plugins/codeeditor/mainframe/texteditkeeper.cpp
- src/plugins/codegeex/codegeex/copilotapi.cpp
showtips when edit closed will cause crashed
Log: bug fix
Change-Id: I8f69fbe38a52812394b0aa91b56cba43d91f1428
> fix: crashed when edit closed

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
- src/app/main.cpp
- src/plugins/find/findplugin.cpp
> fix: loss of translations

- src/plugins/codegeex/widgets/askpagewidget.cpp
- src/plugins/codegeex/widgets/codeeditcomponent.cpp
- src/plugins/cxx/cmake/option/kitsmanagerwidget.cpp
- src/plugins/option/optioncore/mainframe/optionsdialog.cpp
- src/plugins/option/optioncore/mainframe/shortcutsettingwidget.cpp
modify constrct code of QLayout to avoid Warning log
> style: modify constrct code of QLayout

- src/plugins/codegeex/codegeexmanager.cpp
- src/plugins/codegeex/widgets/askpagewidget.cpp
- src/plugins/codegeex/widgets/askpagewidget.h
- src/plugins/codegeex/widgets/messagecomponent.cpp
- src/plugins/codegeex/widgets/messagecomponent.h
> feat: update ui of codegeex

- src/plugins/codegeex/widgets/askpagewidget.cpp
- src/plugins/option/optioncore/mainframe/profilesettingwidget.cpp
use DDialog to replace messageBox
1.after change language   2.delete codegeex session
> feat: update ui of messageBox

- src/plugins/codegeex/codegeex/askapi.cpp
- src/plugins/codegeex/codegeex/askapi.h
- src/plugins/codegeex/codegeexmanager.cpp
- src/plugins/codegeex/codegeexmanager.h
- src/plugins/codegeex/widgets/askpagewidget.cpp
- src/plugins/codegeex/widgets/codegeexwidget.cpp
- src/plugins/codegeex/widgets/codegeexwidget.h
only functionals code, Later add button
> feat: add logOut code

- src/plugins/core/mainframe/aboutdialog.cpp
> feat: about window icon update

- src/common/inotify/private/inotify_linux.h
crashed when close project and open project operation at the same time
Log: bug fix
Change-Id: I1fd2bf2d6b847dd7769b7550dc9e68ed8a63ddb0
> fix: crashed when close project

- src/plugins/codegeex/CMakeLists.txt
- src/plugins/codegeex/widgets/codeeditcomponent.cpp
- src/plugins/codegeex/widgets/codeeditcomponent.h
Add "Syntax Highlighting" of codegeex translation Page ver.1
> feat: Add "Syntax Highlighting" of codegeex translation Page

- src/plugins/codegeex/widgets/askpagewidget.cpp
- src/plugins/codegeex/widgets/intropage.cpp
- src/plugins/codegeex/widgets/intropage.h
> feat: add "logout" button

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
> feat: Translation Updates

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
Log:
Change-Id: I94d23a85e9795b5e22f74d8f8c42936f9538b67f
> chore: update translation

- debian/changelog
Log:
Change-Id: I93ea8b50476b68a5b27f940909e17896a8a41f93
> tag: update to 1.2.1

- src/plugins/binarytools/mainframe/binarytoolsconfigview.cpp
> feat: find plugin ui update

- src/plugins/core/mainframe/windowkeeper.cpp
Log:
Change-Id: Iece8c93a4287274359e1331bff81c8cf57ebed7d
> chore: change help link address

- src/plugins/codeeditor/textedittabwidget/style/stylesci.cpp
- src/plugins/codeeditor/textedittabwidget/textedit.cpp
- src/plugins/codeeditor/textedittabwidget/textedit.h
Log: bug fix
Change-Id: If2d3251484f7c1146df635cb396f4b2eb739e685
> fix: [editor] theme color incorrect

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
- src/plugins/cxx/cmake/project/mainframe/properties/buildpropertywidget.cpp
- src/plugins/cxx/cmake/project/mainframe/properties/stepspane.cpp
Translation not displayed issue
> feat: Translation not displayed issue

- debian/control
- src/plugins/codegeex/codegeex/copilotapi.cpp
- src/plugins/codegeex/codegeex/copilotapi.h
- src/plugins/codegeex/copilot.cpp
- src/plugins/codegeex/copilot.h
- src/plugins/codegeex/data/syntaxdefinitionname.h
- src/plugins/codegeex/widgets/codeeditcomponent.cpp
- src/plugins/codegeex/widgets/codeeditcomponent.h
- src/plugins/codegeex/widgets/messagecomponent.cpp
- src/plugins/codegeex/widgets/translationpagewidget.cpp
- src/plugins/codegeex/widgets/translationpagewidget.h
1."Code output in a Q&A scenario"
2."Code output for translated code"
> feat: Add highlighting for different languages in various operate.

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
- src/plugins/reversedebug/eventfilterdialog.cpp
reversedebug plugin translation update
> feat: reversedebug plugin translation update

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
> feat: Translation update

- debian/control
Log:
Change-Id: Iddac35cfb69d1492f2278a265a7e277314cb564c
> fix: wrong format in control

- CMakeLists.txt
- src/plugins/CMakeLists.txt
- src/tools/CMakeLists.txt
Log:
Change-Id: Ib9e7a7cdc0e76a3b9c92eeead225fa4196eb5810
> chore: compile condition changed

- src/plugins/codegeex/copilot.cpp
- src/plugins/codegeex/copilot.h
Log:
Change-Id: I23c64bf94e4a2546fb9c1f1ef381500e677725eb
> fix: code generation display issue

- debian/changelog
Log:
Change-Id: I806a509631f9065d67db8edf11d4facb88a9d232
> tag: update to 1.2.2

- src/plugins/codeeditor/mainframe/naveditmainwindow.cpp
- src/plugins/codeeditor/mainframe/naveditmainwindow.h
Adjusted minimus width of edit mainwindow resizing
> fix: [codeeditor] Adjusted minimum width of edit mainwindow resizing

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
- src/plugins/core/mainframe/windowkeeper.cpp
- src/plugins/core/mainframe/windowkeeper.h
add waiting logo when app loading
> feat: add waiting logo when app loading

- 3rdparty/unioncode-jsonrpccpp/libjson-rpc-cpp/cmake/FindThreads.cmake
Log:
Change-Id: Id59fa1a56fdb7a2623d1e7363663cff1e004c6c1
> chore: not link lthread in rpc lib

- src/plugins/builder/tasks/taskdelegate.cpp
Log:
Change-Id: I7cb9110898dec6cb6bbe3b35d3b613ee7917a613
> chore: include QPainterPath header

- debian/changelog
Log:
Change-Id: I33949066d4f3319b399d08e4e2fc34edf7984661
> tag: update to 1.2.3

- debian/control
- src/plugins/codegeex/copilot.cpp
- src/plugins/codegeex/option/detailwidget.cpp
Log:
Change-Id: Id789d1a02fa07604cc045ccad0db8f0b22c6034f
> fix: [codegeex] issues on clean environment

- src/plugins/cxx/cmake/project/mainframe/cmakeprojectgenerator.cpp
- src/plugins/project/mainframe/projecttree.cpp
Project property menu removed for not root item.
> fix: Project property menu removed for not root item

- src/plugins/valgrind/mainframe/valgrindbar.cpp
> feat: Valgrind Plugin UI updates

- README.en.md
- README.md
> feat: README.en Update

- src/common/dialog/propertiesdialog.cpp
- src/plugins/cxx/cmake/project/mainframe/properties/environmentwidget.cpp
> fix: Build and run parameter save

- src/plugins/codeeditor/transceiver/codeeditorreceiver.cpp
> fix: crash when opening a file

- src/plugins/codeeditor/transceiver/codeeditorreceiver.cpp
Reverts linuxdeepin/deepin-unioncode#226
> Revert "fix: crash when opening a file"

- src/plugins/codeeditor/codelens/codelensdelegate.cpp
- src/plugins/codeeditor/codelens/codelensdelegate.h
- src/plugins/codeeditor/codelens/codelenstree.cpp
code lens-optimize and highlight colors and child line spacing,设置的24行距来源于UI设计图
> feat: code lens-optimize and highlight colors and child line spacing

- src/plugins/find/findtoolwindow.cpp
- src/plugins/find/findtoolwindow.h
Invalid ase match button and character full match button
> fix: Invalid ase match button and character full match button

- src/plugins/template/wizard/maindialog.cpp
> feat: Templates plugins ui update

- src/plugins/python/python/option/interperterwidget.cpp
> feat: python plugin ui optimisation

- debian/changelog
> tag: update to 1.2.4

- src/plugins/builder/buildercore.cpp
- src/plugins/builder/mainframe/buildmanager.cpp
> fix: can`t switch to Build-tool with alt+D shortCut

- src/plugins/cxx/cmake/project/mainframe/properties/runconfigpane.cpp
- src/plugins/cxx/cmake/project/mainframe/properties/runconfigpane.h
- src/plugins/cxx/cmake/project/mainframe/properties/runpropertywidget.cpp
> fix: ui of propertiesDialog of cxx project

- src/common/supportfile/editorstyle.cpp
- src/common/supportfile/editorstyle.h
- src/plugins/codeeditor/textedittabwidget/style/stylejsonfile.cpp
config file not be updated after upgrade,
use global config file instead.
Log: bug fix
Change-Id: I1a8543199f04479791081a302f46c10816efa200
> fix: highlight not correct after upgrade

- src/plugins/builder/tasks/taskdelegate.cpp
- src/plugins/cxx/cmake/builder/parser/cmakeparser.cpp
> fix: Changed issus list UI

- src/plugins/find/findplugin.cpp
- src/plugins/find/findplugin.h
- src/plugins/find/findtoolbar.cpp
- src/plugins/find/findtoolbar.h
> feat: Find plugin to add focus

- src/plugins/cxx/cmake/project/mainframe/cmakeprojectgenerator.cpp
- src/plugins/cxx/cmake/project/transceiver/projectcmakereceiver.cpp
- src/plugins/project/mainframe/projecttree.cpp
- src/plugins/project/mainframe/projecttree.h
- src/plugins/project/projectcore.cpp
- src/services/project/projectservice.h
Log: bug fix
Change-Id: I8930002ce82121edc69902539f95f39e3f1dce41
> fix: repeat project item in project view

- src/plugins/codegeex/codegeex/askapi.cpp
Adapt to Codegeex specific model
> feat: Adapt to Codegeex specific model

- src/common/icons/ide.svg
> fix: lost of icon

- src/plugins/codeeditor/textedittabwidget/language/python/stylescipython.cpp
Log:
Change-Id: I9240e972c526df394dc92eb1c1ef93240470bcab
> chore: reset python light theme color

- src/plugins/core/mainframe/windowkeeper.cpp
- src/plugins/core/mainframe/windowkeeper.h
- src/plugins/cxx/cmake/project/mainframe/cmakeasynparse.cpp
> fix: Add ShortCut for menu

- debian/changelog
Log:
Change-Id: Iaafc766f1d693acfa8a018a68398d74833597183
> tag: update to 1.2.5

- assets/templates/projects/python/console/main.py
let it support chinese
Log:
Change-Id: I1515c05de5aea6aa505ed5ecd9b072c26d8131c3
> chore: optimize python template

- src/plugins/actionanalyse/mainframe/analysekeeper.cpp
- src/plugins/builder/transceiver/builderreceiver.cpp
Log:
Change-Id: I0a18c7394a26971bd448a9c39911e7226bc50bdf
> fix: pop error message dialog

- src/plugins/core/mainframe/windowkeeper.cpp
- src/plugins/cxx/cmake/project/transceiver/projectcmakereceiver.cpp
Some shortcuts reuse cause invalid.
> fix: Some shortcuts reuse cause invalid

- src/plugins/core/mainframe/windowkeeper.cpp
Modify the logic of adding options action.
> fix: Modify the logic of adding options action

- src/plugins/valgrind/mainframe/valgrindrunner.cpp
- src/services/window/windowelement.h
> fix: modify Action of valgrind

- debian/deepin-unioncode.install
> fix: can`t install icon to system

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
- src/plugins/codegeex/widgets/askpagewidget.cpp
- src/plugins/codegeex/widgets/codegeexwidget.cpp
> 添加codegeex界面按钮的tips信息

- src/plugins/project/mainframe/projecttree.cpp
Remove project tree menu, changed later.
> fix: Remove project tree menu

- src/plugins/builder/transceiver/builderreceiver.cpp
Log:
Change-Id: I796d0cc2d923e8c805100088da7352ac1913e016
> chore: remove symbol error ouput

- debian/changelog
Log:
Change-Id: I70d4ea8be08b05b4404793176c1fa6e1933ee247
> tag: update to 1.2.6

- debian/changelog
Log:
Change-Id: I3e08fa4b608b9d52897dc6b2522230a58ee52624
> tag: update to 1.2.7

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
- src/plugins/codegeex/widgets/codeeditcomponent.cpp
- src/plugins/codegeex/widgets/translationpagewidget.cpp
1.增加tooltip。
2.翻译代码时，没有输入代码不会发送网络请求。
> 修复codeGeex问答/翻译界面显示问题

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
- src/app/main.cpp
- src/common/common.qrc
- src/common/icons/about_logo_128px.svg
incorrect logo in about dialog
> fix: incorrect logo in about dialog

- src/plugins/cxx/cmake/project/mainframe/cmakeasynparse.cpp
- src/plugins/cxx/cmake/project/mainframe/cmakeasynparse.h
- src/plugins/cxx/cmake/project/mainframe/cmakeprojectgenerator.cpp
- src/plugins/cxx/cmake/project/mainframe/cmakeprojectgenerator.h
- src/plugins/project/mainframe/projecttree.cpp
- src/services/project/projectgenerator.cpp
- src/services/project/projectgenerator.h
> fix: Changed menu in project tree

- debian/changelog
Log:
Change-Id: I418cc754fa348405a64e403f9957ef651e37973e
> tag: update to 1.2.8

- src/plugins/codegeex/codegeex/askapi.cpp
fix problem of can`t delete session
> fix: [codegeex] can`t delete session

- src/plugins/codeeditor/mainframe/naveditmainwindow.cpp
- src/plugins/recent/mainframe/recentdisplay.cpp
> fix: Adjusting UI size 

- src/plugins/codeeditor/textedittabwidget/texteditsplitter.cpp
- src/plugins/codeeditor/textedittabwidget/texteditsplitter.h
- src/plugins/codeeditor/textedittabwidget/textedittabwidget.cpp
> refactor: Changed textedit splitter

- src/plugins/codegeex/codegeex/askapi.cpp
- src/plugins/codegeex/codegeex/askapi.h
- src/plugins/codegeex/codegeexmanager.cpp
- src/plugins/codegeex/codegeexmanager.h
- src/plugins/codegeex/widgets/sessionrecorditem.cpp
Modify the 'History Session' window
> fix: [codeGeex] Modify the 'History Session' window

- src/plugins/cxx/cxxplugin.cpp
- src/plugins/cxx/ninja/project/ninjaprojectgenerator.h
- src/plugins/template/wizard/detailwidget.cpp
> fix: Ninja project create faild

- src/plugins/codeeditor/textedittabwidget/style/stylelsp.cpp
- src/plugins/codeeditor/textedittabwidget/style/stylelsp.h
- src/plugins/codeeditor/textedittabwidget/textedit.cpp
mutil initial of lspConnection when change theme
> fix: mutil initial of lspConnection when change theme

- src/plugins/option/optioncore/mainframe/shortcutsettingwidget.cpp
- src/plugins/option/optioncore/mainframe/shortcutsettingwidget.h
incorrect shortCut-description display in English env
> fix: incorrect shortCut-description display in English env

- src/plugins/builder/mainframe/buildmanager.cpp
top tooolbar buttong initialisation problem
> fix:  top tooolbar buttong initialisation problem

- src/plugins/codeeditor/textedittabwidget/style/stylelsp.cpp
An exception occurred during formatting code
> fix: [stylelsp] An exception occurred during formatting code

- src/common/inotify/private/inotify_linux.h
> fix: crash when close project

- src/plugins/cxx/cmake/cmakegenerator.cpp
- src/plugins/cxx/cmake/project/mainframe/properties/configutil.cpp
- src/plugins/cxx/cmake/project/mainframe/properties/environmentwidget.cpp
- src/plugins/cxx/cmake/project/mainframe/properties/environmentwidget.h
- src/plugins/debugger/runner/runner.cpp
- src/services/language/languagegenerator.h
- src/services/project/projectinfo.h
Apply environment variables in cmake project properties.
> fix: Apply environment variables in cmake project properties

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
- src/services/window/windowelement.h
"About Plugin" text is displayed incorrectly
> fix: "About Plugin" text is displayed incorrectly

- src/plugins/builder/mainframe/buildmanager.cpp
Compile widgets to add left and right stretching
> fix: Compile widgets to add left and right stretching

- src/plugins/codeeditor/textedittabwidget/texteditsplitter.cpp
Crash when closing last file in editor split.
> fix: Crash when closing last file in editor split

- src/plugins/codeeditor/textedittabwidget/textedittabbar.cpp
- src/plugins/codeeditor/textedittabwidget/textedittabbar.h
> feat: add menu for textedittabbar

- src/plugins/recent/mainframe/displayrecentview.cpp
- src/plugins/recent/mainframe/displayrecentview.h
- src/plugins/recent/mainframe/recentdisplay.cpp
- src/plugins/recent/mainframe/recentdisplay.h
incorrect display of recent Widget
add button to clear recent-open list
> feat: [recent-display] add button to clear recent-open list

- src/plugins/find/findtoolwindow.cpp
- src/plugins/find/findtoolwindow.h
- src/plugins/find/searchresultwindow.cpp
Changes to the warning window in the find plugin
> fix: Changes to the warning window in the find plugin

- src/plugins/project/mainframe/projecttree.cpp
Returns if the name of the new file is empty
> fix: Returns if the name of the new file is empty

- src/plugins/codeeditor/textedittabwidget/scintillaeditextern.cpp
Match the color of the line number and its background color according to the design drawing
> fix: Modify the line number color and its background color

- src/plugins/find/findplugin.cpp
- src/plugins/find/findtoolbar.cpp
- src/plugins/find/findtoolbar.h
> feat: FindToolBar ui modification

- assets/translations/zh_CN.ts
- debian/changelog
Log:
Change-Id: I14f10255ef26101e32180705bfa4c92e2b7ca7e5
> translation: update

- src/plugins/codeeditor/textedittabwidget/textedittabbar.cpp
- src/plugins/codeeditor/textedittabwidget/textedittabbar.h
Incomplete display of textedittabbar
> fix: Incomplete display of textedittabbar

- src/plugins/codeeditor/textedittabwidget/textedittabbar.cpp
- src/plugins/codeeditor/textedittabwidget/textedittabbar.h
textedittabbar corner position display adjusted to right angle
> fix: textedittabbar corner position display adjusted to right angle

- src/plugins/codeeditor/textedittabwidget/textedittabbar.cpp
- src/plugins/codeeditor/textedittabwidget/textedittabbar.h
> fix: textedittabbar ui update

- src/plugins/cxx/cmake/project/mainframe/properties/configureprojpane.cpp
Log:
Change-Id: Idb9a714fe6456aaa04142391ec2e0094da08a956
> feat: set default build parameter

- src/plugins/cxx/cmake/project/mainframe/properties/stepspane.cpp
- src/plugins/cxx/cmake/project/mainframe/properties/stepspane.h
Log:
Change-Id: I5a1ceee13fc6d32c835116a9be8c94520296d332
> refactor: remove unused parameter in build step

- src/plugins/cxx/cmake/project/mainframe/cmakeprojectgenerator.cpp
- src/plugins/cxx/cmake/project/mainframe/cmakeprojectgenerator.h
- src/plugins/cxx/cmake/project/mainframe/properties/buildpropertywidget.cpp
- src/plugins/cxx/cmake/project/mainframe/properties/configutil.cpp
Log:
Change-Id: I06c8b20256a0b0f7a635bb7dade392f3b5b34e61
> refactor: add build menu in project contextmenu

- src/plugins/project/mainframe/projecttree.cpp
- src/plugins/project/mainframe/projecttree.h
Log:
Change-Id: Ib445f69d8b03b81b0032bd7c07ded89ebdeac189
> feat: add open contain folder action

- src/plugins/project/mainframe/projecttree.cpp
Log:
Change-Id: If1c0588e46471df3f443ec3d880bdad883dcfddb
> feat: add running action in project menu

- src/plugins/cxx/cmake/project/mainframe/cmakeprojectgenerator.cpp
- src/plugins/cxx/cmake/project/mainframe/cmakeprojectgenerator.h
Log:
Change-Id: I8b54b536f7f91eaf55136aa47c564cea30d57845
> feat: add runcmake menu item

- src/plugins/core/CMakeLists.txt
- src/plugins/core/mainframe/mainwindow.cpp
- src/plugins/core/mainframe/mainwindow.h
> refactor: [core] add new file

- src/plugins/console/console.cpp
- src/plugins/console/consolewidget.cpp
- src/plugins/project/mainframe/projecttree.cpp
- src/plugins/project/mainframe/projecttree.h
- src/services/CMakeLists.txt
- src/services/terminal/terminalservice.h
Log:
Change-Id: I1aa0d8bca2e9ad650708dc22db2deb1b0342b700
> feat: add run-in-terminal menu item

- src/plugins/cxx/cmake/project/mainframe/cmakeprojectgenerator.cpp
- src/plugins/template/wizard/maindialog.cpp
- src/services/project/projectinfo.h
- src/services/project/projectservice.h
Log:
Change-Id: Ib3f02e308ac0bcbb6d51fc0c5c765ffceb2a0b89
> refactor: remove unused code

- src/common/util/custompaths.cpp
custompaths not updated when configure
path changed.
Log:
Change-Id: Idaaaafc226b4d8f074d39990d4eb0b6baba0f30f
> fix: configure file path changed

- src/plugins/core/CMakeLists.txt
- src/plugins/core/core.cpp
- src/plugins/core/mainframe/controller.cpp
- src/plugins/core/mainframe/controller.h
- src/plugins/core/mainframe/mainwindow.cpp
- src/plugins/core/mainframe/mainwindow.h
- src/plugins/core/mainframe/navigationbar.cpp
- src/plugins/core/mainframe/navigationbar.h
- src/services/window/windowelement.h
- src/services/window/windowservice.h
append `controller` to replace `windowkeeper` later
> refactor: [core] append controller to replace windowkeeper later

- src/plugins/core/mainframe/controller.cpp
> fix: Spelling errors in words

- src/common/util/eventdefinitions.h
- src/plugins/codeeditor/codeeditor.cpp
- src/plugins/codeeditor/codeeditor.h
- src/plugins/codeeditor/gui/private/tabwidget_p.h
- src/plugins/codeeditor/gui/private/texteditor_p.cpp
- src/plugins/codeeditor/gui/private/texteditor_p.h
- src/plugins/codeeditor/gui/private/workspacewidget_p.h
- src/plugins/codeeditor/gui/tabwidget.cpp
- src/plugins/codeeditor/gui/tabwidget.h
- src/plugins/codeeditor/gui/texteditor.cpp
- src/plugins/codeeditor/gui/workspacewidget.cpp
- src/plugins/codeeditor/manager/texteditormanager.cpp
- src/plugins/codeeditor/manager/texteditormanager.h
- src/plugins/codeeditor/transceiver/codeeditorreceiver.cpp
- src/plugins/codeeditor/transceiver/codeeditorreceiver.h
> feat: [editor] Implement a feature of  cursor position back or forward

- src/plugins/cxx/cmake/project/cmakeprojectgenerator.cpp
- src/plugins/cxx/cmake/project/properties/bulidCfgWidget/buildpropertypage.cpp
- src/plugins/cxx/cmake/project/properties/bulidCfgWidget/buildpropertypage.h
- src/plugins/cxx/cmake/project/properties/bulidCfgWidget/stepspane.cpp
- src/plugins/cxx/cmake/project/properties/configWidget/configureprojpane.cpp
- src/plugins/cxx/cmake/project/properties/configWidget/configureprojpane.h
- src/plugins/cxx/cmake/project/properties/configutil.cpp
- src/plugins/cxx/cmake/project/properties/configutil.h
- src/plugins/cxx/cmake/project/properties/environmentwidget.cpp
- src/plugins/cxx/cmake/project/properties/environmentwidget.h
- src/plugins/cxx/cmake/project/properties/runCfgWidget/runconfigpane.cpp
- src/plugins/cxx/cmake/project/properties/runCfgWidget/runconfigpane.h
- src/plugins/cxx/cmake/project/properties/runCfgWidget/runpropertypage.cpp
- src/plugins/java/maven/project/mavenprojectgenerator.h
- src/plugins/javascript/project/properties/configpropertywidget.cpp
- src/plugins/javascript/project/properties/configpropertywidget.h
- src/plugins/javascript/project/properties/configutil.cpp
- src/plugins/javascript/project/properties/configutil.h
- src/plugins/python/python/project/properties/configpropertywidget.cpp
- src/plugins/python/python/project/properties/configpropertywidget.h
- src/plugins/python/python/project/properties/configutil.cpp
- src/plugins/python/python/project/properties/configutil.h
Log:
Change-Id: I768c198511c031bcb89ceff8bca0ebdfeb01a8d2
> refactor: [cxxplugin] re-write some class&struct

- src/plugins/cxx/cmake/project/cmakeprojectgenerator.cpp
- src/plugins/cxx/cmake/project/cmakeprojectgenerator.h
- src/plugins/cxx/cmake/project/properties/bulidCfgWidget/buildpropertypage.cpp
- src/plugins/cxx/cmake/project/properties/bulidCfgWidget/buildpropertypage.h
- src/plugins/cxx/cmake/project/properties/configutil.cpp
- src/plugins/cxx/cmake/project/properties/configutil.h
- src/plugins/cxx/cmake/project/properties/environmentwidget.cpp
- src/plugins/cxx/cmake/project/properties/environmentwidget.h
- src/plugins/cxx/cmake/project/properties/runCfgWidget/runpropertypage.cpp
- src/plugins/cxx/cmake/project/properties/targetsmanager.cpp
- src/plugins/cxx/cmake/project/properties/targetsmanager.h
- src/plugins/project/mainframe/projecttree.cpp
- src/plugins/project/mainframe/projecttree.h
- src/plugins/project/projectcore.cpp
- src/services/project/projectservice.h
enable this config could output debug
level information when debug.
Log:
Change-Id: Ie53420da50d3d5cbe76a079f837527cc0918ea37
> feat: [cxxplugin] add qt debug level config

- src/plugins/collaborators/collaborators.cpp
- src/plugins/debugger/debuggerplugin.cpp
> fix: crash when close applicaiton

- src/plugins/core/core.cpp
- src/plugins/core/mainframe/controller.cpp
- src/plugins/recent/recent.cpp
issue of memory released and code style
> refactor: [core] issue of memory released and code style

- src/common/util/eventdefinitions.h
- src/plugins/codeeditor/codeeditor.cpp
- src/plugins/codeeditor/codeeditor.h
- src/plugins/codeeditor/gui/private/tabwidget_p.h
- src/plugins/codeeditor/gui/private/texteditor_p.cpp
- src/plugins/codeeditor/gui/private/texteditor_p.h
- src/plugins/codeeditor/gui/private/workspacewidget_p.h
- src/plugins/codeeditor/gui/tabwidget.cpp
- src/plugins/codeeditor/gui/tabwidget.h
- src/plugins/codeeditor/gui/texteditor.cpp
- src/plugins/codeeditor/gui/texteditor.h
- src/plugins/codeeditor/gui/workspacewidget.cpp
- src/plugins/codeeditor/gui/workspacewidget.h
- src/plugins/codeeditor/transceiver/codeeditorreceiver.cpp
- src/plugins/codeeditor/transceiver/codeeditorreceiver.h
- src/plugins/codegeex/copilot.cpp
- src/plugins/codeporting/codeportingmanager.cpp
- src/plugins/cxx/cmake/project/cmakeprojectgenerator.cpp
- src/plugins/filebrowser/mainframe/treeview.cpp
- src/plugins/find/searchresultwindow.cpp
- src/plugins/project/mainframe/projecttree.cpp
- src/services/editor/editorservice.h
- src/services/project/projectgenerator.cpp
1.Implement search and replace interface
2.Implement jump interface
3.Implement the setting line background color interface
Log: Interface completion
> refactor: [editor] Interface completion

- src/services/window/windowservice.h
Log:
Change-Id: I428545e68e0ec246f153cd12e5c1729efd1d32d1
> refactor: [service] remove unused signal

- src/plugins/java/CMakeLists.txt
- src/plugins/java/maven/project/mavenasynparse.h
- src/plugins/java/maven/project/mavenprojectgenerator.cpp
- src/plugins/java/maven/project/mavenprojectgenerator.h
- src/plugins/java/maven/project/projectactioninfo.h
- src/services/CMakeLists.txt
- src/services/project/projectinfo.h
Log:
Change-Id: I4bab8d163855f097eed515d509779ec9d868bab4
> refactor: [service] move code to java plugin

- src/common/util/eventdefinitions.h
- src/plugins/codeeditor/gui/private/tabwidget_p.h
- src/plugins/codeeditor/gui/private/texteditor_p.cpp
- src/plugins/codeeditor/gui/private/texteditor_p.h
- src/plugins/codeeditor/gui/tabwidget.cpp
- src/plugins/codeeditor/gui/texteditor.cpp
- src/plugins/codeeditor/gui/texteditor.h
- src/plugins/codeeditor/transceiver/codeeditorreceiver.cpp
- src/plugins/codeeditor/transceiver/codeeditorreceiver.h
- src/plugins/codeporting/codeportingmanager.cpp
> refactor: [editor] Add interface for annotation

- src/framework/backtrace/backtrace.cpp
- src/plugins/python/python/project/properties/configpropertywidget.cpp
- src/plugins/python/python/project/pythonprojectgenerator.cpp
- src/plugins/python/python/pythongenerator.cpp
Log:
Change-Id: I9a6f898adb4283a09c01c6739490a212475dbd6e
> fix: [python] cannot run in some condition

- src/base/abstractaction.cpp
- src/base/abstractaction.h
- src/base/abstractmenu.cpp
- src/base/abstractmenu.h
- src/common/actionmanager/actionmanager.cpp
- src/common/actionmanager/actionmanager.h
- src/plugins/actionanalyse/actionanalyseplugin.cpp
- src/plugins/binarytools/binarytools.cpp
- src/plugins/builder/mainframe/buildmanager.cpp
- src/plugins/codeeditor/codeeditor.cpp
- src/plugins/codeporting/codeportingplugin.cpp
- src/plugins/collaborators/mainframe/svn/svnclientwidget.cpp
- src/plugins/core/mainframe/controller.cpp
- src/plugins/core/mainframe/controller.h
- src/plugins/core/mainframe/workspacewidget.cpp
- src/plugins/cxx/cmake/project/cmakeprojectgenerator.cpp
- src/plugins/debugger/interface/menumanager.cpp
- src/plugins/debugger/runner/runner.cpp
- src/plugins/find/findplugin.cpp
- src/plugins/option/optioncore/optioncore.cpp
- src/plugins/reversedebug/reversedebugplugin.cpp
- src/plugins/template/templatemanager.cpp
- src/plugins/valgrind/mainframe/valgrindrunner.cpp
- src/services/window/windowservice.h
refactoring action shortcut manager
> refactor: [actionmanager] refactoring action shortcut manager

- debian/changelog
Log:
Change-Id: Ie46c3008eb1eb2b1506166a2230ff315bca322d9
> tag: update to 1.2.10

- src/plugins/codeeditor/codeeditor.cpp
- src/plugins/codegeex/codegeex.cpp
- src/plugins/collaborators/collaborators.cpp
- src/plugins/core/gui/navigationbar.cpp
- src/plugins/core/gui/navigationbar.h
- src/plugins/core/modules/pluginmanagermodule.cpp
- src/plugins/core/uicontroller/controller.cpp
- src/plugins/core/uicontroller/controller.h
- src/plugins/debugger/debuggerplugin.cpp
- src/plugins/option/optioncore/optioncore.cpp
- src/plugins/recent/recent.cpp
- src/services/window/windowservice.h
set navigation action priority to sort
> feat: set navigation action priority to sort

- src/plugins/core/gui/navigationbar.cpp
- src/plugins/core/gui/navigationbar.h
- src/plugins/core/uicontroller/controller.cpp
- src/services/window/windowservice.h
> feat: [navigationbar] complete interface

- src/plugins/core/gui/navigationbar.h
- src/plugins/core/locator/locatormanager.h
modify namespace issue in .h file
> style: modify namespace issue in .h file

- src/plugins/codegeex/codegeex.cpp
- src/plugins/codegeex/widgets/codegeexwidget.cpp
- src/plugins/collaborators/collaborators.cpp
- src/plugins/core/gui/navigationbar.cpp
- src/plugins/core/modules/pluginmanagermodule.cpp
- src/plugins/core/uicontroller/controller.cpp
- src/plugins/core/uicontroller/controller.h
- src/plugins/core/uicontroller/mainwindow.cpp
- src/plugins/javascript/debugger/jsdebugger.cpp
- src/services/window/windowservice.h
update interfaces of controller
> refactor: [core] refactoring core

- src/plugins/binarytools/binarytools.cpp
- src/plugins/binarytools/mainframe/binarytoolsconfigview.cpp
> fix: [binaryTools] crash of app

- src/plugins/core/gui/plugindetailsview.cpp
- src/plugins/core/gui/plugindetailsview.h
webview could not quit normally, cause
app cannot exit.
Log: bug fix
Change-Id: Ifd4124da0506d4387835a1dcced2e0d2c9a0761f
> fix: [extension] cause app cannot exit

- src/plugins/core/gui/pluginlistview.cpp
- src/plugins/core/gui/pluginlistview.h
- src/plugins/core/gui/pluginstorewidget.cpp
- src/plugins/core/gui/pluginstorewidget.h
- src/plugins/core/gui/pluginsui.cpp
Log:
Change-Id: I312aa9eb056e50e0a87de7d555efed478d350c99
> feat: [extension] display detail information default

- debian/changelog
Log:
Change-Id: Ibb0e0873be653505c78b9c6ce740443ebe6560c0
> tag: update to 1.2.11

- src/plugins/codeeditor/gui/private/texteditor_p.cpp
- src/plugins/codeeditor/gui/texteditor.cpp
- src/plugins/codeeditor/gui/texteditor.h
- src/plugins/codeeditor/lsp/lspstyle.cpp
- src/plugins/codeeditor/lsp/lspstyle.h
- src/plugins/codeeditor/lsp/private/lspstyle_p.h
> refactor: Code prompt and jump

- src/plugins/cxx/cmake/project/cmakeasynparse.cpp
incorrect display of nodes in projcetTree
> fix: [projcet] incorrect display of nodes in projcetTree

- src/base/abstractlocator.cpp
- src/base/abstractlocator.h
- src/plugins/core/locator/actionlocator.cpp
- src/plugins/core/locator/locatormanager.cpp
- src/plugins/core/locator/locatormanager.h
- src/plugins/core/uicontroller/controller.cpp
- src/plugins/project/locator/allprojectfilelocator.cpp
- src/plugins/project/locator/currentprojectlocator.cpp
> feat: [locator] add shortCut to locator

- 3rdparty/unioncode-qscintilla214/src/PlatQt.cpp
- src/common/lsp/client/stdoutjsonrpcparser.cpp
- src/common/lsp/client/stdoutjsonrpcparser.h
- src/plugins/codeeditor/gui/private/tabbar_p.h
- src/plugins/codeeditor/gui/private/texteditor_p.cpp
- src/plugins/codeeditor/gui/tabbar.cpp
- src/plugins/codeeditor/gui/texteditor.cpp
- src/plugins/codeeditor/gui/texteditor.h
- src/plugins/codeeditor/lexer/lexermanager.cpp
- src/plugins/codeeditor/lsp/lspstyle.cpp
- src/plugins/codeeditor/lsp/lspstyle.h
- src/plugins/codeeditor/lsp/private/lspstyle_p.h
- src/plugins/project/mainframe/projectdelegate.cpp
- src/plugins/project/mainframe/projectdelegate.h
1.Add error prompt
2.Add menu for tabbar
Log: Features completion
> refactor: [editor] Features completion

- src/plugins/codegeex/copilot.cpp
- src/plugins/codegeex/copilot.h
- src/plugins/codegeex/option/codegeexoptionwidget.cpp
- src/plugins/codegeex/option/detailwidget.cpp
- src/plugins/codegeex/option/detailwidget.h
- src/services/option/optionutils.cpp
Log:
Bug:
Change-Id: I7a8f0d5cd69456cb1c0854a5ed7ce41a525ff388
> feat: [codegeex] add generation enable config

- src/common/CMakeLists.txt
- src/plugins/core/gui/pluginitemdelegate.cpp
Log:
Change-Id: If5fe6c164dcd8df61b40c5b384838db5eea20237
> fix: build faild

- src/plugins/cxx/cmake/project/cmakeasynparse.cpp
Make nodes in the project view orderly
> fix: [project] Make nodes in the project view orderly

- src/base/abstractlexerproxy.cpp
- src/base/abstractlexerproxy.h
- src/common/lsp/client/client.cpp
- src/common/lsp/client/stdoutjsonrpcparser.cpp
- src/common/lsp/client/stdoutjsonrpcparser.h
- src/plugins/codeeditor/gui/private/texteditor_p.cpp
- src/plugins/codeeditor/lsp/lspstyle.cpp
- src/plugins/cxx/lexer/scilexercpp.cpp
1.Set completion to be case insensitive
2.Fixed a highlight failure issue
Log: fix issue
> fix: [editor] Fix LSP-related problems

- 3rdparty/unioncode-qscintilla214/src/Qsci/qsciscintilla.h
- src/plugins/codeeditor/gui/private/tabwidget_p.h
- src/plugins/codeeditor/gui/private/texteditor_p.cpp
- src/plugins/codeeditor/gui/private/texteditor_p.h
- src/plugins/codeeditor/gui/tabwidget.cpp
- src/plugins/codeeditor/gui/texteditor.cpp
- src/plugins/codeeditor/gui/texteditor.h
- src/plugins/codeeditor/lsp/lspstyle.cpp
- src/plugins/codeeditor/lsp/lspstyle.h
- src/plugins/codeeditor/lsp/private/lspstyle_p.h
- src/plugins/codeeditor/renamepopup/renamepopup.cpp
- src/plugins/codeeditor/transceiver/codeeditorreceiver.cpp
- src/plugins/codeeditor/transceiver/codeeditorreceiver.h
1.add `rename` action
2.add `switch declaration and definition` action
3.add `find usages` action
Log: refactor
> refactor: [editor] add items for menu

- 3rdparty/unioncode-qscintilla214/src/PlatQt.cpp
- 3rdparty/unioncode-qscintilla214/src/Qsci/qscilexer.h
- 3rdparty/unioncode-qscintilla214/src/qscilexer.cpp
- assets/configures/editorstyle_cpp.support
- src/base/abstractlexerproxy.cpp
- src/plugins/codeeditor/gui/private/texteditor_p.cpp
- src/plugins/codeeditor/lsp/lspclientmanager.cpp
- src/plugins/codeeditor/lsp/lspstyle.cpp
- src/plugins/codeeditor/lsp/lspstyle.h
- src/plugins/cxx/lexer/scilexercpp.cpp
adapts to switch between dark and light themes
Log: theme
> refactor: [editor] Adaptive theme switching

- src/plugins/codeeditor/gui/private/texteditor_p.cpp
- src/plugins/filebrowser/CMakeLists.txt
- src/plugins/filebrowser/mainframe/filebrowserdelegate.cpp
- src/plugins/filebrowser/mainframe/filebrowserdelegate.h
- src/plugins/filebrowser/mainframe/treeview.cpp
- src/plugins/filebrowser/mainframe/treeview.h
- src/plugins/project/mainframe/projectdelegate.cpp
- src/plugins/symbol/CMakeLists.txt
- src/plugins/symbol/mainframe/symbolitemdelegate.cpp
- src/plugins/symbol/mainframe/symbolitemdelegate.h
- src/plugins/symbol/mainframe/symboltreeview.cpp
> fix: [UI] Modify the font color issue

- src/common/util/fileoperation.cpp
- src/common/util/fileoperation.h
- src/plugins/filebrowser/mainframe/treeview.cpp
- src/plugins/filebrowser/mainframe/treeview.h
- src/plugins/project/mainframe/projecttree.cpp
- src/plugins/project/mainframe/projecttree.h
Log:
Change-Id: I0e1f9dddef392bfdfcf1025b89b69d33b8d192da
> feat: [project] add rename、delete、new

- src/plugins/codeeditor/lsp/lspstyle.cpp
> fix: [editor] Fixed text color flicker issue

- src/plugins/codeeditor/lsp/lspstyle.cpp
- src/plugins/codeeditor/lsp/lspstyle.h
> fix: [editor] Editor style disappears After opening a new file

- debian/changelog
Log:
Change-Id: I655239b431b031a28a64ccc8cf460a6fd55dc9c2
> tag: update to 1.2.12

- src/plugins/project/mainframe/projectdelegate.cpp
- src/plugins/project/mainframe/projectdelegate.h
Log:
Change-Id: Ic56831ffd817a2b1b189e69753b66ce776ff12a8
> fix: [project] active project tree without bold set

- src/plugins/codeeditor/gui/private/texteditor_p.cpp
- src/plugins/codeeditor/gui/tabwidget.cpp
- src/plugins/cxx/cxxplugin.cpp
- src/plugins/cxx/lexer/scilexercmake.cpp
- src/plugins/cxx/lexer/scilexercmake.h
- src/plugins/cxx/lexer/scilexercpp.cpp
Fixed file cannot be dragged and dropped into the editor
Log: fix issue
> fix: [editor] Fixed file drag and drop issues

- assets/configures/editorstyle_python.support
- src/base/abstractlexerproxy.cpp
- src/base/abstractlexerproxy.h
- src/plugins/codeeditor/lexer/scilexerhandler.cpp
- src/plugins/codeeditor/lexer/scilexerhandler.h
- src/plugins/codeeditor/lsp/lspclientmanager.cpp
- src/plugins/python/CMakeLists.txt
- src/plugins/python/lexer/scilexerpython.cpp
- src/plugins/python/lexer/scilexerpython.h
- src/plugins/python/pythonplugin.cpp
- src/plugins/python/pythonplugin.h
Add theme for python
Log: refactor
> refactor: [editor] Add theme

- 3rdparty/unioncode-qscintilla214/src/Qsci/qsciscintilla.h
- 3rdparty/unioncode-qscintilla214/src/Qsci/qsciscintillabase.h
- 3rdparty/unioncode-qscintilla214/src/qsciscintilla.cpp
- src/common/lsp/client/client.cpp
- src/common/lsp/client/client.h
- src/common/lsp/client/private/client_p.h
- src/common/lsp/client/stdoutjsonrpcparser.cpp
- src/plugins/codeeditor/gui/private/texteditor_p.cpp
- src/plugins/codeeditor/gui/private/texteditor_p.h
- src/plugins/codeeditor/lsp/lspstyle.cpp
- src/plugins/codeeditor/lsp/lspstyle.h
1.Fixed highlighting issue
2.Fixed crash issue
> fix: [editor] Fixed some issues

- src/plugins/debugger/dap/dapdebugger.cpp
- src/plugins/debugger/dap/debugsession.cpp
- src/plugins/debugger/debuggerplugin.cpp
- src/plugins/debugger/interface/localtreeitem.cpp
- src/plugins/debugger/interface/localtreeitem.h
- src/plugins/debugger/interface/localtreemodel.cpp
- src/scripts/CMakeLists.txt
- src/scripts/prettyprinters/helper.py
- src/scripts/prettyprinters/qt.py
- src/tools/debugadapter/CMakeLists.txt
- src/tools/debugadapter/dapsession.cpp
- src/tools/debugadapter/debugger/debugger.h
- src/tools/debugadapter/debugger/gdbmi/gdbdebugger.cpp
- src/tools/debugadapter/debugger/gdbmi/gdbdebugger.h
- src/tools/debugadapter/debugger/gdbmi/gdbmi.h
- src/tools/debugadapter/debugger/javascript/jsdebugger.cpp
- src/tools/debugadapter/debugger/javascript/jsdebugger.h
- src/tools/debugadapter/debugmanager.cpp
- src/tools/debugadapter/debugmanager.h
> feat: [debugger] watch data formating

- src/plugins/codeeditor/gui/tabwidget.cpp
- src/plugins/codeeditor/gui/tabwidget.h
- src/plugins/codeeditor/gui/texteditor.cpp
- src/plugins/codeeditor/gui/texteditor.h
- src/plugins/codeeditor/gui/workspacewidget.cpp
> fix: [editor] Fixed an issue where Ai prompt messages could not be inserted

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
> translation: update translations

- src/plugins/codeeditor/codeeditor.cpp
- src/plugins/codeeditor/gui/tabwidget.cpp
- src/plugins/codeeditor/gui/tabwidget.h
- src/plugins/codeeditor/gui/workspacewidget.cpp
- src/plugins/codeeditor/gui/workspacewidget.h
- src/services/editor/editorservice.h
1.Add the interface to the modified file list
2.Added an interface for saving all files
Log: Add interfaces
> refactor: [editor] Add interfaces

- src/plugins/cxx/cmake/builder/generator/cmakebuildergenerator.cpp
- src/plugins/python/python/pythongenerator.cpp
Log:
Change-Id: I96cb33a3b19451ec177897b345771b09f38de0e8
> fix: [project] parameters config not correct

- src/plugins/codeeditor/gui/texteditor.cpp
> fix: [editor] Fixed compile issue

- src/plugins/cxx/cmake/project/cmakeasynparse.cpp
Log: bug fix
Change-Id: Ibb3f3e87deadee1bf12e35b8177c80d371d6e299
> fix: crashed when open project

- src/plugins/debugger/interface/localtreemodel.cpp
crash when update watch variables
> fix: [debugger] crash when update watch variables

- debian/changelog
Log:
Bug:
Change-Id: I6cecba6f7838422742f3c0b75fe04ae3abf22563
> tag: update to 1.2.14

- src/plugins/binarytools/mainframe/binarytoolsconfigview.cpp
- src/plugins/binarytools/mainframe/binarytoolsdialog.cpp
- src/plugins/codeeditor/gui/private/texteditor_p.cpp
- src/plugins/codeeditor/gui/tabbar.cpp
- src/plugins/core/uicontroller/controller.cpp
- src/plugins/core/uicontroller/mainwindow.cpp
- src/plugins/debugger/dap/dapdebugger.cpp
- src/plugins/find/findtoolbar.cpp
- src/plugins/recent/mainframe/displayitemdelegate.cpp
- src/plugins/reversedebug/eventfilterdialog.cpp
Compilation failed on lower versions os
> fix: [complie] Compilation failed on lower versions os

- src/plugins/builder/tasks/taskdelegate.cpp
- src/plugins/codeeditor/gui/workspacewidget.cpp
- src/plugins/codeeditor/lsp/lspstyle.cpp
- src/plugins/codeporting/reportpane.cpp
- src/plugins/core/gui/pluginitemdelegate.cpp
- src/plugins/core/uicontroller/controller.cpp
- src/plugins/cxx/cmake/project/cmakeprojectgenerator.cpp
- src/plugins/find/searchresultwindow.cpp
- src/plugins/option/optioncore/mainframe/optionsdialog.cpp
- src/plugins/recent/mainframe/displayitemdelegate.cpp
Log:
Change-Id: Ida7cda815f0b3343db106fc455d5f0faca7506ce
> chore: adapter dtk low version

- 3rdparty/unioncode-jsonrpccpp/libjson-rpc-cpp/cmake/FindThreads.cmake
- src/plugins/option/optioncore/mainframe/optionsdialog.cpp
Log:
Change-Id: Iebc4c7711c2f42f57964b093a5a47ea95846ebe6
> fix: cannot find lthread

- src/plugins/CMakeLists.txt
Log:
Change-Id: Icbe971291c6edb2ddb6ac2b2df66a35fde9a4fb5
> fix: clang cannot found

- src/plugins/debugger/dap/dapdebugger.cpp
- src/plugins/debugger/dap/dapdebugger.h
- src/plugins/debugger/dap/debugsession.cpp
- src/plugins/debugger/dap/debugsession.h
- src/plugins/debugger/interface/localtreeitem.cpp
- src/plugins/debugger/interface/localtreeitem.h
- src/plugins/debugger/interface/localtreemodel.cpp
- src/plugins/debugger/interface/localtreemodel.h
- src/tools/debugadapter/dapsession.cpp
- src/tools/debugadapter/debugger/debugger.h
- src/tools/debugadapter/debugger/gdbmi/gdbdebugger.cpp
- src/tools/debugadapter/debugger/gdbmi/gdbdebugger.h
- src/tools/debugadapter/debugger/gdbmi/gdbmi.cpp
- src/tools/debugadapter/debugger/gdbmi/gdbmi.h
- src/tools/debugadapter/debugger/javascript/jsdebugger.cpp
- src/tools/debugadapter/debugger/javascript/jsdebugger.h
- src/tools/debugadapter/debugmanager.cpp
- src/tools/debugadapter/debugmanager.h
> feat: [debugger] view of watch-data area

- src/plugins/core/uicontroller/controller.cpp
- src/plugins/core/uicontroller/controller.h
- src/plugins/debugger/dap/dapdebugger.cpp
- src/plugins/debugger/debuggerplugin.cpp
- src/plugins/debugger/debugmanager.cpp
- src/plugins/debugger/debugmanager.h
- src/plugins/debugger/interface/localtreemodel.cpp
- src/services/window/windowservice.h
- src/tools/debugadapter/debugger/debugger.h
- src/tools/debugadapter/debugger/gdbmi/gdbdebugger.cpp
- src/tools/debugadapter/debugger/gdbmi/gdbdebugger.h
- src/tools/debugadapter/debugger/gdbmi/gdbmi.cpp
- src/tools/debugadapter/debugger/javascript/jsdebugger.cpp
- src/tools/debugadapter/debugger/javascript/jsdebugger.h
- src/tools/debugadapter/debugmanager.cpp
1. The abnormal size of the watch data window when opening it again after stopping debugging.
2. When debugging functions with complex stacks, the state is abnormal
3. In some cases, breakpoints cannot be inserted
4. To some extent, reduce the risk of deadlock
5. watch data support Chinese
> fix: [debugger] issues of debugger

- src/plugins/codeeditor/gui/private/texteditor_p.cpp
- src/plugins/codeeditor/gui/texteditor.cpp
- src/plugins/codeeditor/gui/texteditor.h
- src/plugins/codeeditor/lsp/lspstyle.cpp
- src/plugins/codeeditor/lsp/private/lspstyle_p.h
Use `QTooltip` to display the prompt
Log: fix issue
Bug: https://pms.uniontech.com/bug-view-240137.html
> fix: [editor] Fixed the issue of tooltip

- src/plugins/debugger/dap/dapdebugger.cpp
- src/plugins/debugger/interface/localtreeitem.cpp
- src/plugins/debugger/interface/localtreeitem.h
- src/scripts/prettyprinters/qt.py
- src/tools/debugadapter/debugger/gdbmi/gdbdebugger.cpp
- src/tools/debugadapter/debugger/gdbmi/gdbdebugger.h
- src/tools/debugadapter/debugger/gdbmi/gdbmi.cpp
support Qt types of watch data widget
fix some bugs of debugger
> feat: [debugger] support Qt types of watch data widget

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
- src/plugins/cxx/CMakeLists.txt
- src/plugins/java/CMakeLists.txt
- src/plugins/javascript/CMakeLists.txt
- src/plugins/performance/CMakeLists.txt
- src/plugins/python/CMakeLists.txt
Log:
Change-Id: Iff9285e14ab0d82bb4c2d75009d8aa14280ace4f
> feat: add more plugin logo

- src/common/util/environment.cpp
Log:
Change-Id: I0e64493e703cf22c1d48c1e7f36369f3ece3d855
> fix: open python project crashed in v23

- src/plugins/debugger/dap/dapdebugger.cpp
- src/plugins/debugger/dap/dapdebugger.h
- src/tools/debugadapter/debugger/gdbmi/gdbdebugger.cpp
Optimizing the loading and display of variables
> feat: [debugger] Optimizing the loading and display of variables

- src/common/util/eventdefinitions.h
- src/plugins/cxx/cmake/project/cmakeprojectgenerator.cpp
- src/plugins/cxx/cmake/project/transceiver/projectcmakereceiver.cpp
- src/plugins/cxx/cmake/project/transceiver/projectcmakereceiver.h
- src/plugins/filebrowser/CMakeLists.txt
- src/plugins/filebrowser/filebrowser.cpp
- src/plugins/filebrowser/mainframe/filetreeview.cpp
- src/plugins/filebrowser/mainframe/filetreeview.h
- src/plugins/filebrowser/mainframe/treeviewkeeper.cpp
- src/plugins/filebrowser/mainframe/treeviewkeeper.h
- src/plugins/project/mainframe/projecttree.cpp
- src/plugins/project/mainframe/projecttree.h
Log:
Change-Id: Icccdd6ccbd48f134bc7baeb19699fd88a793eac8
> refactor: add file deleted event

- src/base/abstractlexerproxy.cpp
- src/base/abstractlexerproxy.h
- src/plugins/codeeditor/gui/completion/codecompletiondelegate.cpp
- src/plugins/codeeditor/gui/completion/codecompletiondelegate.h
- src/plugins/codeeditor/gui/completion/codecompletionmodel.cpp
- src/plugins/codeeditor/gui/completion/codecompletionmodel.h
- src/plugins/codeeditor/gui/completion/codecompletionview.cpp
- src/plugins/codeeditor/gui/completion/codecompletionview.h
- src/plugins/codeeditor/gui/completion/codecompletionwidget.cpp
- src/plugins/codeeditor/gui/completion/codecompletionwidget.h
- src/plugins/codeeditor/gui/private/texteditor_p.cpp
- src/plugins/codeeditor/gui/private/texteditor_p.h
- src/plugins/codeeditor/gui/tabwidget.cpp
- src/plugins/codeeditor/gui/texteditor.cpp
- src/plugins/codeeditor/gui/texteditor.h
- src/plugins/codeeditor/lexer/scilexerhandler.cpp
- src/plugins/codeeditor/lexer/scilexerhandler.h
- src/plugins/codeeditor/lsp/lspstyle.cpp
- src/plugins/codeeditor/lsp/lspstyle.h
- src/plugins/codeeditor/lsp/private/lspstyle_p.h
- src/plugins/cxx/lexer/scilexercpp.cpp
- src/plugins/cxx/lexer/scilexercpp.h
- src/tools/languageadapter/main.cpp
> refactor: [editor] Optimize the code completion

- src/plugins/debugger/dap/dapdebugger.cpp
- src/plugins/debugger/interface/localtreemodel.cpp
- src/scripts/prettyprinters/qt.py
- src/tools/debugadapter/debugger/gdbmi/gdbdebugger.cpp
prettyprinters scripts makes gdb frozen
> fix: [debugger] gdb frozen when get variables

- src/plugins/codeeditor/gui/completion/codecompletiondelegate.cpp
- src/plugins/debugger/remotedebug/remotedebugdlg.cpp
- src/plugins/debugger/remotedebug/remotedebugdlg.h
Log:
Change-Id: I5b9a53b98a2599eb7c3569d3299a6a521ab503b4
> feat: [debugger] add remote debugging

- src/plugins/cxx/cmake/project/cmakeasynparse.cpp
Log: bug fix
Change-Id: I638fce1121e2ab259397bb1332d8ddb4de3f7a9f
> fix: crash when open project

- src/plugins/codeeditor/codeeditor.cpp
- src/plugins/codeeditor/gui/private/workspacewidget_p.h
- src/plugins/codeeditor/gui/tabwidget.cpp
- src/plugins/codeeditor/gui/tabwidget.h
- src/plugins/codeeditor/gui/texteditor.cpp
- src/plugins/codeeditor/gui/texteditor.h
- src/plugins/codeeditor/gui/workspacewidget.cpp
- src/plugins/codeeditor/lsp/lspstyle.cpp
- src/plugins/codeeditor/lsp/lspstyle.h
- src/plugins/codeeditor/transceiver/codeeditorreceiver.h
1.Added a breakpoint toggle shortcut
2.Added the definition jump shortcut key
Log: Add shortcut keys
> feat: [editor] Add shortcut keys

- src/plugins/codeeditor/lsp/lspstyle.cpp
- src/plugins/codeeditor/lsp/lspstyle.h
- src/plugins/core/gui/navigationbar.cpp
- src/plugins/debugger/debuggerplugin.cpp
as title
Log: Fixed compilation warning
> fix: Fixed compilation warning

- src/base/abstractlexerproxy.cpp
- src/base/abstractlexerproxy.h
- src/plugins/codeeditor/codeeditor.cpp
- src/plugins/codeeditor/codeeditor.h
- src/plugins/codeeditor/gui/private/tabwidget_p.h
- src/plugins/codeeditor/gui/private/texteditor_p.cpp
- src/plugins/codeeditor/gui/private/texteditor_p.h
- src/plugins/codeeditor/gui/private/workspacewidget_p.h
- src/plugins/codeeditor/gui/settings/editorsettings.cpp
- src/plugins/codeeditor/gui/settings/editorsettings.h
- src/plugins/codeeditor/gui/settings/editorsettingswidget.cpp
- src/plugins/codeeditor/gui/settings/editorsettingswidget.h
- src/plugins/codeeditor/gui/settings/fontcolorwidget.cpp
- src/plugins/codeeditor/gui/settings/fontcolorwidget.h
- src/plugins/codeeditor/gui/settings/settingsdefine.h
- src/plugins/codeeditor/gui/tabwidget.cpp
- src/plugins/codeeditor/gui/tabwidget.h
- src/plugins/codeeditor/gui/workspacewidget.cpp
- src/plugins/codeeditor/lexer/scilexerhandler.cpp
- src/plugins/codeeditor/lexer/scilexerhandler.h
- src/plugins/cxx/lexer/scilexercmake.cpp
- src/plugins/cxx/lexer/scilexercmake.h
- src/plugins/cxx/lexer/scilexercpp.cpp
- src/plugins/cxx/lexer/scilexercpp.h
- src/plugins/python/lexer/scilexerpython.cpp
- src/plugins/python/lexer/scilexerpython.h
- src/services/option/optionutils.cpp
Added editor font properties configuration
Log: editor settings
> feat: [editor] Added the editor properties setting page

- src/plugins/debugger/dap/dapdebugger.cpp
- src/plugins/debugger/interface/localtreeitem.cpp
- src/plugins/debugger/interface/localtreeitem.h
- src/plugins/debugger/interface/localtreemodel.cpp
- src/plugins/debugger/interface/localtreemodel.h
- src/tools/debugadapter/debugger/gdbmi/gdbdebugger.cpp
highlight value when update watch variables
> feat: [debugger] highlight value when update watch variables

- src/plugins/debugger/dap/dapdebugger.cpp
- src/plugins/debugger/interface/localtreeitem.cpp
- src/plugins/debugger/interface/localtreemodel.cpp
- src/tools/debugadapter/debugger/gdbmi/gdbdebugger.cpp
1.flash
2.Lag when updating multiple times.
> fix: [debugger] some issues of updating watch data

- src/tools/debugadapter/debugger/gdbmi/gdbdebugger.cpp
- src/tools/debugadapter/debugmanager.cpp
> fix: [debugger] Incomplete variable display

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
- src/plugins/option/optioncore/optioncore.cpp
> translations: update

- 3rdparty/unioncode-qscintilla214/src/qsciscintilla.cpp
- src/plugins/codeeditor/codeeditor.cpp
- src/plugins/core/uicontroller/controller.cpp
- src/plugins/find/findplugin.cpp
1.Fixed an issue with indentation exceptions
2.Fixed an issue with invalid advanced search shortcut
Log: fix issue
> fix: [editor] Fixed some issue

- src/plugins/codeeditor/gui/completion/codecompletionwidget.cpp
- src/plugins/codeeditor/gui/private/workspacewidget_p.h
- src/plugins/codeeditor/gui/workspacewidget.cpp
- src/plugins/codeeditor/transceiver/codeeditorreceiver.cpp
- src/plugins/codeeditor/transceiver/codeeditorreceiver.h
Complete the content about the `setModifiedAutoReload`
Log: fix issue
> fix: [editor] Complete the interface content

- src/base/abstractoutputparser.h
- src/plugins/cxx/CMakeLists.txt
- src/plugins/cxx/ninja/builder/parser/ninjaparser.cpp
- src/plugins/cxx/ninja/project/ninjaasynparse.cpp
Log:
Change-Id: I875abebc6b8aac5b9645bc7e4bacddb5b2ae0ba1
> fix: [cxx] ninja build failed

- src/plugins/builder/mainframe/buildmanager.cpp
- src/plugins/debugger/debugmanager.cpp
- src/plugins/debugger/runner/runner.cpp
Log:
Change-Id: I16c3b2bd5f5a1ae9d246786d269ce4067b5cdf8f
> chore: save files before build/debug/run

- src/plugins/debugger/dap/dapdebugger.cpp
- src/plugins/debugger/interface/stackframemodel.cpp
- src/tools/debugadapter/debugger/gdbmi/gdbdebugger.cpp
- src/tools/debugadapter/debugmanager.cpp
can not show disassemble when frame file is not exsited
> fix:[debugger] can not show disassemble when frame file is not exsited

- src/common/toolchain/toolchain.cpp
- src/plugins/actionanalyse/mainframe/wordcountanalyse.cpp
- src/plugins/codeporting/codeporting.cpp
- src/plugins/python/python/project/properties/configpropertywidget.cpp
- src/plugins/python/python/project/pythonasynparse.cpp
- src/plugins/python/python/project/pythonasynparse.h
- src/plugins/python/python/project/pythonprojectgenerator.cpp
- src/plugins/python/python/pythongenerator.cpp
- src/plugins/symbol/mainframe/symbolparser.cpp
> fix: [python] incorrect python version

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
- src/plugins/codeeditor/codeeditor.cpp
- src/plugins/codeeditor/gui/private/tabwidget_p.h
- src/plugins/codeeditor/gui/tabwidget.cpp
as title
Log: Add blank page display content
> feat: [editor] Add blank page display content

- debian/changelog
Log:
Change-Id: Ic6b305e7c62ff4efa5c1908c6e29a9c18bce42b6
> tag: update to 1.2.16

- src/plugins/debugger/dap/dapdebugger.cpp
> fix: issue of build

- src/plugins/codeeditor/gui/completion/codecompletionextendwidget.cpp
- src/plugins/codeeditor/gui/tabwidget.cpp
as title
Log: Fixed a compilation failure issue
> fix: Fixed a compilation failure issue

- src/plugins/codeeditor/gui/completion/codecompletiondelegate.cpp
- src/plugins/debugger/dap/dapdebugger.cpp
Log:
Change-Id: I66010ba21e6945306d94608a69d6580f0e0d58ee
> fix: build failed on low version

- src/plugins/codeeditor/gui/completion/codecompletiondelegate.cpp
- src/plugins/codeeditor/gui/completion/codecompletionwidget.cpp
Log:
Change-Id: Iae8274571eb4a8f8f17a878f428b09ff66f1e4e1
> fix: build failed

- src/plugins/codeeditor/gui/completion/codecompletiondelegate.cpp
Log:
Change-Id: I3731803a787b46674d4869d115a302ebc54ba900
> fix: miss DPaletteHelper modified

- src/plugins/cxx/cmake/project/cmakeprojectgenerator.cpp
Log:
Change-Id: Ic940d84c1ddacd3c2ff9ca416c8b385066b34b87
> fix: [cxx] project tree repeat when multi-configure

- src/plugins/actionanalyse/actionanalyseplugin.json
- src/plugins/builder/buildercore.json
- src/plugins/commandproxy/commandproxy.json
- src/plugins/console/console.json
- src/plugins/core/gui/plugindetailsview.cpp
- src/plugins/core/gui/plugindetailsview.h
- src/plugins/core/gui/pluginstorewidget.cpp
- src/plugins/core/gui/pluginstorewidget.h
- src/plugins/cxx/cxxplugin.json
- src/plugins/filebrowser/filebrowser.json
- src/plugins/find/findplugin.json
- src/plugins/java/javaplugin.json
- src/plugins/javascript/javascriptplugin.json
- src/plugins/option/optioncore/optioncore.json
- src/plugins/performance/performance.json
- src/plugins/python/pythonplugin.json
- src/plugins/symbol/symbol.json
> feat: [pluginmanager] ui adjustment

- src/plugins/collaborators/collaborators.json
- src/plugins/console/console.json
- src/plugins/filebrowser/filebrowser.json
- src/plugins/symbol/symbol.json
- src/plugins/template/templateplugin.json
Log:
Change-Id: Ia1d23e80c9165d843caae60b3f22459317e1be39
> fix: [extension] modify description in meta json

- src/plugins/core/gui/plugindetailsview.cpp
- src/plugins/core/gui/plugindetailsview.h
Log:
Change-Id: Ib1755c34dfd394675631d76371c663697ba709d7
> fix: [extension] auto zoom web view

- src/common/util/custompaths.cpp
- src/plugins/cxx/cmake/project/cmakeasynparse.cpp
> fix: [cmake] crash when open project

- src/plugins/core/gui/plugindetailsview.cpp
- src/plugins/core/gui/pluginitemdelegate.cpp
- src/plugins/core/gui/pluginlistview.cpp
- src/plugins/core/gui/pluginlistview.h
- src/plugins/core/gui/pluginstorewidget.cpp
Log:
Change-Id: Iff2a6137d0da5396eb290965d9f7b9e480ddd89a
> fix: [extension] display issue

- debian/changelog
Log:
Change-Id: Iad167507d909f1304803e8ae2a8750570e1fa27e
> tag: update to 1.2.17

- debian/control
- src/tools/languageadapter/main.cpp
Log:
Change-Id: Ieb27d8d86071d3b811dc2c71291ada24c80c1535
> chore: optimize runtime depends

- src/plugins/codeeditor/gui/texteditor.cpp
> fix: [editor] Undo operation exception after the file is saved

- src/common/util/eventdefinitions.h
- src/plugins/debugger/dap/dapdebugger.cpp
- src/plugins/debugger/dap/dapdebugger.h
- src/plugins/debugger/dap/debugmodel.cpp
- src/plugins/debugger/dap/debugmodel.h
- src/plugins/debugger/dap/debugservice.cpp
- src/plugins/debugger/dap/debugservice.h
- src/plugins/debugger/interface/breakpointitem.cpp
- src/plugins/debugger/interface/breakpointitem.h
- src/plugins/debugger/interface/breakpointmodel.cpp
- src/plugins/debugger/interface/breakpointmodel.h
- src/plugins/debugger/interface/breakpointview.cpp
- src/plugins/debugger/interface/breakpointview.h
- src/plugins/debugger/interface/stackframeview.cpp
add interface of enable/disable breakpoint
> feat: [debugger] add interface of enable/disable breakpoint

- src/plugins/debugger/dap/dapdebugger.cpp
- src/plugins/debugger/dap/dapdebugger.h
- src/plugins/debugger/dap/debugservice.cpp
- src/plugins/debugger/dap/debugservice.h
- src/plugins/debugger/dap/debugsession.cpp
- src/plugins/debugger/dark/icons/breakpoint_14px.svg
- src/plugins/debugger/dark/icons/disabled_breakpoint_14px.svg
- src/plugins/debugger/interface/breakpointitem.cpp
- src/plugins/debugger/interface/breakpointview.cpp
- src/plugins/debugger/interface/breakpointview.h
- src/plugins/debugger/light/icons/breakpoint_14px.svg
- src/plugins/debugger/light/icons/disabled_breakpoint_14px.svg
- src/plugins/debugger/resource.qrc
- src/tools/debugadapter/debugger/gdbmi/gdbdebugger.cpp
- src/tools/debugadapter/debugmanager.cpp
Replace/Optimize Breakpoint-related Interfaces
> feat: [debugger] Replace/Optimize Breakpoint-related Interfaces

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
- src/plugins/project/mainframe/projecttree.cpp
> translations: translations

- README.md
Log:
Change-Id: I39c84f2c4633a75af45133b7f9ed3fcfd942b9d1
> doc: readme changed

- src/plugins/debugger/dap/dapdebugger.cpp
- src/plugins/debugger/dap/dapdebugger.h
- src/plugins/debugger/dap/debugsession.cpp
Optimize interaction of debugger
> feat: [debugger]  Optimize interaction of debugger

- src/plugins/core/locator/popupwidget.cpp
- src/plugins/debugger/dap/dapdebugger.cpp
- src/plugins/debugger/interface/breakpointmodel.cpp
- src/plugins/debugger/interface/breakpointmodel.h
- src/plugins/debugger/interface/breakpointview.cpp
- src/plugins/debugger/interface/stackframemodel.cpp
- src/plugins/debugger/interface/stackframeview.cpp
- src/plugins/debugger/interface/stackframeview.h
> feat: update TreeView delegate

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
- src/common/util/eventdefinitions.h
- src/plugins/codeeditor/codeeditor.cpp
- src/plugins/codegeex/codegeex.cpp
- src/plugins/core/find/findtoolbar.cpp
- src/plugins/cxx/cxxplugin.cpp
- src/plugins/java/javaplugin.cpp
- src/plugins/option/optioncore/mainframe/optionsdialog.cpp
- src/plugins/option/optioncore/optioncore.cpp
- src/plugins/python/python/project/properties/configpropertywidget.cpp
- src/plugins/python/python/project/pythonprojectgenerator.cpp
- src/plugins/python/pythonplugin.cpp
- src/services/option/optiondatastruct.h
- src/services/option/optionservice.h
modifyed interface of optionservice
> feat: [option] modifyed interface of optionservice

- src/plugins/codeeditor/codeeditor.cpp
> fix:  error icon

- src/plugins/core/gui/navigationbar.cpp
- src/plugins/core/gui/workspacewidget.cpp
> feat: [ui] optimized ui

- src/plugins/commandproxy/commandproxy.json
- src/plugins/filebrowser/filebrowser.json
- src/plugins/find/findplugin.json
- src/plugins/symbol/symbol.json
- src/plugins/template/templateplugin.json
Log:
Change-Id: Iac79476c9e34de67adbce8e5104bfc6fa489623c
> chore: change plugin's category

- src/plugins/debugger/dap/dapdebugger.cpp
- src/plugins/debugger/interface/localtreeitem.cpp
watch data has not update VarList after clear it
> fix: [debugger] watch data has not update VarList after clear it

- src/plugins/core/uicontroller/controller.cpp
Log: UI modified
Bug: https://pms.uniontech.com/bug-view-240605.html
> fix: UI modified

- src/plugins/recent/mainframe/recentdisplay.cpp
Log: [recent] UI modified
Bug: https://pms.uniontech.com/bug-view-240545.html
> fix: [recent] UI modified

- src/common/actionmanager/actionmanager.cpp
Log:
Change-Id: I10a817295d3d90b5a283a177c9d28cdd302125da
> fix: [common] resolve runtime warning

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
- src/plugins/codegeex/codegeexmanager.cpp
- src/plugins/codegeex/codegeexmanager.h
- src/plugins/codegeex/data/messagedata.cpp
- src/plugins/codegeex/widgets/askpagewidget.cpp
- src/plugins/codegeex/widgets/askpagewidget.h
- src/plugins/codegeex/widgets/codeeditcomponent.cpp
- src/plugins/codegeex/widgets/codeeditcomponent.h
- src/plugins/codegeex/widgets/codegeexwidget.cpp
- src/plugins/codegeex/widgets/intropage.cpp
- src/plugins/codegeex/widgets/messagecomponent.cpp
- src/plugins/codegeex/widgets/translationpagewidget.cpp
> feat: [codegeex] update ui of askpage

- src/plugins/reversedebug/loadcoredialog.cpp
Log: [reversedebug] UI modified
Bug: https://pms.uniontech.com/bug-view-242457.html
> fix: [reversedebug] UI modified

- src/common/dialog/propertiesdialog.cpp
- src/common/widget/configurewidget.cpp
- src/plugins/cxx/cmake/project/properties/bulidCfgWidget/buildpropertypage.cpp
- src/plugins/cxx/cmake/project/properties/bulidCfgWidget/stepspane.cpp
fix bug of propertyDialog`s ui
> fix: [property] fix bug of propertyDialog`s ui

- src/plugins/codeeditor/gui/private/texteditor_p.cpp
> fix: [editor] Fix ToolTip font color issue

- src/plugins/reversedebug/loadcoredialog.cpp
Log: [reversedebug] UI && UI logic modified
Bug: https://pms.uniontech.com/bug-view-242461.html
> fix: [reversedebug] UI && UI logic modified

- src/plugins/codegeex/widgets/messagecomponent.cpp
Log:
Change-Id: I050dffef4685b57221ecfa51fb73294637ee0896
> fix: [codegeex] display issue

- src/plugins/builder/mainframe/buildmanager.cpp
- src/plugins/codeeditor/codelens/codelens.cpp
- src/plugins/find/findtoolwindow.cpp
- src/plugins/valgrind/mainframe/valgrindbar.cpp
Log: [buildercore][codeeditor][find][valgrind] UI modified
Bug: https://pms.uniontech.com/bug-view-240473.html
> fix: [buildercore][codeeditor][find][valgrind] UI modified

- src/plugins/cxx/cmake/project/cmakeprojectgenerator.cpp
- src/plugins/cxx/cmake/project/properties/bulidCfgWidget/buildpropertypage.cpp
- src/plugins/cxx/cmake/project/properties/bulidCfgWidget/buildpropertypage.h
- src/plugins/cxx/cmake/project/properties/cmakeCfgWidget/cmakeitemdelegate.cpp
- src/plugins/cxx/cmake/project/properties/cmakeCfgWidget/cmakeitemdelegate.h
- src/plugins/cxx/cmake/project/properties/cmakeCfgWidget/cmakeitemmodel.cpp
- src/plugins/cxx/cmake/project/properties/cmakeCfgWidget/cmakeitemmodel.h
- src/plugins/cxx/cmake/project/properties/cmakeCfgWidget/cmakepropertypage.cpp
- src/plugins/cxx/cmake/project/properties/cmakeCfgWidget/cmakepropertypage.h
> feat: [cmake] add configuration of cmake

- src/plugins/codegeex/widgets/askpagewidget.cpp
ui modified
Bug: https://pms.uniontech.com/bug-view-241757.html
> fix: [codegeex] ui modified

- src/plugins/binarytools/mainframe/environmentview.cpp
- src/plugins/binarytools/mainframe/environmentview.h
can`t add config item
bug: https://pms.uniontech.com/bug-view-246899.html
> fix: [binarytools] can`t add config item

- src/common/widget/outputpane.cpp
wrong state of copy action
bug: https://pms.uniontech.com/bug-view-246821.html
> fix: [outputpane] wrong state of copy action

- debian/control
- src/plugins/core/CMakeLists.txt
- src/plugins/core/gui/plugindetailsview.cpp
- src/plugins/core/gui/plugindetailsview.h
webengine not valid on some platforms, not build it to resolve the issue.
Log:
Change-Id: I6d0379bfe972698d59eaf82a8dea4a028c94389a
> chore: [core] add build condition whether use webengine

- src/plugins/core/CMakeLists.txt
Log:
Change-Id: Ieba6112a648adbd6fe34279367b971804607d567
> fix: [core] remove webengine depend

- debian/changelog
Log:
Change-Id: I9e80b922d3bcbbbd191b70b4102767ea28127565
> tag: update to 1.2.18

- src/plugins/codeeditor/gui/completion/codecompletiondelegate.cpp
- src/plugins/codeeditor/gui/completion/codecompletionextendwidget.cpp
Log:
Change-Id: Iaad8a35f730a19fa7af5db206ffcb10c554d6362
> chore: [editor] optimize completion code color

- src/common/widget/outputpane.cpp
- src/common/widget/outputpane.h
- src/plugins/builder/CMakeLists.txt
- src/plugins/builder/mainframe/builderwidget.cpp
- src/plugins/builder/mainframe/builderwidget.h
- src/plugins/builder/mainframe/buildmanager.cpp
- src/plugins/builder/tasks/taskdelegate.cpp
- src/plugins/codeeditor/codelens/codelens.cpp
- src/plugins/find/findtoolwindow.cpp
According to the design drawing, modified font, widget position, and icon position in the issue list
> fix: [buildercore] UI modified

- src/plugins/codeeditor/codeeditor.cpp
- src/plugins/codeeditor/gui/tabwidget.cpp
- src/plugins/codeeditor/gui/tabwidget.h
- src/plugins/codeeditor/gui/workspacewidget.cpp
- src/plugins/codeeditor/gui/workspacewidget.h
- src/plugins/core/uicontroller/controller.cpp
- src/plugins/core/uicontroller/mainwindow.cpp
- src/plugins/core/uicontroller/mainwindow.h
- src/plugins/git/CMakeLists.txt
- src/plugins/git/client/gitclient.cpp
- src/plugins/git/client/gitclient.h
- src/plugins/git/constants.h
- src/plugins/git/git.cpp
- src/plugins/git/gui/gitbasewidget.h
- src/plugins/git/gui/giteditor.cpp
- src/plugins/git/gui/giteditor.h
- src/plugins/git/gui/gitlogwidget.cpp
- src/plugins/git/gui/gitlogwidget.h
- src/plugins/git/gui/gittabwidget.cpp
- src/plugins/git/gui/gittabwidget.h
- src/plugins/git/transceiver/gitreceiver.cpp
- src/plugins/git/utils/codeformathandler.cpp
- src/plugins/git/utils/codeformathandler.h
- src/plugins/git/utils/gitmenumanager.cpp
- src/plugins/git/utils/gitmenumanager.h
- src/services/editor/editorservice.h
- src/services/window/windowservice.h
Add git log for current displyed file
Log: git log
> feat: [git] Git log of current file

- src/plugins/option/optioncore/mainframe/shortcutsettingwidget.cpp
- src/plugins/option/optioncore/mainframe/shortcutsettingwidget.h
Log: Fixed a logic issue with shortcut keys in global Settings
Bug: https://pms.uniontech.com/bug-view-246773.html
> fix: [option] fixed shortcut repeated problem  in global settings

- src/plugins/git/client/gitclient.cpp
- src/plugins/git/client/gitclient.h
- src/plugins/git/constants.h
- src/plugins/git/gui/gitbasewidget.h
- src/plugins/git/gui/gitblamewidget.cpp
- src/plugins/git/gui/gitblamewidget.h
- src/plugins/git/gui/gittabwidget.cpp
- src/plugins/git/highlighter/basehighlighter.cpp
- src/plugins/git/highlighter/basehighlighter.h
- src/plugins/git/highlighter/gitblamehighlighter.cpp
- src/plugins/git/highlighter/gitblamehighlighter.h
- src/plugins/git/utils/gitmenumanager.cpp
- src/plugins/git/utils/gitmenumanager.h
Added display of 'git blame' information for current file
Log: git blame
> feat: [git] Git blame for current file

- src/plugins/builder/mainframe/buildmanager.cpp
- src/plugins/builder/mainframe/problemoutputpane.cpp
- src/plugins/builder/mainframe/problemoutputpane.h
- src/plugins/builder/tasks/taskdelegate.cpp
- src/plugins/builder/tasks/taskmanager.cpp
- src/plugins/builder/tasks/taskmanager.h
- src/plugins/builder/tasks/taskmodel.cpp
- src/plugins/builder/tasks/taskmodel.h
Log: added the filter (all, error, warning) in the issue list. It can filter message by combox.
> feat: [builder] added the filter in issue list

- src/plugins/cxx/cmake/project/cmakeprojectgenerator.cpp
- src/plugins/cxx/cmake/project/cmakeprojectgenerator.h
Added a new right-click action, which can remove the cmakecaches and cmakefiles
> feat: [cxx] clear cmake configuration

- src/plugins/filebrowser/mainframe/filetreeview.cpp
- src/plugins/filebrowser/mainframe/filetreeview.h
Bug: https://pms.uniontech.com/bug-view-245767.html
> fix: [filebrowser] the name of new files and and folders cannot be customized

- 3rdparty/cppdap/src/network.cpp
- src/base/abstractdebugger.h
- src/plugins/debugger/dap/dapdebugger.cpp
- src/plugins/debugger/dap/dapdebugger.h
- src/plugins/debugger/dap/debugsession.cpp
- src/plugins/debugger/dap/debugsession.h
- src/plugins/debugger/debuggerglobals.h
- src/plugins/debugger/debugmanager.cpp
- src/plugins/debugger/debugmanager.h
- src/plugins/debugger/interface/menumanager.cpp
- src/plugins/debugger/interface/menumanager.h
- src/plugins/debugger/remotedebug/remotedebugdlg.cpp
- src/plugins/debugger/remotedebug/remotedebugdlg.h
- src/plugins/javascript/debugger/jsdebugger.cpp
- src/plugins/javascript/debugger/jsdebugger.h
- src/services/window/windowelement.h
support incomplete function of remote debug
> feat: [debugger] remote debug

- src/common/inotify/private/inotify_linux.h
- src/plugins/codeeditor/gui/workspacewidget.cpp
- src/plugins/git/client/gitclient.cpp
- src/plugins/git/client/gitclient.h
- src/plugins/git/constants.h
- src/plugins/git/gui/gitbasewidget.h
- src/plugins/git/gui/gitblamewidget.cpp
- src/plugins/git/gui/gitblamewidget.h
- src/plugins/git/gui/gitdiffwidget.cpp
- src/plugins/git/gui/gitdiffwidget.h
- src/plugins/git/gui/giteditor.cpp
- src/plugins/git/gui/giteditor.h
- src/plugins/git/gui/gitlogwidget.cpp
- src/plugins/git/gui/gitlogwidget.h
- src/plugins/git/gui/gittabwidget.cpp
- src/plugins/git/gui/gittabwidget.h
- src/plugins/git/handler/abstracttextcursorhandler.cpp
- src/plugins/git/handler/abstracttextcursorhandler.h
- src/plugins/git/handler/changetextcursorhandler.cpp
- src/plugins/git/handler/changetextcursorhandler.h
- src/plugins/git/utils/differ.cpp
- src/plugins/git/utils/differ.h
- src/plugins/git/utils/diffutils.cpp
- src/plugins/git/utils/diffutils.h
- src/plugins/git/utils/gitmenumanager.cpp
- src/plugins/git/utils/gitmenumanager.h
Add feature of git diff for current file
Log: Git diff
> feat: [Git] Git diff for current file

- src/plugins/git/client/gitclient.cpp
- src/plugins/git/constants.h
- src/plugins/git/gui/gitbasewidget.h
- src/plugins/git/gui/gitblamewidget.cpp
- src/plugins/git/gui/gitblamewidget.h
- src/plugins/git/gui/gitdiffwidget.cpp
- src/plugins/git/gui/gitdiffwidget.h
- src/plugins/git/gui/gitlogwidget.cpp
- src/plugins/git/gui/gitlogwidget.h
- src/plugins/git/gui/gitshowwidget.cpp
- src/plugins/git/gui/gitshowwidget.h
- src/plugins/git/gui/gittabwidget.cpp
- src/plugins/git/gui/gittabwidget.h
- src/plugins/git/utils/gitcommand.cpp
- src/plugins/git/utils/gitcommand.h
Click commit id to view the commit information
Log: Git show
> feat: [Git] Git show for commit id

- src/plugins/project/mainframe/projecttree.cpp
- src/plugins/project/mainframe/projecttree.h
Bug: https://pms.uniontech.com/bug-view-249259.html
> fix: [project] Fixed an issue where the project could not be renamed

- src/plugins/cxx/cmake/project/cmakeasynparse.cpp
- src/plugins/cxx/ninja/project/ninjaprojectgenerator.cpp
- src/plugins/java/gradle/project/gradleprojectgenerator.cpp
- src/plugins/java/maven/project/mavenprojectgenerator.cpp
- src/plugins/project/mainframe/projectdelegate.cpp
- src/plugins/project/mainframe/projecttree.cpp
- src/plugins/python/python/project/pythonprojectgenerator.cpp
- src/services/project/projectservice.h
> feat: [projecttree] add spinner while parsing project

- src/plugins/codeeditor/gui/private/workspacewidget_p.h
- src/plugins/codeeditor/gui/workspacewidget.cpp
- src/plugins/git/client/gitclient.cpp
- src/plugins/git/client/gitclient.h
- src/plugins/git/constants.h
- src/plugins/git/gui/gitblamewidget.cpp
- src/plugins/git/gui/gitdiffwidget.cpp
- src/plugins/git/gui/gitlogwidget.cpp
- src/plugins/git/transceiver/gitreceiver.cpp
- src/plugins/git/transceiver/gitreceiver.h
- src/plugins/git/utils/gitmenumanager.cpp
- src/plugins/git/utils/gitmenumanager.h
1.Display git information for the project
2.Add git item for editor menu
> feat: [Git] Display git information for the project

- src/plugins/builder/mainframe/buildmanager.cpp
The filter implementation is optimized and the default selection are set
> fix: [builder] filter implementation method

- src/plugins/template/wizard/detailwidget.cpp
- src/plugins/template/wizard/maindialog.cpp
Bug: https://pms.uniontech.com/bug-view-240083.html
> fix: [template] ui modified in new files and new projects dialog

- src/common/widget/appoutputpane.cpp
- src/common/widget/appoutputpane.h
- src/common/widget/outputpane.cpp
- src/plugins/core/modules/contextmodule.cpp
> fix: [appoutputpane] can`t find in application output pane

- src/plugins/builder/tasks/taskdelegate.cpp
adjusted the ui problem in issue list
> fix: [builder] two lines of text appears in one line

- src/base/abstractlocator.h
- src/base/basefilelocator.cpp
- src/base/basefilelocator.h
- src/common/util/fileutils.cpp
- src/plugins/core/locator/popupwidget.cpp
> feat: [locator] optimized display of long file name

- src/plugins/reversedebug/loadcoredialog.cpp
Bug: https://pms.uniontech.com/bug-view-242457.html
> fix: [reversedebug] ui modified in reversedebug dialog

- src/plugins/recent/mainframe/recentdisplay.cpp
Bug: https://pms.uniontech.com/bug-view-240545.html
> fix: [recent] ui modified in recent display

- src/common/widget/appoutputpane.cpp
- src/common/widget/appoutputpane.h
- src/plugins/valgrind/mainframe/valgrindbar.cpp
Bug: https://pms.uniontech.com/bug-view-240473.html
> fix: [common] ui modified in appoutput pane and valgrind pane

- src/plugins/codegeex/codegeexmanager.cpp
> feat: [Ai] change api of ai plugin

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
- src/plugins/filebrowser/mainframe/filetreeview.cpp
- src/plugins/project/mainframe/projecttree.cpp
Bug: https://pms.uniontech.com/bug-view-254703.html, https://pms.uniontech.com/bug-view-254693.html,
https://pms.uniontech.com/bug-view-254691.html
> fix: [filebrowser,project] code translation and warning dialog modified

- src/plugins/cxx/cmake/project/properties/bulidCfgWidget/stepspane.cpp
Log: bug fix
Change-Id: I6e50e94bb721172dc733e5bb68cbd2b6315a2bfc
> fix: [cxx] build parameters wrong

- src/plugins/binarytools/binarytools.cpp
- src/plugins/binarytools/binarytools.h
- src/plugins/binarytools/configure/binarytoolsmanager.cpp
- src/plugins/binarytools/configure/binarytoolsmanager.h
- src/plugins/binarytools/mainframe/binarytoolsconfigview.cpp
- src/plugins/git/client/gitclient.cpp
- src/plugins/git/gui/gitdiffwidget.cpp
1.Add menu to execute tool
2.Fixed tool execution logic issue
3.Adjust the `git blame` time format
> fix: Fixed some issues

- src/plugins/binarytools/configure/binarytoolsmanager.cpp
- src/plugins/binarytools/configure/default_binarytools.json
> feat: add default tool

- src/plugins/binarytools/configure/binarytoolsmanager.h
- src/plugins/binarytools/mainframe/binarytoolsconfigview.cpp
> fix: Fix compilation issue

- src/plugins/find/findtoolwindow.cpp
ui modified in findtoolwindow
Bug: https://pms.uniontech.com/bug-view-255261.html
> fix: [find] ui modified

- src/plugins/cxx/cmake/project/properties/environmentwidget.cpp
Bug: https://pms.uniontech.com/bug-view-245895.html
> fix: [cxx] the settings cannot save in cxx project enviroment

- src/common/widget/appoutputpane.cpp
- src/common/widget/appoutputpane.h
- src/plugins/binarytools/configure/binarytoolsmanager.cpp
- src/plugins/binarytools/configure/binarytoolsmanager.h
- src/plugins/codeeditor/gui/completion/codecompletionmodel.cpp
- src/plugins/core/modules/contextmodule.cpp
- src/plugins/debugger/runner/runner.cpp
Optimize the output information of the tool
> feat: [tool] Optimize the output information of the tool

- src/plugins/codeeditor/gui/private/texteditor_p.cpp
- src/plugins/codeeditor/gui/private/texteditor_p.h
- src/plugins/codeeditor/gui/settings/commentconfigdetailwidget.cpp
- src/plugins/codeeditor/gui/settings/commentconfigwidget.cpp
- src/plugins/codeeditor/gui/settings/editorsettings.cpp
- src/plugins/codeeditor/gui/settings/editorsettings.h
- src/plugins/codeeditor/gui/settings/editorsettingswidget.cpp
- src/plugins/codeeditor/gui/tabwidget.cpp
- src/plugins/codeeditor/gui/tabwidget.h
- src/plugins/codeeditor/gui/texteditor.cpp
- src/plugins/codeeditor/gui/texteditor.h
> fix: [codeeditor] optimized the comment feature

- src/plugins/core/uicontroller/controller.cpp
- src/plugins/core/uicontroller/controller.h
- src/services/window/windowservice.h
1.add interface of remove item by action
2.add interface of update item by new action
> feat: [controller] add interface of toptoolitem

- src/plugins/codeeditor/gui/settings/commentconfigwidget.cpp
- src/plugins/codeeditor/gui/settings/editorsettings.cpp
- src/plugins/codeeditor/gui/texteditor.cpp
Log: add single-line comment without selected, ui modified
> fix: [codeeditor] comment logic && ui modified

- src/plugins/project/mainframe/projecttree.cpp
> fix: [project] can`t create new document in root of projectTree

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
- src/plugins/codeeditor/gui/settings/commentconfigdetailwidget.cpp
- src/plugins/codeeditor/gui/settings/commentconfigdetailwidget.h
- src/plugins/codegeex/option/detailwidget.cpp
- src/plugins/java/gradle/project/properties/gradleconfigpropertywidget.cpp
- src/plugins/java/java/option/jdkwidget.cpp
- src/plugins/java/maven/project/properties/mavenconfigpropertywidget.cpp
translated code in codeeditor, binarytools and so on
> fix: code translation

- src/plugins/binarytools/configure/binarytoolsmanager.cpp
- src/plugins/binarytools/configure/binarytoolsmanager.h
> fix: Fixed multi-thread resource contention issue

- debian/changelog
Log:
Change-Id: Iee70d098e7776388cb47a9088dc2711d1c286b7c
> tag: update to 1.3.0

- 3rdparty/unioncode-qscintilla214/src/qscicommandset.cpp
- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
- src/plugins/codeeditor/gui/settings/commentconfigwidget.cpp
- src/plugins/codeeditor/gui/settings/editorsettings.cpp
- src/plugins/codeeditor/gui/tabwidget.cpp
- src/plugins/codeeditor/gui/workspacewidget.cpp
Log: fixed some issues in codeeditor, add comment shortcut label
> fix: [codeeditor] can't save config && code translation

- src/common/util/eventdefinitions.h
- src/plugins/codeeditor/gui/private/texteditor_p.cpp
- src/plugins/codeeditor/gui/texteditor.cpp
- src/plugins/codeeditor/gui/texteditor.h
- src/plugins/debugger/breakpoint.h
- src/plugins/debugger/dap/dapdebugger.cpp
- src/plugins/debugger/dap/dapdebugger.h
- src/plugins/debugger/dap/debugmodel.cpp
- src/plugins/debugger/dap/debugmodel.h
- src/plugins/debugger/dap/debugservice.cpp
- src/plugins/debugger/dap/debugservice.h
- src/plugins/debugger/dap/debugsession.cpp
- src/plugins/debugger/interface/breakpointitem.cpp
- src/plugins/debugger/interface/breakpointitem.h
- src/plugins/debugger/interface/breakpointmodel.cpp
- src/plugins/debugger/interface/breakpointmodel.h
- src/plugins/debugger/interface/breakpointview.cpp
- src/plugins/debugger/interface/breakpointview.h
- src/tools/debugadapter/dapproxy.h
- src/tools/debugadapter/dapsession.cpp
- src/tools/debugadapter/debugger/debugger.h
- src/tools/debugadapter/debugger/gdbmi/gdbdebugger.cpp
- src/tools/debugadapter/debugger/gdbmi/gdbdebugger.h
- src/tools/debugadapter/debugger/javascript/jsdebugger.cpp
- src/tools/debugadapter/debugger/javascript/jsdebugger.h
- src/tools/debugadapter/debugmanager.cpp
- src/tools/debugadapter/debugmanager.h
support add contion to breakpoint by right-click menu
> feat: [debugger] add interface of Conditional Breakpoint

- src/plugins/cxx/cmake/project/properties/bulidCfgWidget/stepspane.cpp
Log:
Change-Id: If4bb1a3d0c9cd0d2276aa8723c4aceff71627050
> fix: [cxx] build parameter wrong work

- src/plugins/codeeditor/gui/workspacewidget.cpp
Log: used the ScrollArea
Bug: https://pms.uniontech.com/bug-view-246251.html
> fix: [codeeditor] Double shadows appear in the left and right columns

- src/plugins/console/console.json
- src/plugins/cxx/cxxplugin.json
- src/plugins/git/git.json
- src/plugins/java/javaplugin.json
- src/plugins/javascript/javascriptplugin.json
- src/plugins/python/pythonplugin.json
> fix: updated the website

- src/plugins/builder/CMakeLists.txt
- src/plugins/builder/tasks/taskdelegate.cpp
- src/plugins/builder/tasks/taskdelegate.h
- src/plugins/builder/tasks/taskfilterproxymodel.cpp
- src/plugins/builder/tasks/taskfilterproxymodel.h
- src/plugins/builder/tasks/taskmanager.cpp
- src/plugins/builder/tasks/taskmanager.h
Log: added the proxy filter model
> fix: [builder] the filter can't update in time

- src/plugins/cxx/cxxplugin.json
- src/plugins/java/javaplugin.json
- src/plugins/javascript/javascriptplugin.json
- src/plugins/python/pythonplugin.json
> fix: update c/c++ python java javascript website

- src/common/util/eventdefinitions.h
- src/plugins/binarytools/configure/binarytoolsmanager.cpp
- src/plugins/binarytools/configure/binarytoolsmanager.h
- src/plugins/binarytools/configure/default_binarytools.json
- src/plugins/binarytools/constants.h
- src/plugins/binarytools/event/eventreceiver.cpp
- src/plugins/binarytools/event/eventreceiver.h
- src/plugins/binarytools/mainframe/advancedsettingsdialog.cpp
- src/plugins/binarytools/mainframe/advancedsettingsdialog.h
- src/plugins/binarytools/mainframe/binarytoolsconfigview.cpp
- src/plugins/binarytools/models/binarytoolsmodel.cpp
- src/plugins/codeeditor/gui/texteditor.cpp
1.Missing hint
2.Install command
3.Trigger event
4.Config update
> feat: [tool] Advance Setting

- src/plugins/core/find/findtoolbar.cpp
- src/plugins/core/find/findtoolbar.h
> feat: [find] Added find shortcut keys

- src/plugins/debugger/dap/dapdebugger.cpp
- src/plugins/debugger/dap/dapdebugger.h
- src/plugins/debugger/interface/localtreemodel.cpp
- src/tools/debugadapter/dapsession.cpp
- src/tools/debugadapter/debugger/debugger.h
- src/tools/debugadapter/debugger/gdbmi/gdbdebugger.cpp
- src/tools/debugadapter/debugger/gdbmi/gdbdebugger.h
- src/tools/debugadapter/debugger/javascript/jsdebugger.cpp
- src/tools/debugadapter/debugger/javascript/jsdebugger.h
- src/tools/debugadapter/debugmanager.cpp
- src/tools/debugadapter/debugmanager.h
> feat: [debugger] Add Variable Monitoring Feature

- src/plugins/codegeex/codegeex/copilotapi.cpp
- src/plugins/codegeex/codegeex/copilotapi.h
- src/plugins/codegeex/copilot.cpp
1.update api
2.modified file type param
> fix: [codegeex] update some issues of ai

- src/common/util/macroexpander.cpp
- src/common/util/macroexpander.h
- src/common/widget/variablechooser.cpp
- src/common/widget/variablechooser.h
- src/plugins/binarytools/configure/binarytoolsmanager.cpp
- src/plugins/binarytools/configure/binarytoolsmanager.h
- src/plugins/binarytools/configure/default_binarytools.json
- src/plugins/binarytools/mainframe/binarytoolsconfigview.cpp
- src/plugins/codeeditor/codeeditor.cpp
1.Add macro support
2.Add spell check tool
> feat: [tool] Add spell check tool

- src/plugins/codeeditor/gui/private/tabwidget_p.h
- src/plugins/codeeditor/gui/private/texteditor_p.cpp
- src/plugins/codeeditor/gui/tabwidget.cpp
- src/plugins/codeeditor/gui/texteditor.cpp
- src/plugins/codeeditor/gui/texteditor.h
Fixed an issue where text could not be dragged and dropped in the editor
> fix: [editor] Fixed an issue where text could not be dragged and dropped in the editor

- src/plugins/core/gui/plugindetailsview.cpp
Log:
Change-Id: I841daf849b11d71653e2152a838ef19919b1d4f2
> fix: [core] guide show wrong

- src/common/lsp/client/client.cpp
- src/common/lsp/client/client.h
- src/common/lsp/protocol/new/basicjsonstructures.h
- src/common/lsp/protocol/new/languagefeatures.cpp
- src/plugins/codeeditor/codeeditor.cpp
- src/plugins/codeeditor/lsp/lspstyle.cpp
- src/plugins/codeeditor/lsp/lspstyle.h
- src/plugins/codeeditor/utils/editorutils.cpp
- src/plugins/codeeditor/utils/editorutils.h
Add `Range Formatting` for editor
> feat: [editor] Add `Range Formatting` for editor

- src/common/util/eventdefinitions.h
- src/plugins/codeeditor/gui/private/texteditor_p.cpp
- src/plugins/debugger/dap/dapdebugger.cpp
- src/plugins/debugger/dap/dapdebugger.h
- src/plugins/debugger/debugmanager.cpp
- src/services/debugger/debuggerservice.h
- src/tools/debugadapter/dapsession.cpp
- src/tools/debugadapter/debugger/debugger.h
- src/tools/debugadapter/debugger/gdbmi/gdbdebugger.cpp
- src/tools/debugadapter/debugger/gdbmi/gdbdebugger.h
- src/tools/debugadapter/debugger/javascript/jsdebugger.cpp
- src/tools/debugadapter/debugger/javascript/jsdebugger.h
- src/tools/debugadapter/debugmanager.cpp
- src/tools/debugadapter/debugmanager.h
log: when debugger started, you can right-click on the breakpoint margin and select ‘Jump to Line’ to navigate to a specific line.
> feat: [debugger] add "jump" function

- src/plugins/binarytools/configure/binarytoolsmanager.cpp
- src/plugins/binarytools/configure/binarytoolsmanager.h
- src/plugins/binarytools/configure/default_binarytools.json
- src/plugins/binarytools/constants.h
- src/plugins/binarytools/mainframe/advancedsettingsdialog.cpp
- src/plugins/binarytools/mainframe/binarytoolsconfigview.cpp
- src/plugins/codeeditor/codeeditor.cpp
- src/plugins/codeeditor/codeeditor.h
- src/plugins/codeeditor/gui/tabwidget.cpp
- src/plugins/codeeditor/gui/tabwidget.h
- src/plugins/codeeditor/gui/workspacewidget.cpp
- src/plugins/codeeditor/gui/workspacewidget.h
- src/services/editor/editorservice.h
Add `clang-format` tool for formatting current document
> feat: [tool] Add `clang-format` tool

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
- src/plugins/binarytools/configure/binarytoolsmanager.cpp
- src/plugins/binarytools/configure/binarytoolsmanager.h
- src/plugins/find/CMakeLists.txt
- src/plugins/find/constants.h
- src/plugins/find/findtoolwindow.cpp
- src/plugins/find/findtoolwindow.h
- src/plugins/find/searchresultwindow.cpp
- src/plugins/find/searchresultwindow.h
- src/plugins/find/util/searcreplacehworker.cpp
- src/plugins/find/util/searcreplacehworker.h
Optimize advanced search logic
> refactor: [search] Optimize advanced search logic

- src/base/CMakeLists.txt
- src/base/abstracteditwidget.cpp
- src/base/abstracteditwidget.h
- src/plugins/codeeditor/codeeditor.cpp
- src/plugins/codeeditor/gui/private/workspacewidget_p.h
- src/plugins/codeeditor/gui/workspacewidget.cpp
- src/plugins/codeeditor/gui/workspacewidget.h
- src/plugins/codeeditor/lexer/lexermanager.cpp
- src/plugins/codeeditor/lexer/lexermanager.h
- src/plugins/cxx/cxxplugin.cpp
- src/plugins/git/client/gitclient.cpp
- src/plugins/git/client/gitclient.h
- src/plugins/git/git.cpp
- src/plugins/git/gui/gittabwidget.cpp
- src/plugins/git/gui/gittabwidget.h
- src/plugins/git/utils/gitmenumanager.cpp
- src/plugins/git/utils/gitmenumanager.h
- src/plugins/python/pythonplugin.cpp
- src/services/editor/editorservice.h
Add shortcut key to close git window
> fix: [git] Fix git window closing issue

- src/plugins/find/findtoolwindow.cpp
- src/plugins/find/searchresultwindow.cpp
- src/plugins/find/util/searcreplacehworker.cpp
- src/plugins/git/gui/instantblamewidget.cpp
- src/plugins/git/gui/instantblamewidget.h
Click `Instant Blame` to jump to `Git show`
> feat: [git] Add click-response for `Instant Blame`

- src/plugins/codegeex/codegeex/askapi.cpp
- src/plugins/codegeex/codegeex/copilotapi.cpp
log： The content of the ‘data’ field is in JSON format, while the other fields are not.
> fix: [codeGeex] Fix the incorrect parsing method

- 3rdparty/unioncode-qscintilla214/src/qsciscintilla.cpp
- src/common/widget/variablechooser.cpp
- src/plugins/codeeditor/gui/private/texteditor_p.h
- src/plugins/codeeditor/gui/tabwidget.cpp
- src/plugins/codeeditor/gui/texteditor.cpp
- src/plugins/codeeditor/lsp/lspstyle.cpp
- src/tools/languageadapter/main.cpp
Optimized cursor forward and backward logic
Log: Feature optimization
> fix: [editor] Optimize the cursor history

- src/common/util/utils.h
- src/plugins/builder/mainframe/buildmanager.cpp
- src/plugins/core/uicontroller/controller.cpp
- src/plugins/core/uicontroller/mainwindow.cpp
- src/plugins/debugger/dap/dapdebugger.cpp
- src/services/window/windowelement.h
1.修复图标不清晰问题
2.修复和优化tooltip显示
3.修复关闭应用时崩溃问题
> 修复toolTip及崩溃问题

- src/common/widget/appoutputpane.cpp
> fix: [appoutputpane] incorrect display of toolbar

- src/plugins/cxx/cmake/project/cmakeprojectgenerator.cpp
- src/plugins/cxx/cmake/project/transceiver/projectcmakereceiver.cpp
- src/plugins/cxx/cmake/project/transceiver/projectcmakereceiver.h
- src/plugins/project/projectcore.cpp
- src/plugins/project/transceiver/projectcorereceiver.cpp
- src/plugins/project/transceiver/projectcorereceiver.h
only support cmake project for now. to open project`s property dialog quickly
log:
> feat: [project] enable `settings` button of project view

- src/common/widget/variablechooser.cpp
Log:
Change-Id: I521485acd3ad090eff3aafd06bb2034b7e2f6687
> fix: add missing header

- src/plugins/cxx/cmake/project/cmakeprojectgenerator.cpp
> fix: [project] can`t show run program propertys

- debian/changelog
Log:
Change-Id: I0314aa6776129ad06a9caa4f30926133aed1fcfa
> tag: update to 1.3.1

- src/plugins/cxx/cmake/project/cmakeasynparse.cpp
> feat: [project] add interface of cmakeFileLists

- src/plugins/codeeditor/gui/private/tabwidget_p.h
- src/plugins/codeeditor/gui/private/workspacewidget_p.h
- src/plugins/codeeditor/gui/recentopenlistview.cpp
- src/plugins/codeeditor/gui/recentopenlistview.h
- src/plugins/codeeditor/gui/recentopenwidget.cpp
- src/plugins/codeeditor/gui/recentopenwidget.h
- src/plugins/codeeditor/gui/tabwidget.cpp
- src/plugins/codeeditor/gui/tabwidget.h
- src/plugins/codeeditor/gui/workspacewidget.cpp
> feat: [codeeditor] ctrl + tab

- README.md
Log: readme changed
Change-Id: Iaac770cf41df1c7754bb61525aa4fcb58d459eea
> doc: [readme] remove unused content

- src/common/util/eventdefinitions.h
- src/plugins/builder/mainframe/buildmanager.cpp
- src/plugins/builder/mainframe/buildmanager.h
- src/plugins/builder/transceiver/builderreceiver.cpp
- src/plugins/cxx/cmake/project/transceiver/projectcmakereceiver.cpp
- src/plugins/debugger/dap/dapdebugger.cpp
- src/plugins/debugger/debugmanager.cpp
- src/plugins/debugger/runner/runner.cpp
- src/plugins/filebrowser/transceiver/filebrowserreceiver.cpp
- src/plugins/git/transceiver/gitreceiver.cpp
- src/plugins/project/transceiver/projectcorereceiver.cpp
- src/plugins/project/transceiver/sendevents.cpp
- src/plugins/symbol/transceiver/symbolreceiver.cpp
- src/plugins/valgrind/mainframe/valgrindrunner.cpp
- src/plugins/valgrind/transceiver/valgrindreceiver.cpp
> fix: [debugger] wrong debug state when activating project

- src/plugins/debugger/dap/dapdebugger.cpp
> fix: [debugger] havn`t update runstate when debugging python program

- src/plugins/core/gui/plugindetailsview.cpp
Log:
Change-Id: I8f9e36795800fe320ea30b1c05eec861fe26d97a
> fix: plugin detail view show incorrect

- src/plugins/codeeditor/codeeditor.cpp
- src/plugins/codeeditor/gui/workspacewidget.cpp
- src/plugins/codeeditor/status/editorlabel.cpp
- src/plugins/codeeditor/status/editorlabel.h
- src/plugins/codeeditor/status/statusinfomanager.cpp
- src/plugins/codeeditor/status/statusinfomanager.h
- src/plugins/codeeditor/transceiver/codeeditorreceiver.cpp
Added cursor information display
Log: Status bar cursor information
> feat: [statusbar] Added editor information display

- src/plugins/find/gui/findtoolwindow.cpp
- src/plugins/find/gui/findtoolwindow.h
fix issue of the case-sensitive button and full-words button
Log: fix issue
> fix: [UI] Fixed issue of UI

- src/plugins/cxx/cmake/project/properties/runCfgWidget/runconfigpane.cpp
Log:
Change-Id: I60883a7b519343f18298a788337587ed6cb70782
> chore: [cxx] enable target path editable

- src/plugins/codeeditor/gui/tabbar.cpp
- src/plugins/codeeditor/gui/tabwidget.cpp
- src/plugins/codeeditor/gui/tabwidget.h
as title
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-255827.html
> fix: [editor] The modified file cannot be saved when the tab page is closed

- src/plugins/codeeditor/gui/settings/behaviorwidget.cpp
- src/plugins/codeeditor/gui/settings/settingsdefine.h
- src/plugins/codeeditor/lsp/lspstyle.cpp
- src/plugins/codeeditor/lsp/private/lspstyle_p.h
added editor config, to manage tips active time
> fix: [codeeditor] editor tips time

- src/plugins/codegeex/widgets/codegeexwidget.cpp
- src/plugins/codegeex/widgets/translationpagewidget.cpp
> fix: [codegeex] Optimize Window Adjustment Strategy

- src/plugins/filebrowser/mainframe/filetreeview.cpp
Log: fix issues in [filebrowser]
> fix: [filebrowser] delete file when click X

- src/base/abstractdebugger.h
- src/plugins/cxx/cmake/cmakedebug.cpp
- src/plugins/debugger/dap/dapdebugger.cpp
- src/plugins/debugger/dap/dapdebugger.h
- src/plugins/debugger/debugmanager.cpp
- src/plugins/debugger/debugmanager.h
- src/plugins/debugger/interface/attachinfodialog.cpp
- src/plugins/debugger/interface/attachinfodialog.h
- src/plugins/debugger/interface/menumanager.cpp
- src/plugins/debugger/interface/menumanager.h
- src/plugins/javascript/debugger/jsdebugger.cpp
- src/plugins/javascript/debugger/jsdebugger.h
- src/services/window/windowelement.h
- src/tools/debugadapter/dapsession.cpp
- src/tools/debugadapter/debugger/gdbmi/gdbdebugger.cpp
> feat: [debugger] add functional of attach to running program

- src/plugins/binarytools/configure/binarytoolsmanager.cpp
- src/plugins/binarytools/configure/binarytoolsmanager.h
The application crashes when you run the same tool multiple times
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-259611.html
> fix: [tool] Fixed a crash issue when executing the tool

- src/plugins/binarytools/configure/default_binarytools.json
Update missing hint for the translate tool
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-259335.html
> fix: [tool] Update missing hint

- src/plugins/codeeditor/codeeditor.cpp
> fix: [codeedior] the buttons' ui display

- src/plugins/console/CMakeLists.txt
- src/plugins/console/console.cpp
- src/plugins/console/consolemanager.cpp
- src/plugins/console/consolemanager.h
- src/plugins/console/consolewidget.cpp
- src/plugins/console/consolewidget.h
> feat: [console] modified default path of console

- src/common/widget/outputpane.cpp
- src/common/widget/outputpane.h
Use the cache to schedule output
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-254727.html
> fix: [output] Fixed an issue where the application froze when too many logs were output

- src/plugins/cxx/cmake/project/transceiver/projectcmakereceiver.cpp
> fix: [project] incorrect execute program of cmake project

- src/common/dialog/propertiesdialog.cpp
- src/plugins/cxx/cmake/project/properties/bulidCfgWidget/buildpropertypage.cpp
- src/plugins/cxx/cmake/project/properties/environmentwidget.cpp
- src/plugins/cxx/cmake/project/properties/environmentwidget.h
- src/plugins/cxx/cmake/project/properties/runCfgWidget/runconfigpane.cpp
- src/plugins/cxx/cmake/project/properties/runCfgWidget/runpropertypage.cpp
- src/plugins/project/mainframe/projecttree.cpp
> fix: [project] environment settings of project can not save

- src/plugins/codeeditor/lsp/lspstyle.cpp
- src/plugins/codeeditor/lsp/private/lspstyle_p.h
> fix: [editor] Fixed the issue that LSP-related features were invalid for inactive projects

- src/plugins/codeeditor/gui/workspacewidget.cpp
> fix: [editor] Fixed an issue with incorrect prompt information

- src/plugins/filebrowser/mainframe/filetreeview.cpp
- src/plugins/filebrowser/mainframe/filetreeview.h
- src/plugins/filebrowser/transceiver/filebrowserreceiver.cpp
- src/plugins/filebrowser/transceiver/filebrowserreceiver.h
Folders precede files and are sorted by name in ascending order
Log: fix issue
> fix: [browser] Fix file sorting issue on file browser page

- src/plugins/python/python/project/properties/configpropertywidget.cpp
- src/plugins/python/python/pythondebug.cpp
1.Incorrectly obtained the default interpreter
2.Used the interpreter from global settings instead of the project-specific interpreter
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-259623.html
https://pms.uniontech.com/bug-view-259339.html
> fix: [python] issues of python

- src/plugins/codeeditor/gui/private/texteditor_p.cpp
- src/plugins/codeeditor/gui/private/texteditor_p.h
- src/plugins/codeeditor/gui/texteditor.cpp
- src/plugins/codeeditor/gui/texteditor.h
- src/plugins/codeeditor/lsp/lspstyle.cpp
- src/plugins/codeeditor/lsp/lspstyle.h
- src/plugins/codeeditor/lsp/private/lspstyle_p.h
> fix: [editor] Fixed an issue with abnormal cursor

- src/plugins/core/uicontroller/controller.cpp
> fix: [core] dividing line between the navigation bar and the dockwidge

- src/plugins/codeeditor/gui/private/tabbar_p.h
- src/plugins/codeeditor/gui/tabbar.cpp
modified the tabBar's background color
Log: ui modified
> fix: [codeeditor] tabBar background color

- src/plugins/core/modules/notificationmodule.cpp
- src/plugins/core/notify/gui/itemdelegate.cpp
- src/plugins/core/notify/gui/notificationcenterwidget.cpp
- src/plugins/core/notify/gui/notificationcenterwidget.h
- src/plugins/core/notify/gui/notificationlistview.h
- src/plugins/core/notify/notificationentity.cpp
- src/plugins/core/notify/notificationentity.h
- src/plugins/core/notify/notificationmanager.cpp
- src/plugins/core/notify/notificationmanager.h
- src/services/window/windowservice.h
Can respond to button events with callback functions
Log: Optimization notification
> feat: [notify] New notification interface

- assets/configures/language.support
- src/common/supportfile/language.cpp
- src/plugins/codeeditor/gui/private/texteditor_p.cpp
- src/plugins/codeeditor/lexer/lexermanager.cpp
as title
Log: Added support for bash file highlighting
> fix: [editor] Added support for bash file highlighting

- src/plugins/codeeditor/gui/texteditor.cpp
If the file does not have the write permission when saving the file, add a message
Log: fix issue
> fix: [editor] Added an error message when saving the file

- src/common/widget/outputpane.cpp
- src/common/widget/outputpane.h
> fix: [common] compile output text color issue while switching theme

- src/plugins/project/mainframe/projecttree.cpp
- src/plugins/project/mainframe/projecttree.h
- src/services/project/projectgenerator.cpp
- src/services/project/projectgenerator.h
> feat: [project] Add menu action of create new directory

- src/plugins/git/utils/gitmenumanager.cpp
- src/plugins/git/utils/gitmenumanager.h
as title
Log: Add git shortcut keys
> feat: [git] Add shortcut keys

- src/plugins/cxx/cmake/project/cmakeasynparse.cpp
- src/plugins/cxx/cmake/project/cmakeasynparse.h
- src/plugins/cxx/cmake/project/cmakeprojectgenerator.cpp
> feat: [cmake] Prompt the user when files within the project change

- src/plugins/cxx/lexer/scilexercpp.cpp
> fix: [editor] Fixed issue where invalid field font color was too light

- src/plugins/codeeditor/lsp/lspstyle.cpp
> fix: [editor] Fix code highlighting issue

- debian/control
- src/plugins/symbol/CMakeLists.txt
- src/plugins/symbol/symbol.cpp
- src/plugins/symbol/util/util.cpp
- src/plugins/symbol/util/util.h
> fix: [symbol] Fixed an issue where the symbol page had no content

- src/plugins/codeeditor/status/statusinfomanager.cpp
- src/plugins/find/util/searcreplacehworker.cpp
1.Fix program crash when file is opened
2.Fix program crash when advanced search
> fix: Fix program crash issue

- src/plugins/console/consolemanager.cpp
- src/plugins/console/consolemanager.h
> fix: [console] can't not create new terminal

- src/common/util/eventdefinitions.h
- src/plugins/cxx/cmake/project/cmakeprojectgenerator.cpp
- src/plugins/cxx/cmake/project/transceiver/projectcmakereceiver.cpp
- src/plugins/cxx/cmake/project/transceiver/projectcmakereceiver.h
- src/plugins/project/mainframe/projecttree.cpp
- src/plugins/project/mainframe/projecttree.h
- src/plugins/project/projectcore.cpp
- src/plugins/project/transceiver/sendevents.cpp
- src/plugins/project/transceiver/sendevents.h
- src/services/project/projectservice.h
> fix: [cxx] abnormal project view after running cmake

- src/plugins/project/mainframe/projecttree.cpp
> feat: [project] add `new dicreatory` action to project`s root

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
as title
Log: Update translations
> chore: [translation] Update translations

- CMakeLists.txt
Log:
Change-Id: I19213b875502981088258b7f5bd5d2b06483314b
> chore: remove unused comment

- src/plugins/valgrind/mainframe/valgrindrunner.cpp
> fix: [valgrind] Unable to run Valgrind properly

- src/plugins/find/util/searchreplaceworker.cpp
- src/plugins/find/util/searchreplaceworker_p.h
> fix: [search] Fixed an issue where advanced search caused the programto crash

- src/plugins/cxx/cmake/project/cmake.qrc
- src/plugins/cxx/cmake/project/cmakeasynparse.cpp
- src/plugins/cxx/cmake/project/icons/library_20px.svg
> fix: [icon] differed the exe icon and lib icon

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
- src/plugins/cxx/cmake/project/properties/runCfgWidget/runconfigpane.cpp
> fix: [cmake] Cannot specify the execution path for the application

- src/plugins/cxx/cmake/project/properties/bulidCfgWidget/buildpropertypage.cpp
- src/plugins/cxx/cmake/project/properties/environmentwidget.cpp
- src/plugins/cxx/cmake/project/properties/environmentwidget.h
- src/plugins/cxx/cmake/project/properties/runCfgWidget/runconfigpane.cpp
> fix: [cxx] modified the build environment ui

- src/plugins/cxx/cmake/project/cmakeprojectgenerator.cpp
> fix: [cmake] wrong project view when trigger cmake by change cmakelists

- src/plugins/core/gui/workspacewidget.cpp
- src/plugins/core/gui/workspacewidget.h
- src/plugins/core/uicontroller/controller.cpp
- src/plugins/core/uicontroller/mainwindow.cpp
> fix: [workspacewidget] wrong state of toolbutton

- 3rdparty/unioncode-qscintilla214/scintilla/src/Editor.cpp
- 3rdparty/unioncode-qscintilla214/scintilla/src/Editor.h
- src/common/lsp/client/client.cpp
- src/common/lsp/client/client.h
- src/common/lsp/client/private/client_p.h
- src/common/lsp/protocol/new/languagefeatures.h
- src/plugins/codeeditor/codeeditor.cpp
- src/plugins/codeeditor/codeeditor.h
- src/plugins/codeeditor/gui/texteditor.cpp
- src/plugins/codeeditor/gui/texteditor.h
- src/plugins/codeeditor/gui/workspacewidget.cpp
- src/plugins/codeeditor/gui/workspacewidget.h
- src/plugins/codeeditor/lsp/lspstyle.cpp
- src/plugins/codeeditor/lsp/lspstyle.h
- src/plugins/codeeditor/lsp/private/lspstyle_p.h
- src/plugins/codeeditor/symbol/symbollocator.cpp
- src/plugins/codeeditor/symbol/symbollocator.h
Fixed an issue where the cursor style was abnormal when using the mouse to define jumps in the same file
Log: fix issue
> fix: [editor] Fixed cursor style issue

- src/plugins/codeeditor/codelens/codelens.cpp
- src/plugins/codeeditor/codelens/codelens.h
- src/plugins/codeeditor/codelens/codelensdelegate.cpp
- src/plugins/codeeditor/codelens/codelensdelegate.h
- src/plugins/codeeditor/codelens/codelenstree.cpp
- src/plugins/codeeditor/codelens/codelenstree.h
- src/plugins/codeeditor/codelens/codelenstype.h
- src/plugins/codeeditor/lsp/lspstyle.cpp
1.Fixed a style issue when results are selected
2.Fixed an issue where clicking results would not jump after closing all editors
Log: fix issue
> fix: [codelens] Fixed some issues

- src/common/lsp/client/client.cpp
- src/common/lsp/client/client.h
- src/common/lsp/client/private/client_p.h
- src/common/lsp/protocol/protocol.h
- src/plugins/codeeditor/gui/private/texteditor_p.cpp
- src/plugins/codeeditor/lsp/lspstyle.cpp
- src/plugins/codeeditor/lsp/lspstyle.h
- src/plugins/codeeditor/lsp/private/lspstyle_p.h
> feat: [editor] Highlighted field references

- src/plugins/binarytools/configure/default_binarytools.json
as title
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-259333.html
> fix: Update tool information

- src/plugins/core/gui/plugindetailsview.cpp
- src/plugins/core/gui/pluginitemdelegate.cpp
- src/plugins/core/gui/pluginstorewidget.cpp
- src/plugins/core/modules/pluginmanagermodule.cpp
Log: fixed some ui issues in plugin
Bug: https://pms.uniontech.com/bug-view-258793.html
> fix: [plugin] modified ui

- src/plugins/java/CMakeLists.txt
- src/plugins/java/gradle/project/gradleprojectgenerator.cpp
- src/plugins/java/gradle/project/transceiver/projectgradlereciver.cpp
- src/plugins/java/gradle/project/transceiver/projectgradlereciver.h
- src/plugins/project/mainframe/projecttree.cpp
Bug: https://pms.uniontech.com/bug-view-255865.html
> fix: [gradle] cannot expand after building gradle

- assets/configures/unioncode.desktop
as title
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-260987.html
> fix: Fixed abnormal display of menu items in the dock

- src/plugins/codeeditor/gui/private/tabbar_p.h
- src/plugins/codeeditor/gui/private/texteditor_p.h
- src/plugins/codeeditor/gui/private/workspacewidget_p.h
- src/plugins/codeeditor/gui/tabbar.cpp
- src/plugins/codeeditor/gui/tabbar.h
- src/plugins/codeeditor/gui/tabwidget.cpp
- src/plugins/codeeditor/gui/tabwidget.h
- src/plugins/codeeditor/gui/texteditor.cpp
- src/plugins/codeeditor/gui/texteditor.h
- src/plugins/codeeditor/gui/workspacewidget.cpp
- src/plugins/symbol/symbol.cpp
as title
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-255827.html
> fix: [editor] Fixed an issue where the file save dialog could not be closed

- src/plugins/binarytools/binarytools.json
- src/plugins/codegeex/codegeex.json
- src/plugins/codeporting/codeporting.json
- src/plugins/collaborators/collaborators.json
- src/plugins/console/console.json
- src/plugins/cxx/cxxplugin.json
- src/plugins/git/git.json
- src/plugins/java/javaplugin.json
- src/plugins/javascript/javascriptplugin.json
- src/plugins/python/pythonplugin.json
- src/plugins/reversedebug/reversedebug.json
- src/plugins/valgrind/valgrind.json
> fix: [extensions] updated website

- src/plugins/collaborators/mainframe/svn/svnclientwidget.cpp
- src/plugins/debugger/interface/menumanager.cpp
Log: as title
bug: https://pms.uniontech.com/bug-view-255839.html
> fix: [shortcut] repeat shortcut

- debian/control
Log:
Change-Id: Id94743b68804a21e03deeb861be9069ea30da155
> chore: [control] remove npm depend

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
- src/plugins/codeeditor/gui/private/texteditor_p.cpp
Log: updated translation
Bug: https://pms.uniontech.com/bug-view-261509.html, https://pms.uniontech.com/bug-view-259621.html
> chore: [translation] updated translation

- src/plugins/debugger/interface/breakpointview.cpp
- src/plugins/debugger/interface/breakpointview.h
Log: as title
Bug: https://pms.uniontech.com/bug-view-259381.html
> fix: [debugger] can`t remove breakpoint when file closed

- src/plugins/git/client/gitclient.cpp
- src/plugins/git/client/gitclient.h
- src/plugins/git/gui/instantblamewidget.cpp
- src/plugins/git/gui/instantblamewidget.h
- src/plugins/git/transceiver/gitreceiver.cpp
> fix: [git] Fix the `Instant Blame` information display issue

- src/plugins/core/locator/popupwidget.cpp
> fix: [locator] display area of contens

- src/plugins/cxx/cmake/project/cmakeasynparse.cpp
> fix: [project] Incorrect path in tooltip

- src/plugins/core/gui/dockheader.cpp
- src/plugins/core/uicontroller/mainwindow.cpp
Log: fixed ui issues
Bug: https://pms.uniontech.com/bug-view-258781.html
> fix: [ui] dockwidget header ui issues

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
- src/plugins/codeeditor/gui/tabbar.cpp
- src/plugins/find/gui/findtoolwindow.cpp
- src/plugins/project/locator/allprojectfilelocator.h
- src/plugins/project/locator/currentprojectlocator.h
as title
Log: update translations
> chore: Update translations

- assets/templates/projects/qtconsoleapp/CMakeLists.txt
- assets/templates/projects/qtconsoleapp/main.cpp
- assets/templates/projects/qtconsoleapp/wizard.json
- assets/templates/templates.json
> feat: [templates] add template of Qt console

- src/common/lsp/protocol/protocol.h
- src/plugins/codeeditor/gui/completion/codecompletiondelegate.cpp
- src/plugins/codeeditor/gui/completion/codecompletionmodel.cpp
- src/plugins/codeeditor/gui/completion/codecompletionmodel.h
- src/plugins/codeeditor/gui/completion/codecompletionwidget.cpp
- src/plugins/codeeditor/gui/completion/codecompletionwidget.h
- src/tools/languageadapter/main.cpp
as title
Log: Optimize code completion logic
> perf: [editor] Optimize code completion logic

- src/plugins/codeeditor/gui/completion/codecompletionmodel.cpp
- src/plugins/codeeditor/gui/completion/codecompletionwidget.cpp
> fix: [editor] Fixed a complete item ordering issue

- src/plugins/cxx/cmake/cmakedebug.cpp
- src/tools/debugadapter/dapsession.cpp
- src/tools/debugadapter/debugmanager.cpp
- src/tools/debugadapter/debugmanager.h
> fix: [debugger] can`t use running environment to gdb

- src/plugins/codeeditor/gui/completion/codecompletionmodel.cpp
- src/plugins/codeeditor/gui/completion/codecompletionmodel.h
- src/plugins/codeeditor/gui/completion/codecompletionwidget.cpp
as title
Log: Optimize the ordering of complete items
> pref: [editor] Optimize the ordering of complete items

- src/plugins/codeeditor/lsp/lspstyle.cpp
> fix: [editor] Change the field highlight color

- debian/changelog
Log:
Change-Id: I1a4d1fcbcc97bede2cce0ee41a4217c0c66a318a
> tag: update to 1.3.4

- src/plugins/performance/performance.json
> chore: [web] updated website

- src/plugins/codeeditor/gui/recent/recentopenlistdelegate.cpp
missing namespace
Log:
Change-Id: Ifa6245b6950cd6927fca09b96f38927f759b1445
> fix: build faild on v23

- src/plugins/codeeditor/gui/tabbar.cpp
Log:
Change-Id: I67e383383af7cf9400d3dbb42d41f571b0ce762f
> fix: [codeeditor] missing namespace

- src/plugins/codeeditor/gui/tabbar.cpp
Log:
Change-Id: I4a4e54386dc291077e71188ffa3d6ed7ef78a92a
> fix: [codeeditor] replace desktopservice

- src/plugins/codeeditor/gui/completion/codecompletionmodel.cpp
- src/plugins/codeeditor/gui/private/texteditor_p.cpp
- src/plugins/codeeditor/gui/private/texteditor_p.h
- src/plugins/codeeditor/gui/settings/fontcolorwidget.cpp
- src/plugins/codeeditor/gui/texteditor.cpp
- src/plugins/codeeditor/gui/texteditor.h
- src/plugins/codeeditor/lsp/languageclienthandler.cpp
- src/plugins/codeeditor/lsp/languageclienthandler.h
- src/plugins/codeeditor/lsp/languageworker.cpp
- src/plugins/codeeditor/lsp/languageworker.h
- src/plugins/codeeditor/lsp/private/languageclienthandler_p.h
as title
Log: Code optimization
> pefer: [editor] Optimized field highlighting logic

- src/common/util/eventdefinitions.h
- src/plugins/codeeditor/gui/private/workspacewidget_p.h
- src/plugins/codeeditor/gui/workspacewidget.cpp
- src/plugins/codeeditor/gui/workspacewidget.h
- src/plugins/codeeditor/transceiver/codeeditorreceiver.cpp
- src/plugins/codeeditor/transceiver/codeeditorreceiver.h
- src/plugins/project/CMakeLists.txt
- src/plugins/project/mainframe/recent/recentopenlistdelegate.cpp
- src/plugins/project/mainframe/recent/recentopenlistdelegate.h
- src/plugins/project/mainframe/recent/recentopenlistview.cpp
- src/plugins/project/mainframe/recent/recentopenlistview.h
- src/plugins/project/mainframe/recent/recentopenwidget.cpp
- src/plugins/project/mainframe/recent/recentopenwidget.h
- src/plugins/project/projectcore.cpp
- src/plugins/project/projectcore.h
- src/plugins/project/transceiver/projectcorereceiver.cpp
- src/plugins/project/transceiver/projectcorereceiver.h
> feat: [project] open file widget

- src/plugins/recent/mainframe/recentdisplay.cpp
Log: fixed ui issues
Bug: https://pms.uniontech.com/bug-view-258539.html
> fix: [recent] recent page ui

- src/common/dialog/propertiesdialog.cpp
- src/common/widget/configurewidget.cpp
- src/plugins/core/gui/dockheader.cpp
- src/plugins/core/gui/plugindetailsview.cpp
- src/plugins/core/gui/pluginstorewidget.cpp
- src/plugins/cxx/cmake/project/properties/bulidCfgWidget/buildpropertypage.cpp
- src/plugins/cxx/cmake/project/properties/runCfgWidget/runconfigpane.cpp
- src/plugins/cxx/cmake/project/properties/runCfgWidget/runpropertypage.cpp
Log: fixed ui issues
Bug: https://pms.uniontech.com/bug-view-258789.html
> fix: [cxx] project property ui

- src/plugins/core/locator/locatormanager.cpp
- src/plugins/project/mainframe/projecttree.cpp
1. open in terminal
2.locator select all when trigger locator by shortcut
Log: as title
> fix: bugs in Feedback List

- src/plugins/cxx/cmake/project/cmakeasynparse.cpp
- src/plugins/project/mainframe/projecttree.cpp
> feat: [cmake] sort executable programs

- assets/configures/editorstyle_cpp.support
- src/base/CMakeLists.txt
- src/base/abstractinstaller.cpp
- src/base/abstractinstaller.h
- src/framework/lifecycle/plugindepend.h
- src/framework/lifecycle/pluginmetaobject.cpp
- src/framework/lifecycle/pluginmetaobject.h
- src/framework/lifecycle/private/pluginmanager_p.cpp
- src/framework/lifecycle/private/pluginmetaobject_p.h
- src/plugins/binarytools/configure/binarytoolsmanager.cpp
- src/plugins/console/console.cpp
- src/plugins/console/consolemanager.cpp
- src/plugins/console/consolemanager.h
- src/plugins/core/depend/aptinstaller.cpp
- src/plugins/core/depend/aptinstaller.h
- src/plugins/core/depend/dependencemanager.cpp
- src/plugins/core/depend/dependencemanager.h
- src/plugins/core/depend/pipinstaller.cpp
- src/plugins/core/depend/pipinstaller.h
- src/plugins/core/modules/dependencemodule.cpp
- src/plugins/core/modules/dependencemodule.h
- src/plugins/core/uicontroller/controller.cpp
- src/plugins/find/util/searchreplaceworker.cpp
- src/plugins/project/mainframe/projecttree.cpp
- src/plugins/python/pythonplugin.h
- src/plugins/python/pythonplugin.json
- src/services/terminal/terminalservice.h
- src/services/window/windowservice.h
> feat: [core] Optimized dependent installation

- src/common/util/eventdefinitions.h
- src/plugins/codegeex/codegeex.cpp
- src/plugins/core/uicontroller/controller.cpp
- src/plugins/core/uicontroller/controller.h
- src/plugins/core/uicontroller/mainwindow.cpp
- src/plugins/core/uicontroller/mainwindow.h
- src/plugins/project/projectcore.cpp
- src/plugins/project/transceiver/projectcorereceiver.cpp
- src/plugins/project/transceiver/projectcorereceiver.h
- src/services/window/windowservice.h
add interface of adjust dock`s size
log: as title
> feat: Adjust some interfaces in the uiController

- src/plugins/core/uicontroller/controller.cpp
> fix: [core] widget register to mode failed

- src/common/project/projectinfo.h
- src/common/widget/outputpane.cpp
- src/plugins/console/console.cpp
- src/plugins/console/consolemanager.cpp
- src/plugins/console/consolemanager.h
- src/plugins/console/consolewidget.cpp
- src/plugins/console/consolewidget.h
- src/plugins/core/depend/aptinstaller.cpp
- src/plugins/core/depend/pipinstaller.cpp
- src/plugins/core/uicontroller/controller.cpp
- src/plugins/cxx/cmake/cmakegenerator.cpp
- src/plugins/cxx/cmake/project/properties/configutil.cpp
- src/plugins/cxx/cmake/project/properties/configutil.h
- src/plugins/cxx/cmake/project/properties/runCfgWidget/runconfigpane.cpp
- src/plugins/cxx/cmake/project/properties/runCfgWidget/runpropertypage.cpp
- src/plugins/cxx/ninja/ninjagenerator.cpp
- src/plugins/debugger/runner/runner.cpp
- src/plugins/java/gradle/gradlegenerator.cpp
- src/plugins/java/maven/mavengenerator.cpp
- src/plugins/javascript/jsgenerator.cpp
- src/plugins/linglong/llgenerator.cpp
- src/plugins/python/python/project/properties/configpropertywidget.cpp
- src/plugins/python/python/project/properties/configutil.cpp
- src/plugins/python/python/project/properties/configutil.h
- src/plugins/python/python/pythongenerator.cpp
- src/services/language/languagegenerator.h
- src/services/terminal/terminalservice.h
1.run application which need receive user`s input in terminal 2.make output pane editable
log: as title
> feat: [runner] add functional of "Run In Terminal"

- src/plugins/core/uicontroller/mainwindow.cpp
- src/plugins/linglong/gui/mainframe.cpp
> fix: [linglong] ui of mainFrame

- src/common/dialog/propertiesdialog.cpp
- src/common/dialog/propertiesdialog.h
- src/plugins/cxx/cmake/project/cmakeprojectgenerator.cpp
- src/plugins/java/gradle/project/gradleprojectgenerator.cpp
- src/plugins/java/maven/project/mavenprojectgenerator.cpp
> fix: [common] added project name to project proerties

- src/plugins/binarytools/binarytools.json
- src/plugins/builder/buildercore.json
- src/plugins/codeeditor/codeeditor.json
- src/plugins/codegeex/codegeex.json
- src/plugins/codeporting/codeporting.json
- src/plugins/collaborators/collaborators.json
- src/plugins/commandproxy/commandproxy.json
- src/plugins/console/console.json
- src/plugins/core/core.json
- src/plugins/cxx/cxxplugin.json
- src/plugins/filebrowser/filebrowser.json
- src/plugins/find/findplugin.json
- src/plugins/git/git.json
- src/plugins/java/javaplugin.json
- src/plugins/javascript/javascriptplugin.json
- src/plugins/project/projectcore.json
- src/plugins/python/pythonplugin.json
- src/plugins/recent/recent.json
- src/plugins/reversedebug/reversedebug.json
- src/plugins/symbol/symbol.json
- src/plugins/template/templateplugin.json
- src/plugins/valgrind/valgrind.json
> chore: [copyright] update copyright

- src/common/util/hostsysteminfo.h
- src/common/util/oshelper.h
Provides an interface for system judgment
Log:
Change-Id: Ieb72050fb0bb820c0e1d3da32629b4838a26b7fb
> feat: [common/util] add os util class

- 3rdparty/unioncode-qscintilla214/src/qsciscintilla.cpp
- src/common/unilog.h
- src/plugins/codeeditor/gui/private/texteditor_p.h
- src/plugins/codeeditor/gui/texteditor.cpp
- src/plugins/core/depend/dependencemanager.cpp
- src/plugins/cxx/lexer/scilexercpp.cpp
1.Fixed issue where tips and menus displayed at the same time 2.Optimized the logic for determining whether the installation package is installed
> fix: Fixed an issue where prompts and menus were displayed at the same time

- src/plugins/core/gui/dockheader.cpp
- src/plugins/core/gui/dockheader.h
- src/plugins/core/gui/workspacewidget.cpp
- src/plugins/core/gui/workspacewidget.h
- src/plugins/core/uicontroller/controller.cpp
- src/plugins/core/uicontroller/controller.h
- src/plugins/core/uicontroller/mainwindow.cpp
- src/plugins/core/uicontroller/mainwindow.h
- src/services/window/windowservice.h
> feat: [core] Optimize the way to switch between widgets in the workspace

- src/common/util/eventdefinitions.h
- src/plugins/codeeditor/gui/private/texteditor_p.cpp
- src/plugins/codeeditor/gui/private/texteditor_p.h
- src/plugins/codeeditor/gui/texteditor.cpp
> fix: [editor] Fixed issue where breakpoint information was lost after reloading file

- src/plugins/linglong/project/llasynparse.cpp
> fix: [linglong] remove unused header file

- src/plugins/codeeditor/gui/private/texteditor_p.h
- src/plugins/codeeditor/gui/tabbar.cpp
- src/plugins/codeeditor/gui/texteditor.cpp
- src/plugins/codeeditor/lsp/languageclienthandler.cpp
- src/plugins/cxx/lexer/scilexercpp.cpp
- src/plugins/project/mainframe/projecttree.cpp
1.Fix inaccurate feature text
2.Optimize the cursor display style
> fix: Make the display description of some features uniform

- src/plugins/core/locator/popupwidget.cpp
> fix: [locator] adjust icon size

- assets/configures/unioncode.desktop
Change Text Editor to Deepin Union Code
Log:
Change-Id: Iad99660485f61fb68a4592cfd0d9baa7a9f5f770
> fix: App name show incorrect

- src/plugins/cxx/cmake/project/properties/configutil.h
- src/plugins/cxx/cmake/project/properties/environmentwidget.cpp
- src/plugins/cxx/cmake/project/properties/environmentwidget.h
> fix: [environment] remove "enable debug level" check

- src/plugins/cxx/cmake/builder/generator/cmakebuildergenerator.cpp
- src/plugins/cxx/cmake/project/properties/bulidCfgWidget/stepspane.cpp
- src/plugins/cxx/cmake/project/properties/configutil.cpp
> fix: [project] Incorrect parameters when executing clean

- src/plugins/cxx/cmake/project/properties/configutil.h
> fix: [project] Default not running in the terminal.

- src/app/main.cpp
use opengles instead to avoid this issue.
Log:
Change-Id: Id71c49d43a26278e0a74a0c06829f36638592d50
> fix: crash with opengl driver wrong

- src/common/widget/appoutputpane.cpp
- src/common/widget/outputpane.cpp
- src/common/widget/outputpane.h
> feat: [appoutputpane] add filter

- src/plugins/core/uicontroller/controller.cpp
- src/plugins/core/uicontroller/mainwindow.cpp
> feat: [core] save/restore mainWindow`s geometry

- src/plugins/binarytools/configure/binarytoolsmanager.cpp
- src/plugins/console/console.cpp
- src/plugins/console/consolemanager.cpp
- src/plugins/core/depend/aptinstaller.cpp
- src/plugins/core/depend/pipinstaller.cpp
- src/plugins/core/gui/loadingwidget.cpp
- src/plugins/debugger/runner/runner.cpp
- src/plugins/project/mainframe/projecttree.cpp
- src/services/window/windowelement.h
Change the `console` to `terminal`
Log: fix issue
> fix: Correct inaccurate content

- src/services/window/windowelement.h
> fix: [build] Fix inaccurate menu item name

- src/plugins/core/locator/popupwidget.cpp
> fix: [locator] incompletey display of locator

- 3rdparty/unioncode-qscintilla214/src/qsciscintilla.cpp
- src/plugins/codeeditor/gui/settings/fontcolorwidget.cpp
> fix: [editor] Fixed issue where the program crashed when zooming editor font

- src/plugins/binarytools/binarytools.json
- src/plugins/builder/buildercore.json
- src/plugins/codeeditor/codeeditor.json
- src/plugins/codegeex/codegeex.json
- src/plugins/codeporting/codeporting.json
- src/plugins/collaborators/collaborators.json
- src/plugins/commandproxy/commandproxy.json
- src/plugins/console/console.json
- src/plugins/core/uicontroller/controller.cpp
- src/plugins/cxx/cxxplugin.json
- src/plugins/filebrowser/filebrowser.json
- src/plugins/find/findplugin.json
- src/plugins/git/git.json
- src/plugins/java/javaplugin.json
- src/plugins/javascript/javascriptplugin.json
- src/plugins/linglong/linglong.json
- src/plugins/option/optioncore/optioncore.json
- src/plugins/performance/performance.json
- src/plugins/python/pythonplugin.json
- src/plugins/reversedebug/reversedebug.json
- src/plugins/symbol/symbol.json
- src/plugins/template/templateplugin.json
- src/plugins/valgrind/valgrind.json
use new website.
Log:
Change-Id: I3805005a09e6f5e4745c9a64caa34ef9bd4b7219
> fix: update urlLink in plugin meta file

- src/plugins/core/uicontroller/controller.cpp
> fix: [mainwindow] can not show DTK`s menu

- src/plugins/builder/mainframe/buildmanager.cpp
- src/plugins/builder/mainframe/buildmanager.h
- src/plugins/builder/transceiver/builderreceiver.cpp
- src/plugins/cxx/cmake/project/cmakeprojectgenerator.cpp
- src/plugins/project/mainframe/projectdelegate.cpp
- src/plugins/project/mainframe/projectdelegate.h
- src/plugins/project/mainframe/projecttree.cpp
- src/plugins/project/mainframe/projecttree.h
1.crash when close project while running cmake
2.spinner do not hide after closing the current building project 
3.Can not open another project after closing the current building project.
Log: as title
> fix: [project] Crashes/Display Issues Related to Project View

- src/plugins/cxx/cmake/project/cmakeprojectgenerator.cpp
- src/plugins/cxx/cmake/project/cmakeprojectgenerator.h
> fix: [cmake] incorrect use of fileWatcher

- src/plugins/java/javautil.cpp
> fix: [java] notify user when `javap` can`t find

- src/plugins/builder/mainframe/buildmanager.cpp
- src/plugins/builder/mainframe/buildmanager.h
- src/plugins/core/uicontroller/controller.cpp
- src/plugins/core/uicontroller/controller.h
- src/services/window/windowservice.h
> fix: [project] switch display of build/cancel button when state changed

- src/plugins/builder/mainframe/buildmanager.cpp
- src/plugins/builder/mainframe/compileoutputpane.cpp
- src/plugins/builder/mainframe/problemoutputpane.cpp
- src/plugins/project/CMakeLists.txt
- src/plugins/project/mainframe/projecttree.cpp
- src/plugins/project/mainframe/recent/recentopenitemdelegate.cpp
- src/plugins/project/mainframe/recent/recentopenitemdelegate.h
- src/plugins/project/mainframe/recent/recentopenview.cpp
- src/plugins/project/mainframe/recent/recentopenview.h
- src/plugins/project/mainframe/recent/recentopenwidget.cpp
- src/plugins/project/mainframe/recent/recentopenwidget.h
1.opened files view
2.build context widget
Log: as title
> fix: [ui] modified ui

- src/common/lsp/protocol/new/basicjsonstructures.h
- src/plugins/codeeditor/gui/private/tabwidget_p.h
- src/plugins/codeeditor/gui/tabwidget.cpp
- src/plugins/codeeditor/gui/texteditor.cpp
- src/plugins/codeeditor/gui/texteditor.h
- src/plugins/codeeditor/lsp/languageclienthandler.cpp
- src/plugins/codeeditor/lsp/languageclienthandler.h
- src/plugins/codeeditor/lsp/private/languageclienthandler_p.h
- src/plugins/codeeditor/symbol/symbolbar.cpp
- src/plugins/codeeditor/symbol/symbolbar.h
- src/plugins/codeeditor/symbol/symbollocator.cpp
- src/plugins/codeeditor/symbol/symbolmanager.cpp
- src/plugins/codeeditor/symbol/symbolmanager.h
- src/plugins/codeeditor/symbol/symbolview.cpp
- src/plugins/codeeditor/symbol/symbolview.h
as title
Log: new feature for symbol
> feat: [editor] Added symbol navigation bar

- 3rdparty/unioncode-qscintilla214/src/qsciscintilla.cpp
> fix: [editor] Fixed issue with indentation exceptions

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
- src/plugins/find/gui/advancedsearchwidget.cpp
- src/plugins/find/gui/searchresultwidget.cpp
- src/plugins/linglong/gui/generatedialog.h
- src/plugins/linglong/gui/mainframe.h
> translations: update translations

- src/plugins/core/gui/dockheader.cpp
- src/plugins/core/gui/dockheader.h
> feat: [workspace] click workspace`s label to switch widget

- src/plugins/codeeditor/symbol/symbolbar.cpp
- src/plugins/codeeditor/symbol/symbolbar.h
- src/plugins/codeeditor/symbol/symbolmanager.cpp
- src/plugins/codeeditor/symbol/symbolmanager.h
- src/plugins/codeeditor/symbol/symbolview.cpp
as title
Log: add icon for `SymbolBar`
> feat: add icon for `SymbolBar`

- src/plugins/codeeditor/symbol/symbolmanager.cpp
- src/plugins/codeeditor/symbol/symbolmanager.h
- src/plugins/codeeditor/symbol/symbolview.cpp
> fix: Fixed the cppcheck warnings

- src/plugins/core/gui/dockheader.cpp
> fix: [workspace] incorret logic

- src/plugins/codeeditor/symbol/symbollocator.cpp
- src/plugins/codeeditor/symbol/symbolview.cpp
- src/plugins/codeeditor/symbol/symbolview.h
- src/plugins/find/findplugin.cpp
> fix: Optimize symbolic interaction logic

- src/plugins/codegeex/copilot.cpp
- src/plugins/codegeex/copilot.h
> fix: [codegeex] The format of the code in the parameters is incorrect.

- debian/changelog
Log:
Change-Id: I5dec489328720573c9ccf3ef6af331ea43793f0d
> tag: update to 1.3.7

- src/plugins/find/gui/advancedsearchwidget.cpp
- src/plugins/find/gui/searchresultitemdelegate.cpp
- src/plugins/project/mainframe/projectdelegate.cpp
- src/plugins/project/mainframe/projecttree.cpp
- src/plugins/project/mainframe/projecttree.h
1.Fixed an issue where the vertical scroll bar obscured the action button in the search results list for Advanced Search 2.Fixed an issue where horizontal scroll bar is not displayed in Project View
> fix: Fixed scrollbar display issue

- src/plugins/cxx/cmake/project/cmakeprojectgenerator.cpp
> fix: [cmake] remove "cancel" action from projcet`s menu

- src/plugins/codeeditor/symbol/symbolbar.cpp
- src/plugins/cxx/lexer/scilexercpp.cpp
> fix: Fixed issue where the symbol bar separator did not change with the theme

- src/plugins/cxx/cmake/project/cmakeprojectgenerator.cpp
- src/plugins/cxx/cmake/project/properties/runCfgWidget/runconfigpane.cpp
> fix: [project] set default working directory of Cmake project`s property

- README.en.md
- README.md
Log:
Change-Id: Ife81ee8f622efa1ebc1e10aea6090e3ddbd9d314
> doc: update readme

- README.en.md
- README.md
update depends
Log:
Change-Id: I25ac615654d01fefa580ceaf4c7f7aa36801320e
> doc: change readme

- src/plugins/codeeditor/symbol/symbolbar.cpp
> fix: Fixed compilation failure issue

- src/plugins/core/uicontroller/controller.cpp
> fix: [controller] dock`s manager can not show all docks

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
- src/plugins/core/uicontroller/controller.cpp
- src/plugins/core/uicontroller/controller.h
- src/plugins/cxx/cmake/project/cmakeprojectgenerator.cpp
- src/plugins/cxx/cmake/project/cmakeprojectgenerator.h
- src/plugins/cxx/cmake/project/properties/configWidget/configpropertywidget.cpp
- src/plugins/cxx/cmake/project/properties/configWidget/configpropertywidget.h
- src/plugins/cxx/cmake/project/properties/configWidget/configureprojpane.cpp
- src/plugins/cxx/ninja/project/ninjaprojectgenerator.cpp
- src/plugins/cxx/ninja/project/ninjaprojectgenerator.h
- src/plugins/java/gradle/project/gradleprojectgenerator.cpp
- src/plugins/java/gradle/project/gradleprojectgenerator.h
- src/plugins/java/maven/project/mavenprojectgenerator.cpp
- src/plugins/java/maven/project/mavenprojectgenerator.h
- src/plugins/javascript/project/jsprojectgenerator.cpp
- src/plugins/javascript/project/jsprojectgenerator.h
- src/plugins/linglong/project/llprojectgenerator.cpp
- src/plugins/linglong/project/llprojectgenerator.h
- src/plugins/project/projectcore.cpp
- src/plugins/project/projectcore.h
- src/plugins/python/python/project/pythonprojectgenerator.cpp
- src/plugins/python/python/project/pythonprojectgenerator.h
- src/plugins/python/python/pythongenerator.h
- src/plugins/recent/mainframe/recentdisplay.cpp
- src/services/project/projectgenerator.cpp
- src/services/project/projectgenerator.h
- src/services/project/projectservice.h
- src/services/window/windowservice.h
> feat: [recent] Optimize the process of opening projects

- src/plugins/project/projectcore.cpp
> fix: [project] dialog adjustsize

- src/plugins/project/transceiver/projectcorereceiver.cpp
> fix: Fixed issue with lsp invalid

- src/plugins/codegeex/codegeex/copilotapi.cpp
- src/plugins/codegeex/codegeex/copilotapi.h
- src/plugins/codegeex/copilot.cpp
- src/plugins/codegeex/copilot.h
> fix: [codegeex] optimized code completion logic

- src/plugins/codegeex/widgets/askpagewidget.cpp
> fix: [codegeex] incorret references button state

- src/plugins/linglong/gui/mainframe.cpp
> fix: [linglong] After creating the project, the data was not cleared.

- src/plugins/core/depend/dependencemanager.cpp
as title
Log: view installtion details
> feat: [Dependence] Added the ability to view details

- debian/control
> fix: Remove duplicate dependencies

- debian/changelog
Log:
Change-Id: I77b68b770a2f93ba3866db37236923ff99a202a9
> tag: update to 1.3.8

- assets/templates/projects/python/console/wizard.json
> fix: [python] failed when create python project

- src/plugins/core/uicontroller/controller.cpp
> fix: [workspace] dockHeader dose not change when open project

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
- src/plugins/project/projectcore.cpp
set default button
Log:
Change-Id: I944aba0e8b682b4760900b15e95e9bb579953d71
> chore: modify button style in open project dialog

- src/plugins/python/python/pythondebug.cpp
- src/plugins/python/python/pythondebug.h
- src/tools/debugadapter/debugger/python/pythondebugger.cpp
- src/tools/debugadapter/debugger/python/pythondebugger.h
When multiple applications are open, debugging the Python project causes the applications to freeze.
Log: as title
bug: https://pms.uniontech.com/bug-view-267559.html
> fix: [python] debugging python project cause frozen

- debian/changelog
Log:
Change-Id: I7dc1d0535599382040c827d3c1ce950bde76d22d
> tag: update to 1.3.10

- src/common/util/eventdefinitions.h
- src/plugins/codeeditor/gui/private/texteditor_p.cpp
- src/plugins/debugger/dap/dapdebugger.cpp
- src/plugins/debugger/dap/dapdebugger.h
- src/plugins/debugger/dap/debugsession.cpp
- src/tools/debugadapter/dapsession.cpp
- src/tools/debugadapter/debugger/debugger.h
- src/tools/debugadapter/debugger/gdbmi/gdbdebugger.cpp
- src/tools/debugadapter/debugger/gdbmi/gdbdebugger.h
- src/tools/debugadapter/debugger/javascript/jsdebugger.cpp
- src/tools/debugadapter/debugger/javascript/jsdebugger.h
- src/tools/debugadapter/debugmanager.cpp
- src/tools/debugadapter/debugmanager.h
> feat: [debugger] add functional of "run to line"

- src/plugins/cxx/cmake/builder/generator/cmakebuildergenerator.cpp
Modify prompt information
Log: fix issue
> fix: Fixed an issue where cmake could not be found when the project was opened

- src/plugins/core/modules/pluginmanagermodule.cpp
> fix: [crash] crash when opening pluginModule by menu action

- src/plugins/codegeex/widgets/inputeditwidget.cpp
> fix: build failed in deepin v23

- src/plugins/codegeex/copilot.cpp
> fix: update interface

- src/plugins/console/consolemanager.cpp
> fix: [terminal] Fixed an issue with incorrect terminal name

- src/plugins/python/CMakeLists.txt
- src/plugins/python/python/option/interpreterwidget.cpp
- src/plugins/python/python/option/interpreterwidget.h
- src/plugins/python/python/option/pythonoptionwidget.cpp
- src/plugins/python/python/project/properties/configpropertywidget.cpp
- src/services/option/optionutils.cpp
- src/services/option/toolchaindata.h
> feat: [python] add "select local interpreter" function

- src/plugins/codeeditor/gui/private/texteditor_p.cpp
- src/plugins/codeeditor/gui/private/texteditor_p.h
- src/plugins/codeeditor/gui/texteditor.cpp
- src/plugins/codeeditor/gui/texteditor.h
- src/plugins/codegeex/copilot.cpp
- src/plugins/codegeex/copilot.h
- src/plugins/codegeex/eventreceiver.cpp
- src/plugins/codegeex/eventreceiver.h
- src/plugins/codegeex/widgets/inlinechatwidget.cpp
- src/plugins/codegeex/widgets/inlinechatwidget.h
- src/services/editor/editor_define.h
1.Fixed some interaction issues
2.Optimized prompt words
> fix: Fixed some issues with inline chat

- src/plugins/codegeex/codegeex/askapi.cpp
- src/plugins/codegeex/codegeex/askapi.h
- src/plugins/codegeex/codegeexmanager.cpp
- src/plugins/codegeex/codegeexmanager.h
- src/plugins/codegeex/copilot.cpp
- src/plugins/codegeex/eventreceiver.cpp
- src/plugins/codegeex/widgets/askpagewidget.cpp
- src/plugins/codegeex/widgets/askpagewidget.h
- src/plugins/codegeex/widgets/inputeditwidget.cpp
- src/plugins/codegeex/widgets/inputeditwidget.h
- src/plugins/codegeex/widgets/messagecomponent.cpp
- src/plugins/codegeex/widgets/messagecomponent.h
- src/scripts/rag/embedding.py
- src/scripts/rag/generate.py
- src/scripts/rag/install.sh
- src/scripts/rag/query.py
> feat: [AI] Optimize the experience of AI-related features

- 3rdparty/unioncode-qscintilla214/src/PlatQt.cpp
- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
- src/plugins/codegeex/copilot.cpp
- src/plugins/codegeex/widgets/inlinechatwidget.cpp
as title
Log: update the translation
> translation: Update the translation

- src/plugins/codeeditor/gui/private/texteditor_p.cpp
- src/plugins/codegeex/widgets/inlinechatwidget.cpp
1.Fixed app crash when asking questions
2.Fix shortcut invalid issue
Log: fix issue
> fix: Fix some issues of Inline Chat

- debian/changelog
Log:
Change-Id: Ib9235558a127e13408f9e4e2068da464f31bfc44
> tag: update to 1.3.11

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
- src/plugins/codegeex/codegeex.cpp
- src/plugins/codegeex/codegeex/askapi.cpp
- src/plugins/codegeex/codegeexmanager.cpp
- src/plugins/codegeex/codegeexmanager.h
- src/plugins/codegeex/eventreceiver.cpp
- src/plugins/codegeex/eventreceiver.h
- src/plugins/codegeex/widgets/inputeditwidget.cpp
- src/plugins/codegeex/widgets/inputeditwidget.h
- src/scripts/rag/generate.py
> fix: [Ai] Optimize user experience

- src/plugins/codegeex/codegeexmanager.cpp
Log:
Change-Id: I44099a28133c4dcac91523b0b10f800442daaf4b
> fix: build failed without header

- assets/translations/zh_CN.ts
- src/common/util/environment.cpp
Problems caused by environment variables not taking effect
Bug: https://pms.uniontech.com/bug-view-276917.html
Log: fix bug
> fix: Fix the issue of Python LSP not working

- src/plugins/codegeex/codegeexmanager.cpp
- src/plugins/python/python/option/interpreterwidget.cpp
Log: as title
bug: https://pms.uniontech.com/bug-view-276933.html
> fix: [python] default interpreter can not be removed

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
- src/plugins/debugger/reversedebug/reversedebugger.cpp
- src/plugins/debugger/reversedebug/rrdialog.cpp
Log: Prompt users to obtain a higher version of rr on their own.
bug: https://pms.uniontech.com/bug-view-277079.html
https://pms.uniontech.com/bug-view-277071.html
> fix: [reversedebug] add prompt information

- assets/translations/zh_CN.ts
- src/plugins/codegeex/codegeex/askapi.cpp
- src/plugins/codegeex/widgets/inlinechatwidget.cpp
1.Fix crash issues
2.Optimize inline chat
Log: fix issue
> fix: Optimize inline chat

- src/plugins/codegeex/widgets/inlinechatwidget.cpp
After the code is generated, using quick question, the program to crashed
Bug: https://pms.uniontech.com/bug-view-277691.html
Log: fix bug
> fix: [InlineChat] Fix program crash issue

- src/plugins/core/depend/pipinstaller.cpp
- src/plugins/python/pythonplugin.json
as title
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-277843.html
> fix: [dep] Fixed python dependency installation issues

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
- src/plugins/option/optioncore/mainframe/shortcutdialog.cpp
- src/plugins/option/optioncore/mainframe/shortcutsettingwidget.cpp
The title name does not correspond to the operation
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-277807.html
> fix: [Shortcut] Change the dialog title name

- assets/templates/files/python/template.py
- src/plugins/codegeex/codegeexmanager.h
1.python template error
2.incorrect macro of check arm
Log: https://pms.uniontech.com/bug-view-278117.html
https://pms.uniontech.com/bug-view-278019.html
> bug: fix bugs

- src/plugins/codeeditor/gui/private/texteditor_p.cpp
- src/plugins/codegeex/widgets/inlinechatwidget.cpp
as title
Log: Optimized prompt
> fix: [InlineChat] Optimized prompt

- src/plugins/codegeex/widgets/inlinechatwidget.cpp
Do not use chunk as prompts
Log: fix issue
> fix: [InlineChat] Modify the prompts

- debian/changelog
Log:
Change-Id: I0c31415ae39796086d71a91ae192ee3330e5f2b8
> tag: update to 1.3.12

- src/plugins/codegeex/codegeex.cpp
- src/plugins/codegeex/codegeexmanager.h
- src/plugins/codegeex/copilot.cpp
- src/plugins/codegeex/eventreceiver.cpp
- src/plugins/codegeex/eventreceiver.h
- src/plugins/codegeex/widgets/inputeditwidget.cpp
- src/plugins/core/gui/navigationbar.cpp
- src/plugins/core/gui/navigationbar.h
- src/plugins/core/uicontroller/controller.cpp
- src/plugins/core/uicontroller/controller.h
- src/plugins/core/uicontroller/mainwindow.cpp
- src/plugins/debugger/debuggerplugin.cpp
- src/services/window/windowservice.h
> feat: [codegeex] optimized usage of codegeex plugin

- assets/configures/language.support
- src/plugins/codeeditor/lexer/lexermanager.cpp
- src/plugins/codegeex/codegeex/askapi.cpp
- src/plugins/codegeex/widgets/inlinechatwidget.cpp
The prompt words and file content exceeded the maximum limit
Log: fix issue
> fix: [InlineChat] The answer content was empty

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
- src/plugins/codegeex/codegeex/askapi.cpp
- src/plugins/codegeex/codegeex/askapi.h
- src/plugins/codegeex/widgets/inputeditwidget.cpp
- src/plugins/codegeex/widgets/intropage.cpp
- src/scripts/rag/generate.py
1. The speed of inserting vector data into the database has become faster.
2. fix some bugs related multithreads.
3. Ui and tip
log: as title
> fix: [codegeex] optimized efficiency and functionality

- src/base/abstractinlinecompletionprovider.cpp
- src/base/abstractinlinecompletionprovider.h
- src/plugins/codeeditor/codeeditor.cpp
- src/plugins/codeeditor/gui/completion/codecompletionwidget.cpp
- src/plugins/codeeditor/gui/completion/codecompletionwidget.h
- src/plugins/codeeditor/gui/private/texteditor_p.cpp
- src/plugins/codeeditor/gui/private/texteditor_p.h
- src/plugins/codeeditor/gui/tabwidget.cpp
- src/plugins/codeeditor/gui/tabwidget.h
- src/plugins/codeeditor/gui/texteditor.cpp
- src/plugins/codeeditor/gui/texteditor.h
- src/plugins/codeeditor/gui/workspacewidget.cpp
- src/plugins/codeeditor/gui/workspacewidget.h
- src/plugins/codeeditor/utils/resourcemanager.cpp
- src/plugins/codeeditor/utils/resourcemanager.h
- src/plugins/codegeex/codegeex/codegeexcompletionprovider.cpp
- src/plugins/codegeex/codegeex/codegeexcompletionprovider.h
- src/plugins/codegeex/copilot.cpp
- src/plugins/codegeex/copilot.h
- src/plugins/codegeex/eventreceiver.cpp
- src/plugins/codegeex/eventreceiver.h
- src/services/editor/editorservice.h
as title
Log: Optimize intelligent completion
> feat: [completion] Optimize intelligent completion

- src/base/abstractlocator.h
- src/plugins/codegeex/codegeex/askapi.cpp
- src/plugins/codegeex/codegeex/copilotapi.cpp
- src/plugins/codegeex/codegeex/copilotapi.h
- src/plugins/codegeex/codegeexmanager.cpp
- src/plugins/codegeex/copilot.cpp
- src/plugins/codegeex/copilot.h
- src/plugins/codegeex/widgets/inputeditwidget.cpp
- src/plugins/codegeex/widgets/messagecomponent.cpp
- src/scripts/rag/query.py
update interface
fix some issues
Log: as title
> fix: [codegeex] update interface

- src/plugins/binarytools/configure/default_binarytools.json
- src/plugins/codeeditor/gui/completion/codecompletionwidget.cpp
- src/plugins/codeeditor/gui/private/texteditor_p.cpp
- src/plugins/codeeditor/gui/private/texteditor_p.h
- src/plugins/codeeditor/gui/texteditor.cpp
- src/plugins/codeeditor/gui/texteditor.h
- src/plugins/codegeex/codegeex/codegeexcompletionprovider.cpp
> fix: [completion] Fixed an issue where the cursor position was abnormal when completion was canceled

- src/plugins/cxx/cmake/option/kitmanager.cpp
- src/plugins/cxx/cmake/option/kitmanager.h
- src/plugins/cxx/cmake/project/properties/configutil.cpp
- src/plugins/cxx/cmake/project/properties/configutil.h
- src/plugins/cxx/cmake/settings/kitoptionwidget.cpp
Save the CMake project properties in Json format
Log: Refactoring the CMake project properties
> refactor: [project] Refactoring the CMake project properties

- src/plugins/codegeex/codegeex/copilotapi.cpp
- src/plugins/codegeex/codegeex/copilotapi.h
> feat: [codegeex] add command_type arguments of inlinechat api

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
- src/plugins/codegeex/widgets/inputeditwidget.cpp
- src/plugins/codegeex/widgets/referencepopup.cpp
- src/plugins/codegeex/widgets/referencepopup.h
- src/plugins/core/locator/popupwidget.cpp
> feat: [codegeex] optimized of reference files functional

- src/plugins/codeeditor/gui/private/texteditor_p.cpp
- src/plugins/codeeditor/gui/tabwidget.cpp
- src/plugins/codegeex/codegeex/copilotapi.cpp
- src/plugins/codegeex/codegeex/copilotapi.h
- src/plugins/codegeex/copilot.cpp
- src/plugins/codegeex/copilot.h
- src/plugins/codegeex/widgets/inlinechatwidget.cpp
as title
Log: Interface adaptation
> feat: [inline chat] Adapt the inline chat interface

- src/plugins/binarytools/configure/default_binarytools.json
Add `UOS应用迁移助手` to the default tool
Log: Add a default tool
> feat: [tool] Add a default tool

- src/base/abstractinlinecompletionprovider.cpp
- src/base/abstractinlinecompletionprovider.h
- src/plugins/codeeditor/gui/completion/codecompletionwidget.cpp
- src/plugins/codeeditor/gui/texteditor.cpp
- src/plugins/codegeex/codegeex/codegeexcompletionprovider.cpp
- src/plugins/codegeex/codegeex/codegeexcompletionprovider.h
as title
Log: Optimize intelligent completion
> fix: [completion] Optimize intelligent completion

- src/plugins/codegeex/widgets/inputeditwidget.cpp
- src/plugins/codegeex/widgets/referencepopup.cpp
- src/plugins/codegeex/widgets/referencepopup.h
> feat: [codegeex] optimized reference dialog

- debian/changelog
Log:
Change-Id: Ifa74308bc9a9309fb7c3f7b355829300380c00ad
> tag: update to 1.3.15

- src/plugins/codeeditor/gui/texteditor.cpp
> fix: [inline chat] After the code is generated, the editor view scrolled

- debian/control
Log:
Change-Id: Id0ff45d8d545ecb3590aaa9482d23ca9dc902081
> feat: dev lib add dependency

- src/plugins/codeeditor/gui/texteditor.cpp
> fix: [editor] The editor comment feature is abnormal

- src/plugins/codegeex/codegeex.cpp
- src/plugins/core/builtin/texts/uc_left_show_16px.svg
- src/plugins/core/builtin/texts/uc_right_show_16px.svg
- src/plugins/core/core.qrc
- src/plugins/core/uicontroller/controller.cpp
- src/plugins/core/uicontroller/controller.h
- src/plugins/core/uicontroller/mainwindow.cpp
- src/plugins/debugger/debuggerplugin.cpp
- src/services/window/windowelement.h
- src/services/window/windowservice.h
change the way of show dockWidget at right position
Log: as title
> feat: [controller] modified interface of windowService

- src/common/util/eventdefinitions.h
- src/plugins/codeeditor/gui/private/texteditor_p.cpp
- src/plugins/codeeditor/gui/private/texteditor_p.h
- src/plugins/codeeditor/gui/texteditor.cpp
- src/plugins/codegeex/copilot.cpp
- src/plugins/codegeex/copilot.h
- src/plugins/codegeex/eventreceiver.cpp
- src/plugins/codegeex/eventreceiver.h
- src/plugins/codegeex/widgets/inlinechatwidget.cpp
- src/plugins/codegeex/widgets/inlinechatwidget.h
- src/plugins/codegeex/widgets/inputeditwidget.cpp
> fix: [inline chat] The window is minimized and then restored. The inline chat is abnormal

- assets/configures/editorstyle_cpp.support
- src/plugins/codeeditor/lsp/languageworker.cpp
as title
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-282285.html
> fix: [editor] The highlighting effect is abnormal

- src/tools/languageadapter/main.cpp
as title
Log: Code optimization
> chore: Remove useless code

- 3rdparty/unioncode-qscintilla214/src/qsciscintillabase.cpp
> fix: [editor] Scroll through the editor, the focus is set to the editor

- src/plugins/python/pythonplugin.json
- src/tools/languageadapter/main.cpp
- src/tools/languageadapter/remotechecker.cpp
Replace the lsp with `python-lsp-server`
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-282531.html
> fix: [python] The python files syntax highlighting failed

- src/plugins/project/projectcore.cpp
- src/plugins/project/projectcore.h
as title
Log: Add project infomations to macro variables
> feat: [project] Add project infomations to macro variables

- src/plugins/codeeditor/gui/private/texteditor_p.cpp
- src/plugins/codeeditor/gui/texteditor.cpp
- src/plugins/codegeex/codegeex/copilotapi.cpp
- src/plugins/codegeex/widgets/inlinechatwidget.cpp
Network request error, but no error handling
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-281817.html
> fix: [inline chat] No result was returned for a long time

- src/plugins/debugger/dap/dapdebugger.cpp
1.close project can`t quit debugging state
2.Pausing the Python debugging process may cause some exceptions
Log: as title
> fix: [python] issues of debug python program

- debian/changelog
Log:
Change-Id: I47bbf99bbf4942cb280960b99bc7a64b5cb31772
> tag: update to 1.3.16

- src/plugins/codeeditor/gui/completion/codecompletionwidget.cpp
- src/plugins/codeeditor/gui/tabwidget.cpp
- src/plugins/codeeditor/gui/texteditor.cpp
- src/plugins/codeeditor/gui/texteditor.h
> fix: [editor] The cursor is abnormal after completion

- src/plugins/cxx/cmake/settings/compileroptionwidget.cpp
- src/plugins/cxx/cmake/settings/debuggeroptionwidget.cpp
- src/plugins/cxx/cmake/settings/tooloptionwidget.cpp
- src/plugins/python/python/option/interpreterwidget.cpp
> fix: Open settings dialog the program crash

- src/plugins/codegeex/widgets/inlinechatwidget.cpp
as title
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-278015.html
> fix: [inline chat] The keypad Enter key cannot trigger a submit request

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
- src/plugins/core/modules/dependencemodule.cpp
- src/plugins/python/CMakeLists.txt
- src/plugins/python/installer/pipinstaller.cpp
- src/plugins/python/installer/pipinstaller.h
- src/plugins/python/python/pythondebug.cpp
- src/plugins/python/python/pythondebug.h
- src/plugins/python/pythonplugin.cpp
- src/plugins/python/pythonplugin.h
- src/plugins/python/pythonplugin.json
- src/plugins/python/utils/utils.cpp
- src/plugins/python/utils/utils.h
- src/tools/debugadapter/debugger/python/pythondebugger.cpp
- src/tools/languageadapter/main.cpp
Installing python depends on the specified path
Log: fix issue
> fix: [python] Unable to install python dependencies

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
- src/plugins/debugger/dap/dapdebugger.cpp
- src/tools/debugadapter/debugger/python/pythondebugger.cpp
1.can`t re-debug after initailized failed or launch failed
2.connect times out while trying to connect before the debugpy port is ready, adding a wait of 500 milliseconds
Log: as title
> fix: [debugger] issues of debugging

- src/common/settings/settingdata.cpp
- src/common/settings/settingdata.h
- src/common/settings/settings.cpp
- src/common/settings/settings.h
as title
Log: Add a general configuration module
> feat: [settings] Add a general configuration module

- src/plugins/codegeex/codegeex.cpp
- src/plugins/codegeex/codegeexmanager.cpp
- src/plugins/codegeex/codegeexmanager.h
- src/plugins/console/CMakeLists.txt
- src/plugins/console/consolewidget.cpp
- src/plugins/console/generateinput.cpp
- src/plugins/console/generateinput.h
- src/services/CMakeLists.txt
- src/services/ai/aiservice.h
1.add service of Ai to support other plugins use it 2.add intelligent command generator with terminal
Log: as title
> feat: [terminal] Add Smart Terminal Functionality

- debian/changelog
Log:
Change-Id: I7e23dc54a1dd953fdf9838be1b352b125660b53f
> tag: update to 1.3.17

- src/framework/framework.h
Log:
Change-Id: I1f03fc39bc8e85926751eccb83e9390705a9f0c3
> chore: add comment

- src/plugins/core/gui/dockheader.cpp
- src/plugins/core/uicontroller/mainwindow.cpp
- src/plugins/find/gui/advancedsearchwidget.cpp
- src/plugins/find/gui/searchresultitemdelegate.cpp
- src/plugins/find/gui/searchresultitemdelegate.h
- src/plugins/find/gui/searchresultmodel.cpp
- src/plugins/find/gui/searchresultwidget.cpp
- Replaced eventFilter with editorEvent for better event handling.
- Adjusted mouse event handling to update the view correctly.
- Added a new method to draw option backgrounds for better UI feedback.
- Updated drawing methods to ensure consistent icon sizes and margins.
Log: Fix UI issues
Bug: https://pms.uniontech.com/bug-view-272579.html
> fix: [searchresultitemdelegate] Fix UI issues

- src/plugins/project/projectcore.cpp
> fix: [project] When opening the project, the build kit is incorrect.

- src/plugins/core/uicontroller/controller.cpp
- src/plugins/core/uicontroller/mainwindow.cpp
- src/plugins/core/uicontroller/mainwindow.h
- src/plugins/project/mainframe/projecttree.cpp
- src/plugins/symbol/mainframe/symboltreeview.cpp
reduce width of separator between docks
Log: as title
> feat: [mainwindow] optimized ui of mainWindow

- src/plugins/find/gui/searchresultitemdelegate.cpp
- src/scripts/CMakeLists.txt
> fix: [search] The background color position is incorrect

- assets/translations/zh_CN.ts
as title
Log: update translations
> chore: Update translatoins

- src/plugins/codeeditor/gui/tabbar.cpp
- src/plugins/cxx/cmake/project/cmakeasynparse.cpp
- src/plugins/project/mainframe/projecttree.cpp
> fix: Display the directory without selecting the file

- src/plugins/aimanager/CMakeLists.txt
When compiling with the project, do not search for duc-xx libraries.
Log: as title
> fix: issues of build

- src/plugins/aimanager/option/detailwidget.cpp
Log:
Change-Id: I9e4000a8c580289f65aa3df54b0860118e409b7f
> fix: include missing header

- src/plugins/aimanager/aiplugin.cpp
Log:
Change-Id: I55e992d950c4d081d9acb348fa9a492344089ba7
> chore: revert ai option

- debian/changelog
Log: tag update
Change-Id: I2572d783802c32d8056b0c43e060d610e2ecd882
> tag: update to 1.4.0

- src/plugins/cxx/cmake/project/properties/runCfgWidget/runconfigpane.cpp
> fix: [cmake] Unable to save changes while in edit mode

- assets/translations/en_US.ts
- assets/translations/zh_CN.ts
- src/plugins/recent/mainframe/sessionitemwidget.cpp
as title
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-298385.html
> fix: [session] Some scenes are not translated

- src/plugins/python/python/option/interpreterwidget.cpp
- src/plugins/python/python/option/interpreterwidget.h
as title
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-298501.html
> fix: [python] Package not updated when switching interpreter

- src/plugins/core/session/sessionmodel.cpp
- src/plugins/recent/mainframe/sessionitemwidget.cpp
- src/plugins/recent/mainframe/sessionitemwidget.h
as title
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-298387.html
> fix: [session] Optimized the display of session name

- src/plugins/find/gui/advancedsearchwidget.cpp
> fix: [serach] The replacement information is displayed incorrectly

- src/plugins/python/python/option/interpreterwidget.cpp
- src/plugins/python/python/option/interpreterwidget.h
The pip is not installed
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-298501.html
> fix: [python] Package not updated

- debian/changelog
Log:
Change-Id: I7857df17f655f8d50e7b1afa87a551836440b3f4
> tag: update to 1.4.1

- src/plugins/aimanager/codegeex/codegeexllm.cpp
- src/plugins/aimanager/openai/openaicompatiblellm.cpp
- src/plugins/codegeex/codegeexmanager.cpp
- src/plugins/codegeex/codegeexmanager.h
- src/plugins/codegeex/widgets/askpagewidget.cpp
- src/plugins/codegeex/widgets/askpagewidget.h
- src/plugins/codegeex/widgets/messagecomponent.cpp
switch state when received failed message
cancel requesting when terminate before prompt preprocessed
Log: as title
> fix: [Ai] fix issues of compatible llm

- src/plugins/smartut/manager/uttaskpool.cpp
> fix: [ut] IDE crashed

- src/plugins/smartut/common/itemnode.cpp
- src/plugins/smartut/common/itemnode.h
- src/plugins/smartut/common/projectitemdelegate.cpp
- src/plugins/smartut/common/projectitemmodel.cpp
- src/plugins/smartut/common/projectitemmodel.h
- src/plugins/smartut/gui/projecttreeview.cpp
- src/plugins/smartut/gui/projecttreeview.h
- src/plugins/smartut/gui/smartutwidget.cpp
- src/plugins/smartut/gui/smartutwidget.h
- src/plugins/smartut/utils/utils.cpp
> feat: [ut] Add the feature to update the project tree

- src/plugins/core/notify/gui/itemdelegate.cpp
> fix: [notification] Fixed item height issue

- src/common/lsp/client/client.cpp
- src/common/lsp/protocol/new/basicjsonstructures.cpp
- src/common/lsp/protocol/new/basicjsonstructures.h
- src/common/lsp/protocol/new/languagefeatures.cpp
- src/common/lsp/protocol/new/languagefeatures.h
- src/common/lsp/protocol/protocol.cpp
- src/plugins/codeeditor/codeeditor.cpp
- src/plugins/codeeditor/gui/private/workspacewidget_p.h
- src/plugins/codeeditor/gui/texteditor.cpp
- src/plugins/codeeditor/gui/workspacewidget.cpp
- src/plugins/codeeditor/gui/workspacewidget.h
- src/plugins/codeeditor/lsp/languageclienthandler.cpp
- src/plugins/codeeditor/lsp/private/languageclienthandler_p.h
- src/plugins/codeeditor/utils/resourcemanager.cpp
- src/plugins/codeeditor/utils/resourcemanager.h
- src/plugins/codegeex/codegeex.cpp
- src/plugins/codegeex/codegeexmanager.cpp
- src/plugins/codegeex/codegeexmanager.h
- src/plugins/smartut/gui/settingdialog.cpp
- src/plugins/smartut/gui/settingdialog.h
as title
Log: Added diagnostic information repair functionality.
> feat: [diagnostic] Added diagnostic information repair functionality

- src/plugins/codeeditor/lsp/languageclienthandler.cpp
> fix: The diagnostic info cannot be displayed

- src/plugins/builder/mainframe/buildmanager.cpp
- src/plugins/cxx/cmake/project/cmakeprojectgenerator.cpp
- src/plugins/cxx/cmake/project/transceiver/projectcmakereceiver.cpp
- src/plugins/cxx/cmake/project/transceiver/projectcmakereceiver.h
- src/plugins/debugger/runner/runner.cpp
- src/plugins/project/mainframe/projecttree.cpp
- src/services/builder/builderglobals.h
disable build/run/cmake.. actions in right-clicked menu and mainwindow`s menu
Log: as title
> fix: [project] Disable actions for non-active project

- src/plugins/codeeditor/gui/texteditor.cpp
as title
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-284991.html
> fix: [editor] Comment exception

- src/plugins/codeeditor/lsp/languageclienthandler.cpp
- src/plugins/codeeditor/lsp/private/languageclienthandler_p.h
as title
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-286251.html
> fix: [editor] The tooltip is empty

- src/base/CMakeLists.txt
Log:
Change-Id: Id5c85a4f865e619ed1dd16dbee397d197f0fcfd2
> chore: add comment in base cmake file

- CMakeLists.txt
enable fpic flag
Log:
Change-Id: I1ae86cb8051484b80c455874ee3427436a168370
> fix: build faild on arm platform

- debian/changelog
Log:
Change-Id: I897dcd763bffadd1f6a5f1d6ab74422fcf9f8e8a
> tag: update to 1.4.4

- src/plugins/CMakeLists.txt
Log:
Change-Id: I6f416e554768043e54abddb356ebe4e935f7277a
> chore: disable smartut
